TCM-117 | Build dummy onboarding screen
hyfn/trx-consumer-android pull request #10
Opened 2021-03-28 20:14 UTC by halilyesilyurt

## Description

### Summary

- [x] Completed dummy onboarding screen.

### Issue

[TCM-117](https://hyfnla.atlassian.net/browse/TCM-117)

### Video/Screenshot

Step 1
![onboarding_1](https://user-images.githubusercontent.com/30659854/112766632-3bfec080-901b-11eb-9bf8-139efe3373f9.png)

Step 2
![onboarding_2](https://user-images.githubusercontent.com/30659854/112766634-3dc88400-901b-11eb-878d-5b5f52c587d5.png)

Step 3
![onboarding_3](https://user-images.githubusercontent.com/30659854/112766636-3ef9b100-901b-11eb-8bc6-1abd7da9de37.png)

2021-04-01 18:43 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/onboarding/OnBoardingFragment.kt
> +    @SuppressLint("ClickableViewAccessibility")
Don't think this is needed

2021-04-01 18:43 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/onboarding/OnBoardingFragment.kt
> +
Can remove empty space

2021-04-01 18:48 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/onboarding/OnBoardingViewState.kt
> +    val title: Int
Let's annotate all the string res getters with `@get:StringRes`

2021-04-01 18:48 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/onboarding/OnBoardingViewState.kt
> +    val image: Int
Let's annotate with `@get:DrawableRes`

2021-04-01 19:02 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/onboarding/OnBoardingViewState.kt
> +                ?: VIRTUAL
Can fit in the line above

2021-04-01 19:05 UTC, VivekV95 commented on app/src/main/res/layout/fragment_onboarding.xml
> +
Need an additional divider here

2021-04-01 19:11 UTC, VivekV95 commented on app/src/main/res/layout/fragment_onboarding.xml
> +<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
I'm not sure if this view is meant to be scrollable, seems unnecessary if it is. @onodude can you confirm? If not, we can make the header image's height dynamic and have it constraint to the bottom view.

2021-04-01 19:13 UTC, VivekV95 commented on app/src/main/res/layout/fragment_onboarding.xml
> +            app:layout_constraintTop_toBottomOf="@+id/lblItemThree" />
Bottom margin isn't showing on the first screen:
[Screen1](https://user-images.githubusercontent.com/39810816/113342721-6e970a80-92f4-11eb-91f1-4f90bc2192cf.jpg)
[Screen2](https://user-images.githubusercontent.com/39810816/113342748-79519f80-92f4-11eb-8a95-1b52af315d7d.jpg)

2021-04-01 19:14 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/onboarding/OnBoardingViewState.kt
> +    val title: Int
We have tickets to start doing this on Xpass and Phase3

2021-04-01 19:17 UTC, VivekV95 requested changes
Left a few comments and a question

2021-04-03 20:57 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/screens/onboarding/OnBoardingFragment.kt
> +    @SuppressLint("ClickableViewAccessibility")
I removed it.

2021-04-03 20:57 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/screens/onboarding/OnBoardingFragment.kt
> +
Completed.

2021-04-03 20:57 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/screens/onboarding/OnBoardingViewState.kt
> +    val title: Int
Completed.

2021-04-03 20:57 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/screens/onboarding/OnBoardingViewState.kt
> +    val image: Int
Completed.

2021-04-03 20:58 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/screens/onboarding/OnBoardingViewState.kt
> +                ?: VIRTUAL
Completed.

2021-04-03 20:58 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_onboarding.xml
> +
Completed.

2021-04-03 21:00 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_onboarding.xml
> +<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
All items may not be shown in small screens. Because of this i used ScrollView.

2021-04-03 21:02 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_onboarding.xml
> +            app:layout_constraintTop_toBottomOf="@+id/lblItemThree" />
Like i said above comment, i think you need to scroll the screen.

2021-04-06 00:36 UTC, VivekV95 requested changes
Looks great! Just a couple things:
[Screen 1 largest font size](https://user-images.githubusercontent.com/39810816/113642642-e5f6d200-9645-11eb-91f6-6b1640ec5de9.png) is missing margin below the button
[Screen 3 regular font size](https://user-images.githubusercontent.com/39810816/113642686-04f56400-9646-11eb-95bb-f6ca0e7acb8a.png) needs a margin at the end of the title

2021-04-08 16:43 UTC, halilyesilyurt commented
> Looks great! Just a couple things:
> [Screen 1 largest font size](https://user-images.githubusercontent.com/39810816/113642642-e5f6d200-9645-11eb-91f6-6b1640ec5de9.png) is missing margin below the button
> [Screen 3 regular font size](https://user-images.githubusercontent.com/39810816/113642686-04f56400-9646-11eb-95bb-f6ca0e7acb8a.png) needs a margin at the end of the title

Completed.

2021-04-08 22:34 UTC, onodude approved these changes
thanks!

2021-04-08 22:34 UTC, merged