TCM-454 | Implement launch auth loading sequence
hyfn/trx-consumer-android pull request #100
Opened 2021-06-02 20:12 UTC by VivekV95

## Description
Refresh access token and load user on logged in launch

### Summary

- [x] Introduce loading sequence on logged in app launch
- [x] Refresh token in launch loading
- [x] Kick user to `Splash` if loading fails  

### Issue

[TCM-454](https://hyfnla.atlassian.net/browse/TCM-454)

### Video/Screenshot

[Not logged in launch](https://drive.google.com/file/d/16ZWJo1uwrtQqfeYyiFPYfl_YFr0OCAi8/view?usp=sharing)
[Logged in launch](https://drive.google.com/file/d/1kJq0zg_bGkoqoD9aBhDmzXVPx9BG_juB/view?usp=sharing)
[Persist logout](https://drive.google.com/file/d/1gcnds-Zgi3zY8CCtFsDQIdKiZ-LnUFuG/view?usp=sharing)
[Loading failure](https://drive.google.com/file/d/1s4AtiheS665HqpWEG3-SoXIe0LzqkD_N/view?usp=sharing)

2021-06-02 21:32 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/managers/NavigationManager.kt
> +        setUpTabs(navController, activity)
Are you able to use KTX functions to simplify this progress? https://developer.android.com/kotlin/ktx/extensions-list#for_navcontroller

2021-06-02 21:38 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/loading/LoadingFragment.kt
> +        }
I get that this apply block looks cleaner but there's a bit of inconsistency with how the AlertModel is being created app wide. Are we using `apply` blocks like this to create `AlertModels` or are we doing like how `SettingsFragment`, `AddCardFragment`, etc?

2021-06-02 21:40 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/loading/LoadingViewModel.kt
> +            eventShowHud.postValue(false)
Maybe this event can be called at the end since theres another backend call on Line 47?

2021-06-02 21:41 UTC, vespertineSiren requested changes
Just a few small thoughts in my first pass through.

2021-06-02 21:59 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/managers/NavigationManager.kt
> +        setUpTabs(navController, activity)
Not seeing any that apply here, anything in particular you had in mind?

2021-06-02 22:00 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/loading/LoadingViewModel.kt
> +            eventShowHud.postValue(false)
`updateBeforeLogout` just clears cache, but will implement regardless

2021-06-02 22:03 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/loading/LoadingFragment.kt
> +        }
I pretty much always prefer scope functions when calling anything more than a couple times unless the indentation starts to get crazy

2021-06-02 22:17 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/managers/NavigationManager.kt
> +        setUpTabs(navController, activity)
[Inlined the graph inflation](https://github.com/hyfn/trx-consumer-android/pull/100/files#diff-d1d55923a263ecffd17fa21be833b27635a8d5747a6bb8dc5482efb8c1091072R71), should make it a tiny bit cleaner

2021-06-02 22:18 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/loading/LoadingViewModel.kt
> +            eventShowHud.postValue(false)
[Done](https://github.com/hyfn/trx-consumer-android/pull/100/files#diff-cfde734d82a73b1ffdb5cb4cbef2bde658aa3d0da2657c751e334b0fdf61adadR49)

2021-06-03 02:27 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/loading/LoadingFragment.kt
> +        }
Cool. Not a big deal

2021-06-03 02:28 UTC, vespertineSiren approved these changes
No complaints or nitpicks on my end

2021-06-03 21:12 UTC, onodude approved these changes
thank you!

2021-06-03 21:12 UTC, merged