TCM-371 |  Polish trainer screen
hyfn/trx-consumer-android pull request #101
Opened 2021-06-02 21:24 UTC by devender197

## Description

### Summary

- [ ] ViewModel, Fragment, required adapter, trainer Endpoints created.
- [ ] Refactor Trainer to TrainerDetail

### Issue

[TCM-371](https://hyfnla.atlassian.net/browse/TCM-371)

### Video/Screenshot

https://user-images.githubusercontent.com/24737954/120554040-1fca2780-c3ae-11eb-97b0-74d14bf8142d.mov

2021-06-03 18:58 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/TrainerModel.kt
> +        get() = mutableListOf<String>().apply {
Not a big deal, but can just do `trainerCertifications + listOf(trainerCoachingStyle)`

2021-06-03 19:03 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/TrainerProgramModel.kt
> +    // MARK: - Test
This is iOS's equivalent of our `//region`s, let's create regions here if needed

2021-06-03 19:04 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/TrainerProgramModel.kt
> +
Couple extra lines here

2021-06-03 19:06 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/TrainerProgramModel.kt
> +    var durationInMinutes: Int = 0
Any reason for pulling out of constructor? If not, let's keep them inside as we do that everywhere else on android.

2021-06-03 19:09 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/responses/ProgramsResponseModel.kt
> +    private var programs: List<TrainerProgramModel> = listOf()
Related to [this](https://github.com/hyfn/trx-consumer-android/pull/101/files#r645058041)

2021-06-03 19:09 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/responses/TrainerResponseModel.kt
> +    var trainer: TrainerModel = TrainerModel()
Related to [this](https://github.com/hyfn/trx-consumer-android/pull/101/files#r645058041)

2021-06-03 19:12 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/banner/BannerView.kt
> +class BannerView @JvmOverloads constructor(
Do we need a separate `View` for this? Only seems to be used in adapters

2021-06-03 19:18 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/trainer/TrainerDetailFragment.kt
> +        viewModel.doLoadData()
Let's log the events

2021-06-03 19:26 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/trainer/TrainerDetailFragment.kt
> +        NavigationManager.shared.present(this, R.id.content_fragment, model)
Crashing here, the screen is expecting a `ContentParamsModel` instead of a `ContentModel`

2021-06-03 19:27 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/trainer/TrainerDetailFragment.kt
> +    override fun bind() {
Screen needs a hud

2021-06-03 19:29 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/trainer/TrainerDetailFragment.kt
> +            lblOndemand.isHidden = hide
Let's initialize the appropriate labels/lines/buttons as hidden in the xml so that we don't see them on entry

2021-06-03 19:49 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/trainer/TrainerDetailFragment.kt
> +                    requireContext().getString(
Can just call `context` here instead of `requireContext`

2021-06-03 19:53 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/trainer/TrainerDetailFragment.kt
> +                text = SpannableStringBuilder(trimmedText).append(
Not sure about this, looks like it's going to display the "read more" label even if the characters are below 180, which I'm guessing we don't want

2021-06-03 19:57 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/trainer/TrainerDetailViewModel.kt
> +                eventLoadOndemand.postValue(model.lstWorkoutsForTrainerProfileId(trainer.virtualTrainerProfileId))
Exceeds character limit

2021-06-03 20:00 UTC, VivekV95 requested changes
Looking pretty good overall, had some thoughts on the first pass

2021-06-03 21:59 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/banner/BannerView.kt
> +class BannerView @JvmOverloads constructor(
[was referring to iOS side](https://github.com/hyfn/trx-consumer-ios/blob/develop/TRX-Consumer/Screens/Banner/BannerView.swift)

2021-06-03 22:10 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/banner/BannerView.kt
> +class BannerView @JvmOverloads constructor(
Ah gotcha, yeah their `View`s when used in collections are equivalent to our `ViewHolder`s, can just do what we're doing with all other adapters here instead of creating a separate view for it. The only exception we have is `VirtualWorkoutView` and that's because we use it outside of adapters as well.

2021-06-03 22:15 UTC, onodude commented
@devender197 can we make sure the sections collapse when there is no data

2021-06-03 22:35 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/trainer/TrainerDetailFragment.kt
> +            lblOndemand.isHidden = hide
I think, we will apply Skelton here. Same thing is happening at home screen also. If we have plan to implement Skelton then we don't need it else we can go with recommendation.

2021-06-03 22:44 UTC, devender197 commented
> @devender197 can we make sure the sections collapse when there is no data

Yes I checked every section in case of no data.

2021-06-03 22:45 UTC, devender197 commented on app/src/main/java/com/trx/consumer/models/common/TrainerProgramModel.kt
> +
[Removed](https://github.com/hyfn/trx-consumer-android/pull/101/commits/acfde61789d447a4517cfba6247945c0c2253045)

2021-06-03 22:45 UTC, devender197 commented on app/src/main/java/com/trx/consumer/models/common/TrainerProgramModel.kt
> +    var durationInMinutes: Int = 0
[Done](https://github.com/hyfn/trx-consumer-android/pull/101/commits/acfde61789d447a4517cfba6247945c0c2253045#diff-8cf6457a5febb2b00a013c43a46ac903ba35f96a196cfd04194b48bab0e18d74R7)

2021-06-03 22:46 UTC, devender197 commented on app/src/main/java/com/trx/consumer/models/responses/ProgramsResponseModel.kt
> +    private var programs: List<TrainerProgramModel> = listOf()
[Done](https://github.com/hyfn/trx-consumer-android/pull/101/commits/acfde61789d447a4517cfba6247945c0c2253045#diff-974163dc14ec7b7c43490aa377b434f7566cad756451859792e81a834c7b52e6R7)

2021-06-03 22:46 UTC, devender197 commented on app/src/main/java/com/trx/consumer/models/responses/TrainerResponseModel.kt
> +    var trainer: TrainerModel = TrainerModel()
[Done](https://github.com/hyfn/trx-consumer-android/pull/101/commits/acfde61789d447a4517cfba6247945c0c2253045#diff-6897e87e328664f04e39c17e18c86849f3b7779fbea77c5771d4b9f8b8b2a3eaR6)

2021-06-03 22:47 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/trainer/TrainerDetailFragment.kt
> +        viewModel.doLoadData()
[Done](https://github.com/hyfn/trx-consumer-android/pull/101/commits/acfde61789d447a4517cfba6247945c0c2253045#diff-482717045563f6f95a7c7ce2d08e6d8918f53330599b236b423618806a4a0cbeR118)

2021-06-03 22:47 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/trainer/TrainerDetailFragment.kt
> +    override fun bind() {
[Done](https://github.com/hyfn/trx-consumer-android/pull/101/commits/acfde61789d447a4517cfba6247945c0c2253045#diff-7384718b3870cefafbfdd99a1d7a76cd747519a2edc81ad914249660e6d6a294R69)

2021-06-03 22:48 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/trainer/TrainerDetailFragment.kt
> +                    requireContext().getString(
[Done](https://github.com/hyfn/trx-consumer-android/pull/101/commits/acfde61789d447a4517cfba6247945c0c2253045#diff-482717045563f6f95a7c7ce2d08e6d8918f53330599b236b423618806a4a0cbeR241)

2021-06-03 22:49 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/trainer/TrainerDetailFragment.kt
> +                text = SpannableStringBuilder(trimmedText).append(
Yes your right...I missed it totally Changed [here](https://github.com/hyfn/trx-consumer-android/pull/101/commits/acfde61789d447a4517cfba6247945c0c2253045#diff-482717045563f6f95a7c7ce2d08e6d8918f53330599b236b423618806a4a0cbeR248)

2021-06-03 22:51 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/trainer/TrainerDetailViewModel.kt
> +                eventLoadOndemand.postValue(model.lstWorkoutsForTrainerProfileId(trainer.virtualTrainerProfileId))
[Done](https://github.com/hyfn/trx-consumer-android/pull/101/commits/acfde61789d447a4517cfba6247945c0c2253045#diff-7384718b3870cefafbfdd99a1d7a76cd747519a2edc81ad914249660e6d6a294R102)

2021-06-03 22:53 UTC, devender197 commented
@VivekV95 @onodude Thank you for you initial review. I was really helpful. Please resolve the comment so that we will have space of new comments and please let me know If any enhancement come up.

2021-06-04 04:37 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/banner/BannerView.kt
> +class BannerView @JvmOverloads constructor(
Let's remove this view and just handle the layout it directly in `BannerViewHolder`

2021-06-04 04:39 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/trainer/TrainerDetailFragment.kt
> +            lblOndemand.isHidden = hide
@onodude I think this is the collapsing behavior you were referring to (only on entry), makes sense to not worry about this if we're bringing in skeletons but don't know what the timeline on that will be. I'm fine with whatever approach we go with here

2021-06-04 05:00 UTC, VivekV95 requested changes
Thanks for the changes, left another comment and noticed one more thing: the cell here seems to be a bit too big compared to the figma design

[Figma](https://user-images.githubusercontent.com/39810816/120748051-be967700-c4c7-11eb-8ce9-e00f0f467a01.png)
[Screen](https://user-images.githubusercontent.com/39810816/120748052-bf2f0d80-c4c7-11eb-9c9e-9620cdbaac71.png)

2021-06-04 06:59 UTC, devender197 commented
> Thanks for the changes, left a couple comments and noticed one more thing: the cell here seems to be a bit too big compared to the figma design
> 
> [Figma](https://user-images.githubusercontent.com/39810816/120748051-be967700-c4c7-11eb-8ce9-e00f0f467a01.png)
> [Screen](https://user-images.githubusercontent.com/39810816/120748052-bf2f0d80-c4c7-11eb-9c9e-9620cdbaac71.png)

[Done](https://github.com/hyfn/trx-consumer-android/pull/101/commits/91b059cf749bc7f19d3bb3d2a7f962aa4bbd72cc#diff-523480fb667e0911750e69e67a50308dfd0994a967d1c6980cca0e0ec3c796e1R335)

2021-06-04 16:31 UTC, onodude commented on app/src/main/java/com/trx/consumer/screens/trainer/TrainerDetailFragment.kt
> +            lblOndemand.isHidden = hide
@devender197 @VivekV95 the collapsing is more necessary if we get empty list in the response

2021-06-04 16:33 UTC, onodude commented on app/src/main/java/com/trx/consumer/screens/banner/BannerView.kt
> +class BannerView @JvmOverloads constructor(
`BannerView` is equivalent to `BannerView`
`BannerViewHolder` is equivalent to `BannerCollectionViewCell`

2021-06-04 16:38 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/banner/BannerView.kt
> +class BannerView @JvmOverloads constructor(
@onodude Not sure about that, it seems more like Android's `BannerViewHolder` = iOS's `BannerView` + `BannerCollectionViewCell`, we don't create custom views for any other adapter items

2021-06-04 16:40 UTC, onodude commented on app/src/main/java/com/trx/consumer/screens/banner/BannerView.kt
> +class BannerView @JvmOverloads constructor(
this is our general pattern
```
row_banner -> view banner
row_banner_collection -> banner collection view cell
row_banner_table -> banner table view cell
```

2021-06-04 16:41 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/banner/BannerView.kt
> +class BannerView @JvmOverloads constructor(
Ex. Android doesn't have a `PhotoView` or `TrainerProgramView`, so not sure if we need a separate `BannerView`

2021-06-04 16:51 UTC, onodude commented on app/src/main/java/com/trx/consumer/screens/banner/BannerView.kt
> +class BannerView @JvmOverloads constructor(
it is there. also paired with iOS. please move on...

2021-06-04 16:54 UTC, onodude commented on app/src/main/java/com/trx/consumer/screens/banner/BannerView.kt
> +class BannerView @JvmOverloads constructor(
btw could not find PhotoView but the pattern is for rows and cells

2021-06-04 18:15 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/banner/BannerView.kt
> +class BannerView @JvmOverloads constructor(
Briefly discussed with @onodude, confirming that we're removing this file as we don't create `View`s for cells unless they're also being used outside cells.

2021-06-04 18:18 UTC, VivekV95 requested changes
Just the removing `BannerView` comment, the collapsing behavior when data is missing seemed to be working fine in my testing

2021-06-04 20:20 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/trainer/TrainerDetailFragment.kt
> +            lblOndemand.isHidden = hide
it is already done and hide the section before load is done [here](https://github.com/hyfn/trx-consumer-android/pull/101/commits/9a0ec80b7e51013dffaab3092355f90f94e3b3a0)

2021-06-04 20:21 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/banner/BannerView.kt
> +class BannerView @JvmOverloads constructor(
[Removed](https://github.com/hyfn/trx-consumer-android/pull/101/commits/9a0ec80b7e51013dffaab3092355f90f94e3b3a0#diff-1cf9ad3586d2948f6c09d93778f668be4d20a6f4564e9aee346c4ff7ffcadbccR10)

2021-06-04 20:35 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/TrainerProgramModel.kt
> +) {
Looking again, I think we'll need this to be parcelable as we're sending this model to `Schedule` [here](https://github.com/hyfn/trx-consumer-android/pull/101/files#diff-482717045563f6f95a7c7ce2d08e6d8918f53330599b236b423618806a4a0cbeR176). Will crash otherwise. We'll end up wrapping this in params once we connect `Schedule` but will still need to be parcelable regardless

2021-06-04 20:38 UTC, VivekV95 commented on app/src/main/res/layout/fragment_trainer_detail.xml
> +<com.trx.consumer.common.CommonView xmlns:android="http://schemas.android.com/apk/res/android"
Completely missed this file (didn't load as it was too large), there's a lot of optimization that can be done here as we have a bunch of re-usable layouts for the sections, but I'd be fine creating a followup for it

2021-06-04 20:39 UTC, VivekV95 requested changes
Couple things I missed (one that I think would be fine for a followup) and should be good to go from me

2021-06-04 20:40 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/TrainerProgramModel.kt
> +) {
If we want to handle this in the followup as well I'm for it

2021-06-04 21:04 UTC, VivekV95 approved these changes

2021-06-04 22:17 UTC, merged

2021-06-04 22:17 UTC, onodude commented on app/src/main/java/com/trx/consumer/models/common/TrainerProgramModel.kt
> +) {
https://hyfnla.atlassian.net/browse/TCM-506

2021-06-04 22:17 UTC, onodude commented on app/src/main/res/layout/fragment_trainer_detail.xml
> +<com.trx.consumer.common.CommonView xmlns:android="http://schemas.android.com/apk/res/android"
https://hyfnla.atlassian.net/browse/TCM-506