TCM-256 | LiveSwitch Integration
hyfn/trx-consumer-android pull request #103
Opened 2021-06-04 01:20 UTC by vespertineSiren

## Description

### Summary

[text here]

### Issue

[link here]

### Video/Screenshot

[link here]

2021-06-21 17:56 UTC, VivekV95 commented on app/build.gradle
> +//    configurations {
Can we delete the commented code?

2021-06-21 18:05 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/core/MainModule.kt
> +        LivePlayerHandler(context.applicationContext)
Can just pass the `context`; it's guaranteed to be the application context due to the annotation

2021-06-21 18:06 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/frozenmountain/AecContext.kt
> +}
Needs linting

2021-06-21 18:07 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/frozenmountain/LocalCameraMedia.kt
> +// class CameraLocalMedia(
Can this be deleted?

2021-06-21 18:09 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/EndpointModel.kt
> +                PLAN_DELETE -> {
Should be `MEMBERSHIP_DELETE`, I think this is what's causing the current build to fail

2021-06-21 18:10 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/ParticipantModel.kt
> +    var firstName: String = "",
Can be `val`s

2021-06-21 18:11 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/responses/LiveResponseModel.kt
> +    var accessToken: String = "",
Can be `val`s

2021-06-21 18:15 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
> +                model.video
We should be sending the model instead of just the video here right?

2021-06-21 18:16 UTC, VivekV95 commented on app/build.gradle
> +    implementation ("com.stripe:stripe-android:$rootProject.stripeVersion")
Don't need the parens

2021-06-21 18:18 UTC, VivekV95 requested changes
Few thoughts, some cleanup related

2021-06-23 00:29 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/frozenmountain/LocalCameraMedia.kt
> +// class CameraLocalMedia(
It can! It was just a bunch of experiment stuff.

2021-06-28 18:50 UTC, VivekV95 requested changes
Just the merge conflicts

2021-06-28 21:07 UTC, VivekV95 approved these changes

2021-06-28 22:43 UTC, merged