TCM-477 | For You section
hyfn/trx-consumer-android pull request #104
Opened 2021-06-04 06:17 UTC by vespertineSiren

## Description

### Summary

Add space if `For You` section is empty. 

### Issue

[TCM-477](https://hyfnla.atlassian.net/browse/TCM-477)

### Video/Screenshot

![Screenshot_1622787216](https://user-images.githubusercontent.com/27742105/120754609-bd624b80-c4c1-11eb-95b1-3027ee640a6a.png)

2021-06-04 19:10 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/home/HomeFragment.kt
> +        if (promos.isNotEmpty()) promoAdapter.update(promos)
Let's keep the `hide` so that we don't have to do an empty check twice, or we can rename `hide` to `isEmpty` or something if that makes more sense

2021-06-04 19:16 UTC, VivekV95 requested changes
Just one comment, also a bit confused. I might be misinterpreting but it sounds like the ticket is stating that we _dont_ want empty space when there are no promos whereas the implementation is ensuring there's empty space

2021-06-04 20:00 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/home/HomeFragment.kt
> +        if (promos.isNotEmpty()) promoAdapter.update(promos)
> Just one comment, also a bit confused. I might be misinterpreting but it sounds like the ticket is stating that we _dont_ want empty space when there are no promos whereas the implementation is ensuring there's empty space

If we remove the min height for viewMain in the layout_promo_section then we should be able to just hide completely.

2021-06-04 21:37 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/home/HomeFragment.kt
> +        if (promos.isNotEmpty()) promoAdapter.update(promos)
^ Works for me

2021-06-08 18:44 UTC, VivekV95 commented
Looks like there's bottom padding in the root view which causes empty space at the bottom no matter what scroll position we're in. I'm guessing we only want that space once we've scrolled to the bottom. 

![Screen Shot 2021-06-08 at 1 41 59 PM](https://user-images.githubusercontent.com/39810816/121240047-8d1f0200-c85f-11eb-97dd-92c56065a479.png)

2021-06-11 16:24 UTC, VivekV95 approved these changes

2021-06-11 18:57 UTC, onodude approved these changes
thanks!

2021-06-11 18:57 UTC, merged