Feature/#490 improve videos screen
hyfn/trx-consumer-android pull request #109
Opened 2021-06-07 23:22 UTC by vespertineSiren

## Description

### Summary

- Remove button to start workout, no related workouts label. 

### Issue

[TCM-490](https://hyfnla.atlassian.net/browse/TCM-490)

### Video/Screenshot

https://user-images.githubusercontent.com/27742105/121099272-6653c380-c7ac-11eb-875c-85611c7a37eb.mov

| | |
|----|----|
|![Screenshot_1623107467](https://user-images.githubusercontent.com/27742105/121099290-6ce23b00-c7ac-11eb-9a8b-fa318ccbd107.png)|![Screenshot_1623107478](https://user-images.githubusercontent.com/27742105/121099300-72d81c00-c7ac-11eb-84cd-e1dd93778d25.png)|

2021-06-08 18:56 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/videos/VideosFragment.kt
> +            btnBack.action { viewModel.doTapBack() }
I think we can connect tapping trainer profile now

2021-06-08 18:59 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/videos/VideosFragment.kt
> +        }
It looks like some programs/collections have descriptions and some don't, but we're always just displaying the description of the first video. Now that we can't play the first video here, feels like it would be better to check if `VideosModel` has a description and use that if available, and use the first video's description if not.

2021-06-08 19:01 UTC, VivekV95 requested changes
Just a couple things

2021-06-08 19:05 UTC, devender197 commented
@VivekV95 Agreed with you suggestions. But they seems little out of scope of this task. If we are considering to do these improvement in this task. Can we please consider added a limit with Read more if description is longer that threshold value.

2021-06-10 00:56 UTC, VivekV95 commented
> @VivekV95 Agreed with you suggestions. But they seems little out of scope of this task. If we are considering to do these improvement in this task. Can we please consider added a limit with Read more if description is longer than a threshold value?

Our "Improve" tasks are open ended on purpose so we can knock out miscellaneous requirements, so I think the additional changes would be in scope, but if we want to create a separate task regardless, totally fine by me.

2021-06-10 23:30 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/videos/VideosFragment.kt
> +        }
Here we go: https://github.com/hyfn/trx-consumer-android/pull/109/commits/31fbcbfe1a0b34aae0ae9cde07907b0b65ed3cc5

2021-06-10 23:30 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/videos/VideosFragment.kt
> +            btnBack.action { viewModel.doTapBack() }
profile tap: https://github.com/hyfn/trx-consumer-android/pull/109/commits/ffed789ae7ceee11d5c0dcd3a52673b1641bbe15

2021-06-11 16:18 UTC, VivekV95 approved these changes

2021-06-11 16:36 UTC, devender197 commented
> @VivekV95 Agreed with you suggestions. But they seems little out of scope of this task. If we are considering to do these improvement in this task. Can we please consider added a limit with Read more if description is longer than a threshold value?

@vespertineSiren @onodude @VivekV95 So are we handling this `"Read more if description is longer than a threshold value"` request in current PR or  it is out of scope?

2021-06-11 16:37 UTC, devender197 commented
A Question asked

2021-06-11 18:59 UTC, onodude approved these changes
thanks! lets create a new task for followups @vespertineSiren @VivekV95

2021-06-11 18:59 UTC, merged