TCM-492 |  Add equipments section
hyfn/trx-consumer-android pull request #111
Opened 2021-06-08 02:39 UTC by devender197

## Description

### Summary

- [ ] Equipment Section added to workout screen

### Issue

[TCM-492](https://hyfnla.atlassian.net/browse/TCM-492)

### Video

https://user-images.githubusercontent.com/24737954/121114109-ff440800-c7c7-11eb-8f48-e0694eba8261.mov

###Screenshot

![Screenshot_1623119882](https://user-images.githubusercontent.com/24737954/121114054-eb000b00-c7c7-11eb-8a32-5da10d298a19.png)

2021-06-08 02:40 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
> +    private fun listToString(list: List<String>): String {
@onodude need suggestion on this function name and possibility as extension exit or not?

2021-06-08 19:20 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
> +    private fun listToString(list: List<String>): String {
Couple things: 
- Needs an empty check or we'll crash
- Don't want to prepend "and" if it's just one item

Working well in other cases

2021-06-08 19:24 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
> +    private fun listToString(list: List<String>): String {
Also do we want an oxford comma or not? Currently we're not using one

2021-06-08 19:27 UTC, VivekV95 requested changes
Just a couple things

2021-06-08 20:01 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
> +    private fun listToString(list: List<String>): String {
[Done](https://github.com/hyfn/trx-consumer-android/pull/111/commits/458707ce45eb3979489509c914b58cc6b4f1abe6)

2021-06-08 22:20 UTC, onodude requested changes
@devender197 @VivekV95 would it be possible to mimic the changes on iOS with respect to the logic: https://github.com/hyfn/trx-consumer-ios/pull/194

@onodude Made similar to iOS @onodude [Done](https://github.com/hyfn/trx-consumer-android/pull/111/commits/2868fb736f3849604ec58b7d12a315815d16a122)

2021-06-09 16:26 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
> +    private fun listToString(list: List<String>): String {
[This](https://github.com/hyfn/trx-consumer-android/pull/111#pullrequestreview-679054052) should be possible here with same pattern, we have a `capitalized` extension we can use and I think we should be able to just call `joinToString` with a "," separator and inline everything like iOS is doing (if we don't care about adding an "and" at the end)

2021-06-09 16:26 UTC, VivekV95 requested changes
Addressing @onodude 's request

2021-06-09 17:32 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
> +    private fun listToString(list: List<String>): String {
> @devender197 @VivekV95 would it be possible to mimic the changes on iOS with respect to the logic: [hyfn/trx-consumer-ios#194](https://github.com/hyfn/trx-consumer-ios/pull/194)

@onodude Made similar to iOS @onodude [Done](https://github.com/hyfn/trx-consumer-android/pull/111/commits/2868fb736f3849604ec58b7d12a315815d16a122)

2021-06-09 17:34 UTC, devender197 commented
> @devender197 @VivekV95 would it be possible to mimic the changes on iOS with respect to the logic: [hyfn/trx-consumer-ios#194](https://github.com/hyfn/trx-consumer-ios/pull/194)


@onodude Made similar to iOS @onodude [Done](https://github.com/hyfn/trx-consumer-android/pull/111/commits/2868fb736f3849604ec58b7d12a315815d16a122)

2021-06-09 17:34 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
> +    private fun listToString(list: List<String>): String {
addressed [here](https://github.com/hyfn/trx-consumer-android/pull/111#issuecomment-857895530)

2021-06-09 17:45 UTC, devender197 commented
@onodude only difference we have with iOS is that iOS don't have line below equipment section and android have it. do we need remove it on android also?

2021-06-10 00:52 UTC, onodude approved these changes
thanks!

2021-06-10 00:52 UTC, merged