TCM-541 | Build Dummy Private Player Screen
hyfn/trx-consumer-android pull request #120
Opened 2021-06-17 21:03 UTC by devender197

## Description

### Summary

[] Private player dummy screen created

### Issue

[TCM-541](https://hyfnla.atlassian.net/browse/TCM-541)

### Video/Screenshot

[link here]

2021-06-21 16:33 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/common/CommonCheckBox.kt
> +    constructor(context: Context) : super(context)
Let's just use primary constructor and use `@JvmOverloads`, will handle this code for us

2021-06-21 16:35 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/core/MainActivity.kt
>          start()
Let's revert removing the empty line

2021-06-21 16:38 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/extensions/ViewExtensions.kt
> +inline fun View.onChecked(crossinline action: (isChecked: Boolean) -> Unit) {
Any reason why this can't be a `CommonCheckBox` extension? Think we'll only be using this with that class

2021-06-21 16:39 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/extensions/ViewExtensions.kt
> +inline fun View.onChecked(crossinline action: (isChecked: Boolean) -> Unit) {
Can maybe even just have this as a regular function within `CommonCheckBox`

2021-06-21 16:43 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/common/CommonCheckBox.kt
> +class CommonCheckBox : AppCompatCheckBox {
I think I like the other naming suggestion of `CommonStateButton` that was mentioned better here, we'll be using this much more frequently as a "button" than a "checkbox" specifically

2021-06-21 16:45 UTC, VivekV95 commented on app/src/main/res/layout-land/activity_group_player.xml
> +        <CheckBox
`CommonCheckBox` or whatever we end up calling it here and with the other checkboxes

2021-06-21 16:46 UTC, VivekV95 commented on app/src/main/res/layout-land/activity_private_player.xml
> +        <CheckBox
Related to [this](https://github.com/hyfn/trx-consumer-android/pull/120/files#r655546571)

2021-06-21 16:47 UTC, VivekV95 commented on app/src/main/res/layout-land/activity_group_player.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
`CommonView` here and in the other layouts

2021-06-21 16:49 UTC, VivekV95 commented on app/src/main/res/menu/menu_group_player.xml
> +<menu xmlns:android="http://schemas.android.com/apk/res/android">
Are we using this?

2021-06-21 16:49 UTC, VivekV95 commented on app/src/main/res/navigation/nav_main.xml
> +
Extra empty line

2021-06-21 16:52 UTC, VivekV95 requested changes
Few thoughts on the first run through, also can we target the group player branch with this so that the changes are easier to see? Don't want to write duplicate comments

2021-06-21 21:03 UTC, devender197 commented on app/src/main/java/com/trx/consumer/common/CommonCheckBox.kt
> +class CommonCheckBox : AppCompatCheckBox {
@onodude  Please let me know the name which make more sense.

2021-06-21 22:35 UTC, devender197 commented on app/src/main/java/com/trx/consumer/core/MainActivity.kt
>          start()
[Reverted](https://github.com/hyfn/trx-consumer-android/pull/120/commits/4dec6215d7a3385f6e8fe524f6b354e872f5f5b0)

2021-06-21 22:35 UTC, devender197 commented on app/src/main/java/com/trx/consumer/extensions/ViewExtensions.kt
> +inline fun View.onChecked(crossinline action: (isChecked: Boolean) -> Unit) {
[Done](https://github.com/hyfn/trx-consumer-android/pull/120/files#diff-f910762ca34f2d958765ceb45cc4d7c36937d7ee1f123c736b6e12761cb5a471R13)

2021-06-21 22:36 UTC, devender197 commented on app/src/main/res/layout-land/activity_group_player.xml
> +        <CheckBox
[Done](https://github.com/hyfn/trx-consumer-android/pull/120/files#diff-c9dc2b769bde4a4f97f4932c840837e41290f764a36631a4a50e79fd38dbe938R21)

2021-06-21 22:36 UTC, devender197 commented on app/src/main/res/layout-land/activity_private_player.xml
> +        <CheckBox
[Done](https://github.com/hyfn/trx-consumer-android/pull/120/files#diff-c9dc2b769bde4a4f97f4932c840837e41290f764a36631a4a50e79fd38dbe938R21)

2021-06-21 22:37 UTC, devender197 commented on app/src/main/res/layout-land/activity_group_player.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
[Done](https://github.com/hyfn/trx-consumer-android/pull/120/files#diff-c9dc2b769bde4a4f97f4932c840837e41290f764a36631a4a50e79fd38dbe938R9)

2021-06-21 22:37 UTC, devender197 commented on app/src/main/res/menu/menu_group_player.xml
> +<menu xmlns:android="http://schemas.android.com/apk/res/android">
Removed

2021-06-21 22:37 UTC, devender197 commented on app/src/main/res/navigation/nav_main.xml
> +
Removed

2021-06-21 22:39 UTC, devender197 commented
> Few thoughts on the first run through, also can we target the group player branch with this so that the changes are easier to see? Don't want to write duplicate comments

Thank you. Done Changes for group player also. Please let me know more changes required

2021-06-22 23:16 UTC, VivekV95 commented on app/src/main/res/layout-land/activity_group_player.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
Root views are still `ConstraintLayout`s instead of `CommonView`s, but would be okay with handling in followup

2021-06-22 23:16 UTC, VivekV95 commented on app/src/main/res/layout-land/activity_private_player.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
Related to [this](https://github.com/hyfn/trx-consumer-android/pull/120/files#r656643572)

2021-06-22 23:22 UTC, VivekV95 approved these changes
@onodude @devender197 Thanks for the changes, would be okay with handling the new state button and the other couple minor comments in a followup if you guys would like to.

2021-06-22 23:28 UTC, onodude commented
here is the one for the button: https://hyfnla.atlassian.net/browse/TCM-621

2021-06-22 23:28 UTC, onodude approved these changes
thank you!

2021-06-22 23:28 UTC, merged