TCM-442 | Setup firebase remote config connection
hyfn/trx-consumer-android pull request #121
Opened 2021-06-18 01:01 UTC by devender197

## Description

### Summary

- [ ] Setup the firebase remote config connection

### Issue

[TCM-442](https://hyfnla.atlassian.net/browse/TCM-442)

### Video/Screenshot

#### Firebase parameter added

![Screen Shot 2021-06-17 at 6 00 42 PM](https://user-images.githubusercontent.com/24737954/122490074-f5738f00-cf95-11eb-8903-85b831d0e1c5.png)

2021-06-18 16:06 UTC, onodude approved these changes
thanks!

2021-06-21 16:31 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/core/MainModule.kt
> +    fun provideConfigManager(cacheManager: CacheManager): ConfigManager = ConfigManager(cacheManager)
Exceeds character limit

2021-06-21 16:31 UTC, VivekV95 requested changes
Just one minor formatting issue

2021-06-21 18:38 UTC, onodude commented on app/src/main/java/com/trx/consumer/core/MainModule.kt
> +    fun provideConfigManager(cacheManager: CacheManager): ConfigManager = ConfigManager(cacheManager)
should we add a return statement?

2021-06-21 18:58 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/core/MainModule.kt
> +    fun provideConfigManager(cacheManager: CacheManager): ConfigManager = ConfigManager(cacheManager)
Stylistically I prefer using `return` statements but looks like the pattern in the file seems to be just using `=`

2021-06-21 22:41 UTC, devender197 commented on app/src/main/java/com/trx/consumer/core/MainModule.kt
> +    fun provideConfigManager(cacheManager: CacheManager): ConfigManager = ConfigManager(cacheManager)
[Done](https://github.com/hyfn/trx-consumer-android/pull/121/commits/cf957b858f06569c9f92f87541c565fd216924f2)

2021-06-22 00:14 UTC, onodude approved these changes
thanks!

2021-06-22 00:14 UTC, VivekV95 approved these changes

2021-06-22 00:17 UTC, merged