TCM-530 | On Demand Player updates
hyfn/trx-consumer-android pull request #123
Opened 2021-06-18 23:26 UTC by devender197

## Description

### Summary

- [ ] Deleted the unused asset
- [ ] VideoActivity.kt name refactor to VideoPlayer.kt

### Issue

[TCM-530](https://hyfnla.atlassian.net/browse/TCM-530)

### Video/Screenshot

2021-06-19 00:10 UTC, onodude requested changes
so video activity should be `VideoPlayerActivity`

2021-06-19 00:44 UTC, devender197 commented
> so video activity should be `VideoPlayerActivity`

[Done](https://github.com/hyfn/trx-consumer-android/pull/123/commits/a535f51294b1007c8ec28b514c7b34c1d3d21d05)

2021-06-19 01:02 UTC, onodude submitted a review, later dismissed
thanks!

2021-06-21 16:58 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/video/VideoPlayerActivity.kt
> +class VideoPlayerActivity : BrightcovePlayer() {
Let's rename the layout file name as well to match

2021-06-21 16:59 UTC, VivekV95 requested changes
One more naming change

2021-06-21 22:54 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/video/VideoPlayerActivity.kt
> +class VideoPlayerActivity : BrightcovePlayer() {
[Done](https://github.com/hyfn/trx-consumer-android/pull/123/commits/67949b02819083d0bf0e1c71675017ce10cdcc33#diff-b951aad0aee5eec1b805bbf5fa9d7eef32758105002df16c115e6a44ce8298bbR48)

2021-06-22 00:14 UTC, onodude approved these changes
thanks!

2021-06-22 00:14 UTC, VivekV95 approved these changes

2021-06-22 00:15 UTC, merged