TCM-558 : Live Player Code Cleanup
hyfn/trx-consumer-android pull request #126
Opened 2021-06-21 17:10 UTC by vespertineSiren

## Description

### Summary

- Code improvements to match architecture. 

### Issue

[TCM-558](https://hyfnla.atlassian.net/browse/TCM-558

### Video/Screenshot

N/A

2021-06-28 18:34 UTC, VivekV95 approved these changes

2021-06-28 18:50 UTC, VivekV95 requested changes
Just the merge conflicts

2021-06-28 21:08 UTC, VivekV95 submitted a review, later dismissed

2021-06-30 19:00 UTC, VivekV95 approved these changes

2021-06-30 19:09 UTC, onodude approved these changes
thank you!

2021-06-30 19:09 UTC, merged