TCM-600 | Promos on Homepage
hyfn/trx-consumer-android pull request #129
Opened 2021-06-22 20:34 UTC by devender197

## Description

### Summary

- [ ] Promo added to home screen

### Issue

[TCM-600](https://hyfnla.atlassian.net/browse/TCM-600)

### Video/Screenshot

Uploading Screen Recording 2021-06-22 at 1.30.11 PM.mov…

2021-06-22 23:09 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/managers/BackendManager.kt
> +        val params = cacheManager.accessToken()?.let { hashMapOf<String, Any>("jwt" to it) }
Not sure this is needed, should just be able to add `PROMOS` to `isAuthenticated` in `EndpointModel`

2021-06-22 23:10 UTC, VivekV95 requested changes
Just one comment

2021-06-22 23:39 UTC, devender197 commented on app/src/main/java/com/trx/consumer/managers/BackendManager.kt
> +        val params = cacheManager.accessToken()?.let { hashMapOf<String, Any>("jwt" to it) }
[Done](https://github.com/hyfn/trx-consumer-android/pull/129/commits/c1069a43a00277a7aa6dfe754b918daac64eefde#diff-96bdf8cd544df52ea2927bf8f74da8305c760cbb64aa464ce0438f526ac2e61cR74)

2021-06-23 17:08 UTC, onodude commented on app/src/main/java/com/trx/consumer/models/common/EndpointModel.kt
> +                AUTH,PROMOS,
lets add after `PAYMENT_ADD` to keep the order

2021-06-23 17:13 UTC, devender197 commented on app/src/main/java/com/trx/consumer/models/common/EndpointModel.kt
> +                AUTH,PROMOS,
[Done](https://github.com/hyfn/trx-consumer-android/pull/129/files#diff-96bdf8cd544df52ea2927bf8f74da8305c760cbb64aa464ce0438f526ac2e61cR83)

2021-06-23 17:18 UTC, onodude approved these changes
thanks!

2021-06-23 17:29 UTC, merged