TCM-347 | Connect backend to Schedule screen: live, trainer live, user live
hyfn/trx-consumer-android pull request #130
Opened 2021-06-22 21:21 UTC by devender197

## Description

### Summary

- [ ] Connected with backend for live, trainer live and user live

### Issue

[TCM-347](https://hyfnla.atlassian.net/browse/TCM-347)

### Video/Screenshot

#### Trainer Live

https://user-images.githubusercontent.com/24737954/123000975-173d8f00-d365-11eb-9ed5-c3df9b5900d7.mov

#### Live

https://user-images.githubusercontent.com/24737954/123001015-1f95ca00-d365-11eb-83f7-c5605971c4ae.mov

2021-06-28 21:05 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/schedule/ScheduleViewModel.kt
> +        doTapDate(Date().dateAtHour(24))
Think we should just be passing `date` here unless I'm missing something

2021-06-28 21:06 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/schedule/ScheduleFragment.kt
> +    private val handleLoadCalendarView = Observer<CalendarModel> { item -> }
Anything blocking us from updating the calendar here?

2021-06-28 21:07 UTC, VivekV95 requested changes
Couple comments and merge conflicts

2021-07-08 23:11 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/ScheduleModel.kt
> +    val trainerProgram: TrainerProgramModel? = null
Are we able to give this default values (state, blank string, test object) so theres no need to do a null check?

2021-07-08 23:26 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/schedule/ScheduleFragment.kt
> +            eventLoadLiveWorkouts.observe(viewLifecycleOwner, handleLoadLiveWorkout)
Shouldn't these `Load` events be typically before all `Tap` events?

2021-07-08 23:27 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/schedule/ScheduleFragment.kt
> +
Just add a `LogManager` call or something here instead of being an empty function body?

2021-07-08 23:38 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/schedule/ScheduleViewModel.kt
> +        doTapDate(Date().dateAtHour(24))
This function looks a little odd to me. It doesn't seem to need a default parameter since it only seems to be using `Date()`

2021-07-08 23:45 UTC, vespertineSiren requested changes
Just a few nitpicks, nothing major. 
On your demo, are you able to click on the dates of the calendar?

2021-07-12 19:02 UTC, devender197 commented on app/src/main/java/com/trx/consumer/models/common/ScheduleModel.kt
> +    val trainerProgram: TrainerProgramModel? = null
[Done](https://github.com/hyfn/trx-consumer-android/pull/130/commits/d26b46a065b097014524a66929565ffecd9512c8#diff-f40333e4fe317b6aafc5f5ff53c1d7a4cc4ab96ec69e07e75dc85647e2eddb4bR11)

2021-07-12 19:02 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/schedule/ScheduleFragment.kt
> +            eventLoadLiveWorkouts.observe(viewLifecycleOwner, handleLoadLiveWorkout)
[Moved](https://github.com/hyfn/trx-consumer-android/pull/130/commits/d26b46a065b097014524a66929565ffecd9512c8#diff-a730c87cf71a810de6a61d53b0e24801a06637fc82c238a1a76a2f5100a1db39R33)

2021-07-12 19:03 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/schedule/ScheduleFragment.kt
> +
[Done](https://github.com/hyfn/trx-consumer-android/pull/130/commits/d26b46a065b097014524a66929565ffecd9512c8#diff-a730c87cf71a810de6a61d53b0e24801a06637fc82c238a1a76a2f5100a1db39R47)

2021-07-12 19:03 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/schedule/ScheduleViewModel.kt
> +        doTapDate(Date().dateAtHour(24))
[Done](https://github.com/hyfn/trx-consumer-android/pull/130/commits/d26b46a065b097014524a66929565ffecd9512c8#diff-73f05d5e1094f20b3178545334ef504ec2dbf94cc830de138667782ba251d8e5R91)

2021-07-12 19:04 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/schedule/ScheduleViewModel.kt
> +        doTapDate(Date().dateAtHour(24))
[Done](https://github.com/hyfn/trx-consumer-android/pull/130/commits/d26b46a065b097014524a66929565ffecd9512c8#diff-73f05d5e1094f20b3178545334ef504ec2dbf94cc830de138667782ba251d8e5R100)

2021-07-12 19:05 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/schedule/ScheduleFragment.kt
> +    private val handleLoadCalendarView = Observer<CalendarModel> { item -> }
Task is only related to connecting backend. So @onodude Please let me know, if i need to do it here or in separate task.

2021-07-12 19:07 UTC, devender197 commented
@VivekV95 @vespertineSiren Thank you for review. Please let me know if further enhancements are required.

2021-07-12 21:15 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/ScheduleModel.kt
> +    val trainerProgram: TrainerProgramModel? = null
The `key` is still `null`.

2021-07-12 21:23 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/schedule/ScheduleViewModel.kt
> +        doTapDate(Date().dateAtHour(24))
The function, `loadLive()` is only being used at lines 74 and 85 and only being given `Date()`, can't we just use the date parameter and use it like `doTapDate(date)` in line 100? [Reference](https://github.com/hyfn/trx-consumer-android/blob/d26b46a065b097014524a66929565ffecd9512c8/app/src/main/java/com/trx/consumer/screens/schedule/ScheduleViewModel.kt)

2021-07-12 21:23 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/schedule/ScheduleFragment.kt
> +
Thanks!

2021-07-12 21:26 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/schedule/ScheduleFragment.kt
> +            eventLoadLiveWorkouts.observe(viewLifecycleOwner, handleLoadLiveWorkout)
I believe theres a misunderstanding here. 

I meant the change to be something like below. Not moving the whole `viewModel.apply` block. 

```
      viewModel.apply {
            state = model.state
            key = model.key
            eventLoadView.observe(viewLifecycleOwner, handleLoadView)
            eventLoadCalendarView.observe(viewLifecycleOwner, handleLoadCalendarView)
            eventLoadLiveWorkouts.observe(viewLifecycleOwner, handleLoadLiveWorkout)
            eventTapBack.observe(viewLifecycleOwner, handleTapBack)

            doLoadView()
        }
```

2021-07-12 21:27 UTC, vespertineSiren requested changes
Added more clarifying comments on my end.

2021-07-13 00:53 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/schedule/ScheduleViewModel.kt
> +        doTapDate(Date().dateAtHour(24))
[Done](https://github.com/hyfn/trx-consumer-android/pull/130/commits/504148ae27d2ce9b2d4266b9746f8a91eb5377e6#diff-73f05d5e1094f20b3178545334ef504ec2dbf94cc830de138667782ba251d8e5R108)

2021-07-13 00:54 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/schedule/ScheduleFragment.kt
> +            eventLoadLiveWorkouts.observe(viewLifecycleOwner, handleLoadLiveWorkout)
[Done](https://github.com/hyfn/trx-consumer-android/pull/130/commits/504148ae27d2ce9b2d4266b9746f8a91eb5377e6#diff-a730c87cf71a810de6a61d53b0e24801a06637fc82c238a1a76a2f5100a1db39R39)

2021-07-13 00:56 UTC, devender197 commented on app/src/main/java/com/trx/consumer/models/common/ScheduleModel.kt
> +    val trainerProgram: TrainerProgramModel? = null
Either we have option to null check or check key is empty. I preferred to place null check.

2021-07-13 18:34 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/ScheduleModel.kt
> +    val trainerProgram: TrainerProgramModel? = null
Alright fine by me unless anyone else wants to chime in.

2021-07-13 18:39 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/schedule/ScheduleFragment.kt
> +            eventLoadLiveWorkouts.observe(viewLifecycleOwner, handleLoadLiveWorkout)
I dont believe these changes were commited then pushed.  I still see the viewbindings below the viewmodel.apply block and the ordering of the events seems off. Anyways, not a big issue. 
<img width="909" alt="Screen Shot 2021-07-13 at 11 37 30 AM" src="https://user-images.githubusercontent.com/27742105/125507094-9c7e79ff-91c9-4aae-aa6e-5ccfbbf171f8.png">

2021-07-13 18:39 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/schedule/ScheduleViewModel.kt
> +        doTapDate(Date().dateAtHour(24))
Thanks!

2021-07-13 18:40 UTC, vespertineSiren approved these changes
Looks fine. Just small nitpicks but heres an approval for now.

2021-07-14 00:44 UTC, onodude approved these changes
thank you!

2021-07-14 00:45 UTC, merged