TCM-621 | Create CommonStateButton
hyfn/trx-consumer-android pull request #134
Opened 2021-06-23 01:08 UTC by devender197

## Description

### Summary

- [ ] Shapable added
- [ ] CommonCheckBox.kt name changed to CommonStateButton.kt

### Issue

[TCM-621](https://hyfnla.atlassian.net/browse/TCM-621)

### Video/Screenshot

https://user-images.githubusercontent.com/24737954/123019178-d35a8200-d384-11eb-8446-0fbfebd33ef6.mov

2021-06-28 16:35 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/common/CommonStateButton.kt
> +@RequiresApi(Build.VERSION_CODES.M)
This may be an issue, our current minimum api is 21 and the app on the store is 22. We'd have to raise our minimum api to 23 to use `buttonDrawable`, need to investigate how many users we'd affect.

2021-06-28 16:38 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/common/CommonStateButton.kt
> +    private var defaultStateDrawable: Drawable? = null
We don't need to support default state, that's what `CommonImageView` is for.

2021-06-28 16:40 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/common/CommonStateButton.kt
> +    fun image(drawable: Int, state: Int?) {
Related to [this](https://github.com/hyfn/trx-consumer-android/pull/134/files#r659945101)

2021-06-28 18:06 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/common/CommonStateButton.kt
> +    companion object {
Not sure we need the stats, can just use a boolean

2021-06-28 18:09 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/common/CommonStateButton.kt
> +        buttonDrawable = null
Is this needed?

2021-06-28 18:12 UTC, VivekV95 requested changes
Looking pretty good overall with the `buttonDrawable` approach, but have to investigate whether we'll be able to raise our API level to 23 or not. Will wait for @onodude's thoughts.

It is not required now. Only related issue with api level is resolved.

2021-06-28 18:30 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/common/CommonStateButton.kt
> +    private var checkedStateDrawable: Drawable? = null
Think we can just make these public, would be nice to have the ability to set the drawables programatically without toggling checked state

2021-06-28 18:31 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/common/CommonStateButton.kt
> +@RequiresApi(Build.VERSION_CODES.M)
Not a major issue as @devender197 stated it's only needed for the getter

2021-06-28 20:21 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/common/CommonStateButton.kt
> +    private fun setButtonDrawable() {
At the moment, setting a default drawable through `image` (not passing in state) won't work as we're checking for existence of plain/active drawables as source of truth here. If we're supporting a default drawable, we probably want to introduce a third state for it, store state in the view, and use state as source of truth. Checked state + default state need to be able to co-exist. From what I understand, setting a default drawable means view is no longer checkable.

2021-06-28 20:40 UTC, devender197 commented on app/src/main/java/com/trx/consumer/common/CommonStateButton.kt
> +    private fun setButtonDrawable() {
I think we just need to pass null as state. or we can improve it by setting state= null as default value. In both case, it will work. 

`btnCamera.image(R.drawable.ic_btn_back_white, null)`

2021-06-28 22:26 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/common/CommonStateButton.kt
> +    private fun setButtonDrawable() {
It won't work, just tested it out and confirmed. 
![Screen Shot 2021-06-28 at 4 14 50 PM](https://user-images.githubusercontent.com/39810816/123705003-f7f2a600-d82b-11eb-83c6-57c953534f9e.png)
The default drawable will never be set to one of the other ones because the state isn't passed in. There's also the issue of the check listener being triggered when we're using a default drawable, which would cause issues when we're disabling a button for example. With this approach we'd want to do something like this:
![Screen Shot 2021-06-28 at 5 19 10 PM](https://user-images.githubusercontent.com/39810816/123710804-f5487e80-d834-11eb-99a9-76a6b2f79f7d.png)
![Screen Shot 2021-06-28 at 5 19 24 PM](https://user-images.githubusercontent.com/39810816/123710818-fe395000-d834-11eb-858c-9c13fa585c9e.png)

2021-06-28 23:49 UTC, devender197 commented on app/src/main/java/com/trx/consumer/common/CommonStateButton.kt
> +    private fun setButtonDrawable() {
[Done](https://github.com/hyfn/trx-consumer-android/pull/134/commits/a593a5a39c7c93f27bd30418364b0e56b362b9a9)

2021-06-29 05:36 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/common/CommonStateButton.kt
> +        state?.let {
One last thing, I still think we should enable and disable the states by using `isEnabled` depending on whether a state is set. If we're using the default state, this no longer should behave like a state button and the check changed listener should not be triggered.

2021-06-30 01:33 UTC, VivekV95 approved these changes

2021-06-30 18:32 UTC, onodude approved these changes
thank you @devender197 🚀

2021-06-30 18:32 UTC, merged