TCM-568 | Add FM containers/classes to Group/Private Player
hyfn/trx-consumer-android pull request #145
Opened 2021-06-24 22:28 UTC by vespertineSiren

## Description

### Summary

[text here]

### Issue

[link here]

### Video/Screenshot

[link here]

2021-06-29 18:49 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/privateplayer/PrivatePlayerActivity.kt
> +        localMediaStarted = true
Please can we consider setting `localMediaStarted = true` when all the permission are approved. Else it will be set to `true` in every condition. In same context line line 172 `localMediaStarted = false` should not be done in case of fail. 

and line 159 and 164 null check is not required.

2021-06-29 19:25 UTC, devender197 commented on app/src/main/res/layout/activity_group_player.xml
> +            android:id="@+id/btnCast"
Any reason to button name refactor.

2021-06-29 20:24 UTC, devender197 reviewed
few comments

2021-06-29 20:24 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/privateplayer/PrivatePlayerHandler.kt
> +    private var receiveOnly: Boolean = false
Can you please check where we are setting the value of `receiveOnly` variable. we are not setting its value to `true` anywhere I guess.

2021-06-29 20:28 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/privateplayer/PrivatePlayerHandler.kt
> +                            it.videoSource.start()
we need a null check on video source as it.videoSource can produce null in case videoSource in not present.

2021-06-29 20:35 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/privateplayer/PrivatePlayerHandler.kt
> +    private var receiveOnly: Boolean = false
On the demo Chat app, changing it was associated with a checkbox. Image attached. Kept this on the offchance we need to access it later. We are not setting it for now. 
<img width="388" alt="Screen Shot 2021-06-29 at 1 33 44 PM" src="https://user-images.githubusercontent.com/27742105/123863745-d1417780-d8de-11eb-9b43-6c53b6c84ef3.png">

2021-06-29 20:36 UTC, vespertineSiren commented on app/src/main/res/layout/activity_group_player.xml
> +            android:id="@+id/btnCast"
[Matching iOS view naming](https://github.com/hyfn/trx-consumer-ios/blob/develop/TRX-Consumer/Screens/GroupPlayer/GroupPlayerView.swift)

2021-06-29 20:49 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/privateplayer/PrivatePlayerHandler.kt
> +                            promise.reject(e)
we are changing video source input at line 156, can we do it at line 163? , where it is clear that the local media started with any error.

2021-06-29 21:03 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/privateplayer/PrivatePlayerActivity.kt
> +                if (checkLivePermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)) {
Line 121 and line 124 we can ask for user permission in bind method. Camera and audio permission can be ask when user taps here.

2021-06-30 19:18 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/privateplayer/PrivatePlayerActivity.kt
> +                if (checkLivePermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)) {
I believe these permissions can be left along for now until @VivekV95 brings in the Permissions screen.

2021-06-30 19:19 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/privateplayer/PrivatePlayerHandler.kt
> +                            it.videoSource.start()
Good catch. Will put this change in and ping here with commit.

2021-06-30 19:20 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/privateplayer/PrivatePlayerHandler.kt
> +                            promise.reject(e)
I missed adding a TODO there but I wanted them in two separate places to show a distinction if we ever want to change the video source input. Will add todo and ping with commit in this thread.

2021-06-30 19:21 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/privateplayer/PrivatePlayerHandler.kt
> +    private var receiveOnly: Boolean = false
Please `Resolve Conversation` if answer is satisfactory or provide with follow up questions/comments.

2021-06-30 19:21 UTC, vespertineSiren commented on app/src/main/res/layout/activity_group_player.xml
> +            android:id="@+id/btnCast"
Please `Resolve Conversation` if answer is satisfactory or provide with follow up questions/comments.

2021-06-30 19:22 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/privateplayer/PrivatePlayerActivity.kt
> +        localMediaStarted = true
I have been meaning to add this to the viewmodel. Will make that change and respond with a commit in this thread.

2021-07-02 21:26 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/privateplayer/PrivatePlayerHandler.kt
> +                            it.videoSource.start()
Here we are: https://github.com/hyfn/trx-consumer-android/pull/145/commits/b02c359319325839e435ee3f71ad8736966a0f78

2021-07-02 21:30 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/privateplayer/PrivatePlayerActivity.kt
> +        localMediaStarted = true
Here we go: https://github.com/hyfn/trx-consumer-android/pull/145/commits/b02c359319325839e435ee3f71ad8736966a0f78

2021-07-02 22:32 UTC, VivekV95 approved these changes

2021-07-02 23:04 UTC, VivekV95 commented on app/src/main/AndroidManifest.xml
> +            android:configChanges="orientation|screenSize" />
Not sure how important this is for the purposes of this PR, but the landscape layouts are not currently being used as we haven't added `screenLayout` to the `configChanges`. However, once we do add that, we'll have to `setContentView` every time a config change happens as view will be destroyed and recreated and all the views will need to have their data re-bound. This applies to all three fm players.

2021-07-02 23:07 UTC, VivekV95 requested changes
Had a thought

2021-07-03 01:29 UTC, vespertineSiren commented on app/src/main/AndroidManifest.xml
> +            android:configChanges="orientation|screenSize" />
I'm not quite following with the issue at hand. The stream survives a layout change and doesn't instantiate another view.

2021-07-03 02:19 UTC, VivekV95 commented on app/src/main/AndroidManifest.xml
> +            android:configChanges="orientation|screenSize" />
It's not using the landscape layout as `setContentView` won't be called due to activity not being created. Landscape orientation is still using portrait layout

2021-07-03 02:28 UTC, vespertineSiren commented on app/src/main/AndroidManifest.xml
> +            android:configChanges="orientation|screenSize" />
![Screenshot_20210702-192719](https://user-images.githubusercontent.com/27742105/124340655-9c962000-db6b-11eb-9dbf-9d6ca5916a7c.png)


I thought this was the landscape?

2021-07-03 02:29 UTC, VivekV95 commented on app/src/main/AndroidManifest.xml
> +            android:configChanges="orientation|screenSize" />
Nah the buttons are aligned to the right side in landscape

2021-07-06 22:34 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/privateplayer/PrivatePlayerActivity.kt
> +                if (checkLivePermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)) {
Make sense, Resolving it. Thank you

2021-07-08 18:44 UTC, vespertineSiren commented on app/src/main/AndroidManifest.xml
> +            android:configChanges="orientation|screenSize" />
Fixed in most recent commits:
https://github.com/hyfn/trx-consumer-android/pull/145/commits/9a1f2b23128c917652c3b4f176a460cebc64645d
https://github.com/hyfn/trx-consumer-android/pull/145/commits/aa715a6d6ea6dc686506b83a125581d52d274b2b
https://github.com/hyfn/trx-consumer-android/pull/145/commits/418dd4b22690c0252e337a5b6aebd9483f56f287
https://github.com/hyfn/trx-consumer-android/pull/145/commits/d7df249ddb717f09c3dbc0b0fdf99303a9d08f64

2021-07-12 16:14 UTC, onodude approved these changes
thank you @vespertineSiren

2021-07-12 18:15 UTC, VivekV95 approved these changes

2021-07-12 18:17 UTC, merged