TCM-547 | Add dummy settings permissions screen
hyfn/trx-consumer-android pull request #151
Opened 2021-06-26 07:56 UTC by GorkemKarayel

### Summary

Add dummy permissions to settings screen

### Issue

 [TCM-547](https://hyfnla.atlassian.net/browse/TCM-547)

### Video/Screenshot

![permission_not_enabled](https://user-images.githubusercontent.com/17555866/123506458-00e94900-d66d-11eb-90ea-ba73d7d43265.png)

![enable_permissions](https://user-images.githubusercontent.com/17555866/123506464-05156680-d66d-11eb-8a08-870ddbc1a3f3.png)

https://user-images.githubusercontent.com/17555866/123506469-08a8ed80-d66d-11eb-8d74-b7f36b51146b.mov

2021-06-30 00:33 UTC, onodude commented on app/src/main/res/layout/row_permission.xml
> +        android:textColor="#212121"
sorry for the wrong specs, lets just use black

2021-06-30 18:56 UTC, onodude commented on app/src/main/res/drawable/bg_permission_switch.xml
> +<?xml version="1.0" encoding="utf-8"?>
would it be possible to set the attributes instead

2021-06-30 18:56 UTC, onodude commented on app/src/main/res/drawable/bg_permission_switch_thumb.xml
> +<?xml version="1.0" encoding="utf-8"?>
same here could we set an attribute for the switch and use default ui

2021-06-30 18:56 UTC, onodude requested changes
looking good @GorkemKarayel added a couple of questions

2021-07-03 17:38 UTC, GorkemKarayel commented on app/src/main/res/drawable/bg_permission_switch.xml
> +<?xml version="1.0" encoding="utf-8"?>
If I'm not wrong we cannot do it. The default switch view in Android is not as in the design. I had to add custom style to this reason. If you have suggestion I can fix it.

2021-07-21 18:47 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/PermissionModel.kt
> +    var id: String = ""
We try to use the primary constructor for properties whenever possible

2021-07-21 18:57 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/permissions/PermissionViewHolder.kt
> +    private val scPermission: SwitchCompat = view.findViewById(R.id.scPermission)
Looks like on Xpass we're going with the `switch` naming convention, so let's rename the property and view id to `switchPermission` to keep things consistent

2021-07-21 20:14 UTC, VivekV95 commented on app/src/main/res/drawable/bg_permission_switch.xml
> +<?xml version="1.0" encoding="utf-8"?>
@onodude Do we need the switches to look exactly like figma? [This](https://user-images.githubusercontent.com/39810816/126553347-d56aa62a-b94f-4fb2-870e-27c60d974aba.png) is the default switch

2021-07-21 20:14 UTC, VivekV95 commented on app/src/main/res/drawable/bg_permission_switch_thumb.xml
> +<?xml version="1.0" encoding="utf-8"?>
Same as [this](https://github.com/hyfn/trx-consumer-android/pull/151/files#r674304356)

2021-07-21 20:15 UTC, VivekV95 requested changes
One change and a question

2021-07-26 20:52 UTC, devender197 commented on app/src/main/java/com/trx/consumer/models/common/SettingsModel.kt
> +                SettingsType.PERMISSIONS -> {
@onodude can we use [xpass](https://github.com/hyfn/xpass-android/blob/develop/app/src/main/java/com/xponential/xpass/screens/settings/SettingsModel.kt#L86) logic here. Except that we have parity issue here from [iOS](https://github.com/hyfn/trx-consumer-ios/pull/268/files#diff-dec0e355099c51081ed0e3a105c2df60167ec6098addbbceebbae234c432c861R55)

2021-07-26 20:56 UTC, devender197 commented on app/src/main/java/com/trx/consumer/models/common/SettingsModel.kt
> +                if (BuildConfig.DEBUG) add(create(null, SettingsType.PERMISSIONS))
Position of permission on setting screen is different than iOS [here](https://github.com/hyfn/trx-consumer-ios/pull/268/files#diff-65aea56938b0a6d5e75c4c8b3282908c82cc26805f590007a716fd65bbcf9e42R21)

2021-07-26 21:06 UTC, devender197 commented on app/src/main/res/layout/row_permission.xml
> +        android:id="@+id/lblPermissionName"
Please consider to name the view as lblTitle similar to iOS [here](https://github.com/hyfn/trx-consumer-ios/pull/268/files#diff-caf7fe970db6f71c85ff9f77344b63eaebcccd38a98556bcd5c81a4eb2d68d62R35)

2021-07-26 21:08 UTC, devender197 commented on app/src/main/res/layout/row_permission.xml
> +        android:id="@+id/scPermission"
Please consider to name view as `btnSelect` similar to iOS [here](https://github.com/hyfn/trx-consumer-ios/pull/268/files#diff-caf7fe970db6f71c85ff9f77344b63eaebcccd38a98556bcd5c81a4eb2d68d62R52)

2021-07-26 21:17 UTC, devender197 commented on app/src/main/res/layout/row_permission.xml
> +        android:layout_marginTop="18dp"
I think, if we are using `android:gravity="center_vertical" ` for `lblPermissionName`. we should use same for `scPermission` for consistency.

2021-07-26 21:29 UTC, devender197 commented on app/src/main/res/layout/row_permission.xml
> +        android:layout_marginTop="18dp"
To center align view like we did for `lblPermissionName` . we can remove the top and bottom padding.

2021-07-26 21:45 UTC, devender197 commented on app/src/main/java/com/trx/consumer/models/common/PermissionModel.kt
> +class PermissionModel {
Permission Model on iOS and android is completely different and liked the way iOS did it [here](https://github.com/hyfn/trx-consumer-ios/pull/268/files#diff-fd500713149621f3bf515dbe2909b5956251069a2fab6ff092c1a2fadd6c5f5cR17)

2021-07-26 21:50 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/permissions/PermissionsViewModel.kt
> +class PermissionsViewModel @ViewModelInject constructor() : BaseViewModel(), PermissionsListener {
@onodude Different name is used for listener `PermissionsListener` on android and on iOS it is and  [PermissionsOptionTableViewListener](https://github.com/hyfn/trx-consumer-ios/pull/268/files#diff-96b423fa20e3d3adbe04a8c7781f74a355918a6d777390b8176ac63209f9b07bR12). and function name for listener is also different.

2021-07-27 18:00 UTC, closed without merging