TCM-526 | Skin LivePlayer
hyfn/trx-consumer-android pull request #152
Opened 2021-06-28 23:33 UTC by vespertineSiren

## Description

### Summary

TBD

### Issue

[TCM-526](https://hyfnla.atlassian.net/browse/TCM-526)

### Video/Screenshot

TBD

2021-07-02 00:57 UTC, onodude commented
could you please add a demo once complete

2021-07-02 22:37 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/liveplayer/LivePlayerActivity.kt
> +    lateinit var handler: LivePlayerHandler
Do the handlers need to be injected? Seems like we'll only be using them in the corresponding screens and not sure we want singleton instances hanging around in memory once the user leaves the screen.

2021-07-03 01:09 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/liveplayer/LivePlayerActivity.kt
> +    lateinit var handler: LivePlayerHandler
Youre right. Not sure why I injected but I can instantiate here either way

2021-07-03 01:19 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/liveplayer/LivePlayerActivity.kt
> +    lateinit var handler: LivePlayerHandler
https://github.com/hyfn/trx-consumer-android/pull/152/commits/df96e92df5b4e778cbaa5f721d5e3e913d28ee2b

2021-07-12 16:14 UTC, onodude approved these changes
thank you @vespertineSiren

2021-07-12 18:18 UTC, onodude approved these changes
thanks!

2021-07-12 18:28 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/liveplayer/LivePlayerActivity.kt
> +    lateinit var container: RelativeLayout
Wanna make sure we nulliify this in `onDestroy` or it'll leak

2021-07-12 18:43 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/liveplayer/LivePlayerViewModel.kt
> +        set(value) {
This is a bit messy, is it needed? Would anything bad happen if the same model is just set again?

2021-07-12 18:47 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/liveplayer/LivePlayerViewModel.kt
> +        set(value) {
Yeah I felt that it was necessary so it doesnt have to do through all those backend calls again if the orientation is changed.

2021-07-12 18:48 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/liveplayer/LivePlayerActivity.kt
>      @Inject
Could we inject the handler into the viewmodel instead and communicate with it through the viewmodel? Currently the pattern is a bit strange because the handler has an instance of the `viewModelScope` but exists in the activity. Also kinda defeats the purpose of having a viewmodel if we're handling this much business logic in the activity anyways

2021-07-12 18:49 UTC, VivekV95 requested changes
Few thoughts

2021-07-12 18:49 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/liveplayer/LivePlayerActivity.kt
>      @Inject
I think that should be a followup task. Much too large to do now.

2021-07-12 18:50 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/liveplayer/LivePlayerActivity.kt
>      @Inject
Yeah that's totally fine

2021-07-12 18:51 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/liveplayer/LivePlayerViewModel.kt
> +        set(value) {
Why would setting the model again cause backend calls?

2021-07-12 18:53 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/liveplayer/LivePlayerViewModel.kt
> +        set(value) {
No it but will replace the previous model that has a valid livereponsemodel here:
```
if (liveResponse.isSuccess) {
                        try {
                            val liveModel = LiveResponseModel.parse(liveResponse.responseString)
                            if (liveModel.isValidType) {
                                workout.live = liveModel
                                localMediaStarted = true
                                eventLoadVideo.postValue(workout)
                            } else {
                                eventLoadError.postValue("There was an error")
                            }
                        } catch (e: Exception) {
                            LogManager.log(e)
                        }
                    }
```

2021-07-12 18:55 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/liveplayer/LivePlayerActivity.kt
> +    lateinit var container: RelativeLayout
Here we are: https://github.com/hyfn/trx-consumer-android/pull/152/commits/d748e198f347321db2d90b4790547fbaa5c70e4a

2021-07-12 18:59 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/liveplayer/LivePlayerViewModel.kt
> +        set(value) {
Yeah not a fan of that pattern at all. Also fine for a later task, but feels really wrong to couple a response model with a model. We don't do that anywhere else. Whatever info we need when entering screen should just be sent as properties in the `WorkoutModel` and the live response info should be stored separately outside the `WorkoutModel`. Fine for now though.

2021-07-12 19:02 UTC, VivekV95 approved these changes

2021-07-12 19:06 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/liveplayer/LivePlayerViewModel.kt
> +        set(value) {
Yeah. I get it. LiveResponseModel should be its own variable. We can add that to the followup.

2021-07-12 19:13 UTC, onodude approved these changes
thank you!

2021-07-12 19:14 UTC, merged