TCM-672 | improve membership
hyfn/trx-consumer-android pull request #157
Opened 2021-07-01 19:20 UTC by devender197

## Description

### Summary

- [ ] Info Label at bottom of membership screen
- [ ] Info label at the bottom of Alert dialog

### Issue

[TCM-672](https://hyfnla.atlassian.net/browse/TCM-672)

### Video/Screenshot

2021-07-01 21:53 UTC, onodude commented
would it be possible to make [this](https://user-images.githubusercontent.com/2285343/124193655-0df6a580-da7c-11eb-9436-c30d91cafaca.png) part centered as well @devender197

2021-07-01 22:21 UTC, devender197 commented
> would it be possible to make [this](https://user-images.githubusercontent.com/2285343/124193655-0df6a580-da7c-11eb-9436-c30d91cafaca.png) part centered as well @devender197

Thank you for review and I have made the changes requested and demo modified [here](https://github.com/hyfn/trx-consumer-android/pull/157/commits/d70be1face7e85358a1dac835408f36a3d72a508)

2021-07-01 22:32 UTC, onodude submitted a review, later dismissed
thank you @devender197

2021-07-02 02:12 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/AlertModel.kt
> +        override fun AlertModel.write(dest: Parcel, flags: Int) {
We don't need to implement all the parcelable stuff, can just store `clearTitle` as a `CharSequenece`. It will retain all of its Spannable properties.

2021-07-02 02:12 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/alert/AlertViewState.kt
> +        get() = if (CLEAR == this) R.font.atcarquette_regular else R.font.atcarquette_bold
`this == CLEAR`

2021-07-02 02:13 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/alert/AlertViewState.kt
> +    val fontFamily: Int
Let's annotate with `@get:FontRes`

2021-07-02 02:14 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/memberships/MembershipsFragment.kt
> +            lblTerm.text(loadTerm())
Feel like we should hide the policy if no memberships come back as there's nothing to purchase

2021-07-02 02:24 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/alert/AlertFragment.kt
> +                        isHidden = secondaryTitle == 0
Have to bring back the `isHidden` check below before setting text or we'll crash when hiding secondary button, as `0` isn't a valid string resource.

2021-07-02 02:26 UTC, VivekV95 requested changes
Looking pretty good, left some thoughts

2021-07-02 06:51 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/alert/AlertViewState.kt
> +        get() = if (CLEAR == this) R.font.atcarquette_regular else R.font.atcarquette_bold
what's the difference here?

2021-07-02 07:03 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/memberships/MembershipsFragment.kt
> +            lblTerm.text(loadTerm())
We haven't create any mechanism to support empty memberships neither empty membership message nor empty list row. So if we need to do that we should create separate task to do that which is out of scope of this task.

2021-07-02 15:16 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/alert/AlertViewState.kt
> +        get() = if (CLEAR == this) R.font.atcarquette_regular else R.font.atcarquette_bold
More conventional to place the the thing we're checking first.

2021-07-02 15:23 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/memberships/MembershipsFragment.kt
> +            lblTerm.text(loadTerm())
Has to do with the design/behavior of an element that we're adding to the screen, so it would be in scope in my opinion. There's already precedent for it as we're doing the same thing with the restore button when memberships are empty for whatever reason. Definitely also need the empty list row, will create a ticket for that.

2021-07-02 17:33 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/alert/AlertViewState.kt
> +    val fontFamily: Int
[Done](https://github.com/hyfn/trx-consumer-android/pull/157/commits/f078dea696b94286b7e7f28bbe74e5e8a3e61c10)

2021-07-02 17:35 UTC, devender197 commented on app/src/main/java/com/trx/consumer/models/common/AlertModel.kt
> +        override fun AlertModel.write(dest: Parcel, flags: Int) {
@VivekV95 Thank you for that. You made it very simple. [Done](https://github.com/hyfn/trx-consumer-android/pull/157/commits/89bf6605bea86454f532dff68499df9a440d33b7#diff-0f9aa846babf82762ee220845605afea58458034f4a3b119f0f96ef5350b9a3eR26)

2021-07-02 17:35 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/memberships/MembershipsFragment.kt
> +            lblTerm.text(loadTerm())
[Done](https://github.com/hyfn/trx-consumer-android/pull/157/commits/89bf6605bea86454f532dff68499df9a440d33b7#diff-630d76159fb59d76ebfa7ccceaf8405e1e61174c1de05f1e2f2f10a68831ef81R65)

2021-07-02 17:41 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/alert/AlertFragment.kt
> +                        isHidden = secondaryTitle == 0
[Done](https://github.com/hyfn/trx-consumer-android/pull/157/files#diff-32a7889db7bcf693fa0187c648be2b84a0c3e142f0ec6577a878f6176a470634R57)

2021-07-02 17:42 UTC, devender197 commented
@onodude @VivekV95 Thank you for the review. Changes are implemented.

2021-07-02 17:48 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/memberships/MembershipsFragment.kt
> +            lblTerm.text(loadTerm())
@onodude I think Footer with static info should not depend on dynamic data and we can pull this out of the scrollview. Dynamic data in center can change and we can display the static information every time regard less of dynamic data. We need to implement the message if in case, we don't have any membership.

2021-07-02 17:54 UTC, onodude commented on app/src/main/java/com/trx/consumer/screens/alert/AlertViewState.kt
> +        get() = if (CLEAR == this) R.font.atcarquette_regular else R.font.atcarquette_bold
not a big deal but yes that is way

2021-07-02 17:56 UTC, onodude commented on app/src/main/java/com/trx/consumer/screens/memberships/MembershipsFragment.kt
> +            lblTerm.text(loadTerm())
i did not get the whole convo here but in the end lets hide the lblTerm on initial state and show it after loading memberships

2021-07-02 19:59 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/memberships/MembershipsFragment.kt
> +            lblTerm.text(loadTerm())
^Yeah that's what I meant, and it stays hidden if memberships are empty for whatever reason. Sorry if I was confusing.

2021-07-02 23:23 UTC, VivekV95 approved these changes
Thanks for the changes!

2021-07-02 23:25 UTC, onodude approved these changes

2021-07-02 23:25 UTC, merged