TCM-708 | Implement view video analytics events
hyfn/trx-consumer-android pull request #159
Opened 2021-07-06 22:20 UTC by devender197

## Description

### Summary

- [ ] VideoEvent, ViewVideo and ViewVideoDetail analytics set

### Issue

[TCM-708](https://hyfnla.atlassian.net/browse/TCM-708)

### Video/Screenshot

#### Event List
<img width="1347" alt="Screen Shot 2021-07-06 at 3 07 59 PM" src="https://user-images.githubusercontent.com/24737954/124673345-8c34bc80-de6d-11eb-9a26-0cc5a0eec6f0.png">

#### Event Detail
<img width="1201" alt="Screen Shot 2021-07-06 at 3 07 41 PM" src="https://user-images.githubusercontent.com/24737954/124673395-a078b980-de6d-11eb-8b80-5368268e6118.png">

2021-07-06 22:38 UTC, onodude requested changes
looks like you over scoped for the sessions not sure why you would add to live and other stuff
this is only about on demand videos please make the necessary adjustments

2021-07-07 18:50 UTC, devender197 commented
> looks like you over scoped for the sessions not sure why you would add to live and other stuff
> this is only about on demand videos please make the necessary adjustments

[Done](Remove the Live and Virtual screen Video View detail analytics)

2021-07-08 19:58 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverViewModel.kt
> +        analyticsManager.trackViewVideoDetail(model, AnalyticsPageModel.DISCOVER)
Can you make this look like:
`analyticsManager.trackViewVideoDetail(model, DISCOVER)`

You did something similarly on Line 20 in the `HomeViewModel`.

2021-07-08 20:01 UTC, vespertineSiren requested changes
LGTM. Just one small change.

2021-07-09 21:36 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverViewModel.kt
> +        analyticsManager.trackViewVideoDetail(model, AnalyticsPageModel.DISCOVER)
[Done](https://github.com/hyfn/trx-consumer-android/pull/159/commits/59f69a2d6b2d752415daf0291507bae730e814b1)

2021-07-09 22:58 UTC, onodude approved these changes
thank you!

2021-07-09 22:59 UTC, merged