TCM-717 | Update CommonStateButton
hyfn/trx-consumer-android pull request #165
Opened 2021-07-08 20:49 UTC by devender197

## Description

### Summary

- [ ]` isChecked = true` condition now able to trigger the drawable change.

### Issue

[TCM-717](https://hyfnla.atlassian.net/browse/TCM-717)

### Video/Screenshot

2021-07-08 21:56 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/privateplayer/PrivatePlayerActivity.kt
> +            btnCamera.isChecked = true
Shouldn't we set the default state in the so there's less code in the activity to deal with?

2021-07-08 21:58 UTC, vespertineSiren approved these changes
Changes make sense to me.

2021-07-09 00:09 UTC, onodude commented on app/src/main/java/com/trx/consumer/screens/privateplayer/PrivatePlayerActivity.kt
> +            btnCamera.isChecked = true
i would agree with this, lets do it if possible

2021-07-09 00:09 UTC, onodude requested changes
@devender197 a question or an issue :)

2021-07-09 00:34 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/privateplayer/PrivatePlayerActivity.kt
> +            btnCamera.isChecked = true
That code was for testing. I am sorry. I removed it.
[Done](https://github.com/hyfn/trx-consumer-android/pull/165/commits/cbe5d3f79cce4217deb4e79bd7c43752841ef1ac)

2021-07-09 01:06 UTC, onodude approved these changes
thanks!

2021-07-09 01:06 UTC, merged