TCM-734 | Add UserId for Amplitude
hyfn/trx-consumer-android pull request #170
Opened 2021-07-12 20:03 UTC by vespertineSiren

## Description

### Summary

- Inject analytics manager to backendmanager, call `AnalyticsManager.setUserId(id: String)` in `BackendManager.user()`.

### Issue

[TCM-734](https://hyfnla.atlassian.net/browse/TCM-734)

### Video/Screenshot

2021-07-12 22:54 UTC, dkhamsing commented
@vespertineSiren in ios we set the amplitude user id in BackendManager.user (similar idea to xpass where it is done in BackendManager.profile).. is that something we can do in android

2021-07-12 23:44 UTC, onodude commented on app/src/main/java/com/trx/consumer/screens/home/HomeViewModel.kt
> +                analyticsManager.setUserId(user.uid)
shouldn't this be in the backend manager where we do: `IAPManager.shared.identify(user.uid)`

2021-07-12 23:44 UTC, onodude requested changes
there are lots of changes?

2021-07-12 23:45 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/home/HomeViewModel.kt
> +                analyticsManager.setUserId(user.uid)
Yeah just clarified it with @dkhamsing over slack. Will revert.

2021-07-12 23:45 UTC, vespertineSiren commented
> there are lots of changes?

A lot of them are ktlint related. Will revert.

2021-07-13 00:34 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/home/HomeViewModel.kt
> +                analyticsManager.setUserId(user.uid)
Here you go: https://github.com/hyfn/trx-consumer-android/pull/170/commits/e40226c4256ff732a898b71d80af4e92a2213998

2021-07-13 16:54 UTC, onodude approved these changes
thanks!

2021-07-13 16:58 UTC, merged