TCM-776 | Dummy Permissions Alert
hyfn/trx-consumer-android pull request #187
Opened 2021-07-28 17:52 UTC by vespertineSiren

## Description

### Summary

- Create PermissionAlert with viewstate and test utility

### Issue

[TCM-776](https://hyfnla.atlassian.net/browse/TCM-776)

### Video/Screenshot

![Uploading Screen Shot 2021-07-27 at 6.11.42 PM.png…]()

2021-07-28 19:22 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/states/PermissionAlertViewState.kt
> +enum class PermissionAlertViewState {
There's an existing `PermissionsAlertViewState` in `develop` that can be used

2021-07-28 19:35 UTC, VivekV95 commented on app/src/main/res/values/strings.xml
> +    <string name="permission_alert_secondary_button">No, I will not join at this time</string>
From [slack](https://commafwd.slack.com/archives/G01JVMJ6G5S/p1627500530014200)

2021-07-28 19:35 UTC, VivekV95 requested changes
Couple comments and merge conflicts

2021-07-28 19:42 UTC, VivekV95 commented on app/src/main/res/values/strings.xml
> +    <string name="permission_alert_secondary_button">No, I will not join at this time</string>
Nvm, label seems fine and makes sense

2021-07-28 22:58 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/states/PermissionAlertViewState.kt
> +enum class PermissionAlertViewState {
Oops. Missed that. Will move over.

2021-07-29 18:00 UTC, VivekV95 approved these changes

2021-07-29 18:03 UTC, onodude approved these changes
thanks!

2021-07-29 18:03 UTC, merged