TCM-138 | Build dummy plans screen
hyfn/trx-consumer-android pull request #19
Opened 2021-04-06 20:56 UTC by halilyesilyurt

## Description

### Summary

- [x] Completed dummy plans screen.
- [x] Added plans to test utility.

### Issue

[TCM-138](https://hyfnla.atlassian.net/browse/TCM-138)

### Video/Screenshot

![plans1](https://user-images.githubusercontent.com/30659854/113777288-8f67c180-9733-11eb-82b0-e84cd6368995.PNG)
![plans2](https://user-images.githubusercontent.com/30659854/113777294-90005800-9733-11eb-9dde-54397e41bf9e.PNG)
![plans3](https://user-images.githubusercontent.com/30659854/113777295-90005800-9733-11eb-8184-b79d980a3a6c.PNG)

2021-04-07 00:43 UTC, onodude commented on app/build.gradle
> +            buildConfigField "String", "kWaiversUrl", '"https://xpass.xpodev.com/api/locations/xponential-xpass/waiver.html"'
lets put a generic trx link if possible :)
maybe `http://trx.sprintfwd.com/`

2021-04-07 00:43 UTC, onodude commented on app/src/main/java/com/trx/consumer/models/common/PlansListModel.kt
> +    private val renewGenericText: SpannableStringBuilder
some of these variables are not used, lets try to keep it lean and remove these

2021-04-08 17:01 UTC, halilyesilyurt commented on app/build.gradle
> +            buildConfigField "String", "kWaiversUrl", '"https://xpass.xpodev.com/api/locations/xponential-xpass/waiver.html"'
Completed.

2021-04-08 17:01 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/models/common/PlansListModel.kt
> +    private val renewGenericText: SpannableStringBuilder
Completed.

2021-04-12 05:21 UTC, VivekV95 commented
@onodude Does iOS currently have `Plans` implemented?

2021-04-21 13:42 UTC, halilyesilyurt commented
resolved conflicts.

2021-04-22 04:15 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/PlansListModel.kt
> +class PlansListModel(
Looks like this is based off `Xpass`'s model, updated the ticket to include iOS's `Plans` module. I believe this should be based on `PlanModel` on the iOS side

2021-04-22 04:18 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/plans/list/PlansListAdapter.kt
> +class PlansListAdapter(
We can rename occurrences of `PlansList` to just `Plan` here as the model will be `PlanModel`

2021-04-22 04:22 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/plans/list/PlansListViewState.kt
> +enum class PlansListViewState {
Let's base this file on [PlansViewState](https://github.com/hyfn/trx-consumer-ios/blob/develop/TRX-Consumer/Screens/Plans/PlansViewState.swift)

2021-04-22 04:25 UTC, VivekV95 commented on app/src/main/res/layout/fragment_plans.xml
> +<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
We'll want to make this a `NestedScrollView` as there's a `RecyclerView` in here

2021-04-22 04:34 UTC, VivekV95 commented on app/src/main/res/layout/fragment_plans.xml
> +            android:layout_marginTop="55dp"
`marginTop` is not needed according to the iOS side

2021-04-22 04:34 UTC, VivekV95 commented on app/src/main/res/layout/fragment_plans.xml
> +            android:text="@string/plans_title"
Lets give this a `textSize` of 11, can place an `ignore` on the warning

2021-04-22 04:35 UTC, VivekV95 commented on app/src/main/res/layout/fragment_plans.xml
> +            android:layout_marginStart="20dp"
Looks like this should be `15dp` according to iOS

2021-04-22 04:40 UTC, VivekV95 commented on app/src/main/res/layout/fragment_plans.xml
> +            android:id="@+id/viewDates"
Let's put the `next` and `last` views in separate `CommonView`s like iOS is doing

2021-04-22 04:43 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/plans/PlansFragment.kt
> +    private val viewModel: PlansViewModel by viewModels()
Let's set up the `RecyclerView` and adapter here and load a test list so that it's visible in the `TestUtility`, can check for the patterns in `PlansViewController` on the iOS side

2021-04-22 04:44 UTC, VivekV95 requested changes
Left a few comments, looks like some of the files may not have been merged on the iOS side based on their creation date when this ticket was created, have updated the ticket.

2021-04-23 14:30 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/models/common/PlansListModel.kt
> +class PlansListModel(
Completed.

2021-04-23 14:30 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/screens/plans/list/PlansListAdapter.kt
> +class PlansListAdapter(
Completed.

2021-04-23 14:30 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/screens/plans/list/PlansListViewState.kt
> +enum class PlansListViewState {
Completed.

2021-04-23 14:30 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_plans.xml
> +<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
Completed.

2021-04-23 14:30 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_plans.xml
> +            android:layout_marginTop="55dp"
Completed.

2021-04-23 14:30 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_plans.xml
> +            android:text="@string/plans_title"
Completed.

2021-04-23 14:31 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_plans.xml
> +            android:layout_marginStart="20dp"
Completed.

2021-04-23 14:34 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_plans.xml
> +            android:id="@+id/viewDates"
i putted "viewBottom" as id. Because we have just one CommonView below the list.

2021-04-23 14:34 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/screens/plans/PlansFragment.kt
> +    private val viewModel: PlansViewModel by viewModels()
Completed.

2021-04-29 21:28 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/PlanModel.kt
> +    var state: PlansViewState = PlansViewState.OTHER
Let's name this `primaryState` to match iOS and move this into the constructor to get rid of the warning

2021-04-29 21:32 UTC, VivekV95 commented on app/src/main/res/layout/fragment_plans.xml
> +            android:id="@+id/viewDates"
Fair enough

2021-04-29 21:43 UTC, VivekV95 requested changes
Looking great, just one last change from me

2021-05-03 08:09 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/models/common/PlanModel.kt
> +    var state: PlansViewState = PlansViewState.OTHER
Completed.

2021-05-06 18:54 UTC, onodude approved these changes

2021-05-06 18:54 UTC, merged