TCM-136 | Build dummy cards screen
hyfn/trx-consumer-android pull request #20
Opened 2021-04-08 20:05 UTC by halilyesilyurt

## Description

### Summary

- [x] Completed dummy cards screen.
- [x] Added navigation to test utility.

### Issue

[TCM-136](https://hyfnla.atlassian.net/browse/TCM-136)

### Video/Screenshot

| Has Card | No Card|
|--------|------|
|![cards_has_card](https://user-images.githubusercontent.com/30659854/114089415-cae2c700-98be-11eb-8245-4620f5587978.png)|![cards_no_card](https://user-images.githubusercontent.com/30659854/114089418-cb7b5d80-98be-11eb-9cfe-0f322fc4f481.png)|

2021-04-08 22:36 UTC, onodude submitted a review, later dismissed
thanks!

2021-04-09 01:24 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/CardModel.kt
> +    val typeText: Int
Let's give this @get:StringRes

2021-04-09 01:24 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/CardModel.kt
> +    val imageName: Int
Let's give this @get:DrawableRes

2021-04-09 01:25 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/CardModel.kt
> +                "mc" -> {
Can just be `"mc" -> R.string.cards_type_text_master_card` along with all the other as everything fits in one line

2021-04-09 01:33 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/CardModel.kt
> +    val typeText: Int
Ignore the above, we'll make this in an improvement ticket for both trx and xpass

2021-04-09 01:33 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/CardModel.kt
> +                "mc" -> {
Ignore the above, we'll make this in an improvement ticket for both trx and xpass

2021-04-09 01:33 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/CardModel.kt
> +    val imageName: Int
Ignore the above, we'll make this in an improvement ticket for both trx and xpass

2021-04-09 01:58 UTC, VivekV95 approved these changes

2021-04-12 04:23 UTC, VivekV95 requested changes
Conflicts with `develop`

2021-04-17 23:12 UTC, VivekV95 approved these changes

2021-04-19 17:32 UTC, onodude approved these changes

2021-04-19 17:32 UTC, merged