TCM-101 | Build dummy addcard screen
hyfn/trx-consumer-android pull request #21
Opened 2021-04-09 19:51 UTC by halilyesilyurt

## Description

### Summary

- [x] Completed dummy addcard screen.
- [x] Added addcard screen navigation to test utility.

### Issue

[TCM-101](https://hyfnla.atlassian.net/browse/TCM-101)

### Video/Screenshot

![add_card](https://user-images.githubusercontent.com/30659854/114233378-e1078a80-9985-11eb-9f55-37cd585eda29.png)

https://user-images.githubusercontent.com/30659854/114233396-ec5ab600-9985-11eb-83b9-d044693614e7.mp4

2021-04-12 04:44 UTC, VivekV95 commented on app/src/main/res/layout/fragment_add_card.xml
> +        android:id="@+id/ivExpirtyDate"
There's a typo in the specs, let's change this to "ivExpiryDate"

2021-04-12 04:46 UTC, VivekV95 commented on app/src/main/res/layout/fragment_add_card.xml
> +            android:layout_marginStart="20dp"
Let's make this `15dp` to match the input view margins

2021-04-12 04:47 UTC, VivekV95 commented on app/src/main/res/values/strings.xml
> +    <string name="inputview_placeholder_expiration">EXPIRTY DATE</string>
Same typo from the specs, "EXPIRY"

2021-04-12 04:54 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/views/input/InputView.kt
> +            if (mState == InputViewState.CVV) {
Is this needed? If not, let's remove

2021-04-12 04:56 UTC, VivekV95 commented on app/build.gradle
> +            buildConfigField "Integer", "kExpirationDateLimit", "5"
@onodude I see the specs showing a 2 digit year and not 4 digit year [here](https://www.figma.com/file/wMfhxL9w3KOw6okQJtt1OD/All-Screens-(v1.0.0)?node-id=1700%3A4524), just verifying that's what we want:

2021-04-12 04:58 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/views/input/InputView.kt
> +            if (mState == InputViewState.CVV) {
Ah I see it's for hiding the code. Looks like we'll need to do the for the credit card too, so let's revert this and tackle it in a separate ticket

2021-04-12 04:59 UTC, VivekV95 requested changes
Looks great, left a few comments

2021-04-12 05:17 UTC, VivekV95 commented on app/src/main/res/values/strings.xml
> +    <string name="inputview_placeholder_expiration">EXPIRTY DATE</string>
Actually, let's just keep the strings consistent with what iOS has right now, we'll modify both together to match design specs is needed: [iOS](https://github.com/hyfn/trx-consumer-ios/blob/develop/TRX-Consumer/Screens/Input/InputViewState.swift)

2021-04-12 05:19 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/views/input/InputViewState.kt
> -                1 -> {
Any reason for the removal? If not, let's revert this

2021-04-13 18:49 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_add_card.xml
> +        android:id="@+id/ivExpirtyDate"
Completed.

2021-04-13 18:49 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_add_card.xml
> +            android:layout_marginStart="20dp"
Completed.

2021-04-13 18:49 UTC, halilyesilyurt commented on app/src/main/res/values/strings.xml
> +    <string name="inputview_placeholder_expiration">EXPIRTY DATE</string>
Completed.

2021-04-13 18:49 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/views/input/InputView.kt
> +            if (mState == InputViewState.CVV) {
Completed.

2021-04-13 18:51 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/views/input/InputViewState.kt
> -                1 -> {
Yes it was needed for correct text typing.

2021-04-17 22:08 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/views/input/InputViewState.kt
> -                1 -> {
This is needed in order to auto-input a "0" if any number other than "1" is typed. For ex, if a user types "2", it'll auto-input "02/". It's just a convenience thing. Either way, if we end up doing this,  let's revert and tackle in a separate ticket as it touches a core file

2021-04-17 22:11 UTC, VivekV95 commented on app/build.gradle
> +            buildConfigField "Integer", "kExpirationDateLimit", "5"
Looks like this is still "7" on the [iOS](https://github.com/hyfn/trx-consumer-ios/blob/develop/TRX-Consumer/Core/Constants.swift#L40) side, let's revert

2021-04-17 22:12 UTC, VivekV95 requested changes
Couple things

2021-04-21 13:35 UTC, halilyesilyurt commented on app/build.gradle
> +            buildConfigField "Integer", "kExpirationDateLimit", "5"
Completed.

2021-04-21 13:35 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/views/input/InputViewState.kt
> -                1 -> {
Completed.

2021-04-21 20:28 UTC, VivekV95 approved these changes

2021-04-22 01:27 UTC, onodude approved these changes

2021-04-22 01:27 UTC, merged