TCM-158 | Forms move top image into scrollview
hyfn/trx-consumer-android pull request #22
Opened 2021-04-10 07:28 UTC by halilyesilyurt

## Description

### Summary

- [x] Moved email and login layouts into scrollview.
- [x] A few padding fixes.

### Issue

[TCM-158](https://hyfnla.atlassian.net/browse/TCM-158)

### Video/Screenshot

2021-04-12 05:03 UTC, VivekV95 commented on app/src/main/res/layout/fragment_email.xml
> +    app:layout_constraintBottom_toBottomOf="parent"
Don't think the constraints are needed as we're matching parent dimensions

2021-04-12 05:04 UTC, VivekV95 commented on app/src/main/res/layout/fragment_login.xml
> +    app:layout_constraintBottom_toBottomOf="parent"
Same as email, don't think the constraints are needed

2021-04-12 05:08 UTC, VivekV95 requested changes
Couple small things, also while we're here, let's make the dividers `greyLight` instead of `grey` in `login`, `email`, and `register` like they are in iOS

2021-04-13 18:19 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_email.xml
> +    app:layout_constraintBottom_toBottomOf="parent"
Completed.

2021-04-13 18:19 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_login.xml
> +    app:layout_constraintBottom_toBottomOf="parent"
Completed.

2021-04-15 15:44 UTC, halilyesilyurt commented
Added demos.

2021-04-17 21:52 UTC, VivekV95 commented on app/src/main/res/layout/fragment_email.xml
> +                android:id="@+id/vLine"
Let's make the dividers in `login`, `register`, and `email` `greyLight`

2021-04-17 21:52 UTC, VivekV95 requested changes
One last thing

2021-04-21 13:10 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_email.xml
> +                android:id="@+id/vLine"
Completed.

2021-04-21 20:27 UTC, VivekV95 approved these changes

2021-04-22 01:28 UTC, onodude approved these changes

2021-04-22 01:28 UTC, merged