TCM-104 | Build dummy update screen
hyfn/trx-consumer-android pull request #23
Opened 2021-04-11 11:00 UTC by halilyesilyurt

## Description

### Summary

- [x] Completed dummy update screen.
- [x] Added update screen navigation to test utility.

### Issue

[TCM-104](https://hyfnla.atlassian.net/browse/TCM-104)

### Video/Screenshot

CREATE
![update_state_create](https://user-images.githubusercontent.com/30659854/114301563-069fab80-9ace-11eb-98ed-2df997fe65f6.png)

EDIT
![update_state_edit](https://user-images.githubusercontent.com/30659854/114301565-07384200-9ace-11eb-84fa-fb7db523dbd7.png)

2021-04-12 05:14 UTC, VivekV95 commented on app/src/main/res/layout/fragment_update.xml
> +<?xml version="1.0" encoding="utf-8"?>
Some extra spaces in this file

2021-04-12 05:22 UTC, VivekV95 commented on app/src/main/res/values/strings.xml
> +    <string name="inputview_placeholder_birthday">BIRTHDAY</string>
Let's keep the strings consistent with [iOS](https://github.com/hyfn/trx-consumer-ios/blob/develop/TRX-Consumer/Screens/Input/InputViewState.swift) for now

2021-04-12 05:25 UTC, VivekV95 commented on app/src/main/res/layout/fragment_update.xml
> +        android:layout_width="0dp"
Can just make width `match_parent` and remove the horizontal constraints

2021-04-12 05:27 UTC, VivekV95 commented on app/src/main/res/layout/fragment_update.xml
> +<?xml version="1.0" encoding="utf-8"?>
Let's also code format this file

2021-04-12 05:28 UTC, VivekV95 commented on app/src/main/res/layout/fragment_update.xml
> +        android:layout_width="0dp"
Same here, can make width `match_parent` and remove horizontal constraints

2021-04-12 05:29 UTC, VivekV95 commented on app/src/main/res/layout/fragment_update.xml
> +            <View
Let's make all the dividers `greyLight`

2021-04-12 05:29 UTC, VivekV95 commented on app/src/main/res/layout/fragment_update.xml
> +                android:id="@+id/ivProfile"
Convention is `imgProfile`

2021-04-12 05:32 UTC, VivekV95 commented on app/src/main/res/layout/fragment_update.xml
> +        android:fontFamily="@font/atcarquette_regular"
Specs have this as regular but let's make this bold like iOS is doing, we'll probably eventually create a style for this

2021-04-12 05:33 UTC, VivekV95 commented on app/src/main/res/layout/fragment_update.xml
> +        app:layout_constraintBottom_toBottomOf="parent"
Can use `style="@style/MatchParentEdgesViewStyle"` for this

2021-04-12 05:33 UTC, VivekV95 commented on app/src/main/res/layout/fragment_update.xml
> +        android:layout_width="0dp"
Can `match_parent` here and remove horizontal constraints

2021-04-12 05:38 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/views/input/InputViewState.kt
> +                    if (userInput.first().toString().toInt() !in intArrayOf(
Let's revert this, auto-format probably picked it up but we'll dedicate tickets to fixing core files

2021-04-12 05:41 UTC, VivekV95 requested changes
Looking great, left a few comments

2021-04-13 18:09 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_update.xml
> +<?xml version="1.0" encoding="utf-8"?>
Completed.

2021-04-13 18:09 UTC, halilyesilyurt commented on app/src/main/res/values/strings.xml
> +    <string name="inputview_placeholder_birthday">BIRTHDAY</string>
Completed.

2021-04-13 18:09 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_update.xml
> +        android:layout_width="0dp"
Completed.

2021-04-13 18:09 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_update.xml
> +        android:layout_width="0dp"
Completed.

2021-04-13 18:09 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_update.xml
> +            <View
Completed.

2021-04-13 18:09 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_update.xml
> +                android:id="@+id/ivProfile"
Completed.

2021-04-13 18:09 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_update.xml
> +        android:fontFamily="@font/atcarquette_regular"
Completed.

2021-04-13 18:09 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_update.xml
> +        app:layout_constraintBottom_toBottomOf="parent"
Completed.

2021-04-13 18:10 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_update.xml
> +        android:layout_width="0dp"
Completed.

2021-04-13 18:10 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/views/input/InputViewState.kt
> +                    if (userInput.first().toString().toInt() !in intArrayOf(
Completed.

2021-04-17 21:39 UTC, VivekV95 approved these changes

2021-04-19 17:34 UTC, onodude commented
we wont have the profile image and some paddings/colors seem off lets check iOS for parity and also resolve the conflicts

2021-04-24 20:35 UTC, halilyesilyurt commented
> we wont have the profile image and some paddings/colors seem off lets check iOS for parity and also resolve the conflicts

removed profile image and tried to make similar to ios side.

2021-04-24 20:36 UTC, halilyesilyurt commented
pr images updated.

2021-04-28 04:01 UTC, VivekV95 approved these changes

2021-04-28 17:35 UTC, onodude approved these changes

2021-04-28 17:35 UTC, merged