TCM-105 | Build dummy content screen
hyfn/trx-consumer-android pull request #24
Opened 2021-04-25 19:43 UTC by halilyesilyurt

## Description

### Summary

- [x] Completed dummy content screen.
- [x] Added dummy content to test utility.

### Issue

[TCM-105](https://hyfnla.atlassian.net/browse/TCM-105)

### Video/Screenshot

| State Book| State Plain|
|--------|--------|
|![content_state_book](https://user-images.githubusercontent.com/30659854/116007244-7b6afd80-a617-11eb-918e-06fba91c9fff.png)|![content_state_plain](https://user-images.githubusercontent.com/30659854/116007245-7c9c2a80-a617-11eb-9db7-6da566ce52b6.png)|

2021-04-28 04:06 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/WaiverModel.kt
> +data class WaiverModel(var covid: String = "", var terms: String = "") : Parcelable {
Think we can remove this as iOS doesn't have it

2021-04-28 04:07 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/ContentModel.kt
> +    var state: ContentViewState = ContentViewState.PLAIN,
Let's remove the `state` and `waiverModel` properties to match iOS

2021-04-28 04:08 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/content/ContentViewState.kt
> +enum class ContentViewState {
Think we can remove this as iOS doesn't have it

2021-04-28 04:10 UTC, VivekV95 requested changes
Few things we can remove that I don't think we'll need in TRX

2021-04-29 17:24 UTC, onodude approved these changes

2021-04-29 17:24 UTC, merged