TCM-110 | Build dummy settings screen
hyfn/trx-consumer-android pull request #27
Opened 2021-05-12 12:18 UTC by halilyesilyurt

## Description

### Summary

- [x] Completed dummy settings screen.
- [x] Added settings to test utility.

### Issue

[TCM-110](https://hyfnla.atlassian.net/browse/TCM-110)

### Video/Screenshot

BEFORE SCROLL

![settings_1](https://user-images.githubusercontent.com/30659854/117973347-f67d2500-b334-11eb-874c-779ce19f077a.png)

AFTER SCROLL

![settings_2](https://user-images.githubusercontent.com/30659854/117973345-f5e48e80-b334-11eb-8380-157108fce986.png)

DEMO

https://user-images.githubusercontent.com/30659854/117973438-114f9980-b335-11eb-8ca9-343a68c8dbd4.mp4

2021-05-15 20:45 UTC, onodude commented
design specs updated

2021-05-19 06:12 UTC, halilyesilyurt commented
updated pr images and demo.

2021-05-19 18:17 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/managers/UtilityManager.kt
> +        return "App Version " + buildVersion() + "." + appVersion()
Let's use String interpolation here

2021-05-19 19:03 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/settings/SettingsViewModel.kt
> +    val eventLoadView = CommonLiveEvent<MutableList<Any>>()
Can just accept a `List<Any>`

2021-05-19 19:21 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/settings/SettingsFragment.kt
> +    private val handleLoadView = Observer<MutableList<Any>> { list ->
Related to [this](https://github.com/hyfn/trx-consumer-android/pull/27/files#r635510501)

2021-05-19 19:35 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/settings/option/SettingsOptionViewHolder.kt
> +        if (model.setMarginBottom)
We don't need this, as `EmptyViewHolder` handles the spacing between cells.

2021-05-19 19:36 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/settings/SettingsModel.kt
> +            return mutableListOf<Any>().apply {
We can just `add(0)` wherever we need spaces between cells. It becomes an `EmptyViewHolder` in the adapter.

2021-05-19 19:41 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/settings/SettingsModel.kt
> +    var setMarginBottom = false
Let's remove this after letting `EmptyViewHolder` handle the spaces between cells

2021-05-19 19:43 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/settings/SettingsModel.kt
> +                SettingsType.PAYMENT_METHODS -> {
Can fit on one line `SettingsType.PAYMENT_METHODS -> user?.card?.let { "None" } ?: "Connected"`

2021-05-19 19:45 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/settings/SettingsModel.kt
> +        fun list(user: UserModel?): MutableList<Any> {
Can just return `List<Any>` and in the body, can do 
```
return listOf<Any>(
     create(null, SettingsType.EDIT_PROFILE, true)
     create(user, SettingsType.SUBSCRIPTIONS, false)
     )

2021-05-19 19:48 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/settings/SettingsModel.kt
> +                add(create(null, SettingsType.EDIT_PROFILE, true))
Based on the [design](https://www.figma.com/file/wMfhxL9w3KOw6okQJtt1OD/All-Screens-(v1.0.0)?node-id=478%3A327), let's remove `EDIT_PROFILE`, `PAYMENT_METHODS`, and `NOTIFICATIONS` as they won't be in v1

2021-05-19 20:08 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/settings/SettingsModel.kt
> +    val textColor: Int
Let's call this `titleTextColor` for clarity

2021-05-19 20:08 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/settings/SettingsModel.kt
> +    val textSize: Int
Let's call this `titleTextSize` for clarity

2021-05-19 20:09 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/settings/option/SettingsOptionViewHolder.kt
> +                setTextSize(TypedValue.COMPLEX_UNIT_SP, 10.toFloat())
Don't think we need this, the correct text size is already set above

2021-05-19 20:11 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/settings/option/SettingsOptionViewHolder.kt
> +                lblSubtitle.visibility = View.GONE
lblSubtitle.isVisible = false

2021-05-19 20:17 UTC, VivekV95 commented on app/src/main/res/layout/row_settings_option.xml
> +        android:layout_width="0dp"
can just `match_parent` here instead of using horizontal constraints

2021-05-19 20:22 UTC, VivekV95 requested changes
Looking good overall, left some comments

2021-05-19 20:34 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/managers/UtilityManager.kt
> +        return "App Version " + buildVersion() + "." + appVersion()
Completed.

2021-05-19 20:34 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/screens/settings/SettingsViewModel.kt
> +    val eventLoadView = CommonLiveEvent<MutableList<Any>>()
Completed.

2021-05-19 20:34 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/screens/settings/SettingsModel.kt
> +    var setMarginBottom = false
Completed.

2021-05-19 20:34 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/screens/settings/SettingsFragment.kt
> +    private val handleLoadView = Observer<MutableList<Any>> { list ->
Completed.

2021-05-19 20:35 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/screens/settings/option/SettingsOptionViewHolder.kt
> +        if (model.setMarginBottom)
Completed.

2021-05-19 20:35 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/screens/settings/SettingsModel.kt
> +            return mutableListOf<Any>().apply {
Completed.

2021-05-19 20:35 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/screens/settings/SettingsModel.kt
> +                SettingsType.PAYMENT_METHODS -> {
Completed.

2021-05-19 20:36 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/screens/settings/SettingsModel.kt
> +        fun list(user: UserModel?): MutableList<Any> {
i guess, we cannot use add(0) if the return type is listof.

2021-05-19 20:37 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/screens/settings/SettingsModel.kt
> +                add(create(null, SettingsType.EDIT_PROFILE, true))
Completed.

2021-05-19 20:37 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/screens/settings/SettingsModel.kt
> +    val textColor: Int
Completed.

2021-05-19 20:37 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/screens/settings/SettingsModel.kt
> +    val textSize: Int
Completed.

2021-05-19 20:41 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/screens/settings/option/SettingsOptionViewHolder.kt
> +                setTextSize(TypedValue.COMPLEX_UNIT_SP, 10.toFloat())
I think we need this because; when subtitle is not empty then title text size is 10sp as design specs .

2021-05-19 20:41 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/screens/settings/option/SettingsOptionViewHolder.kt
> +                lblSubtitle.visibility = View.GONE
Completed.

2021-05-19 20:41 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/screens/settings/option/SettingsOptionViewHolder.kt
> +                isAllCaps = true
Completed.

2021-05-19 20:41 UTC, halilyesilyurt commented on app/src/main/res/layout/row_settings_option.xml
> +        android:layout_width="0dp"
Completed.

2021-05-19 20:42 UTC, halilyesilyurt commented
updated pr image.

2021-05-20 00:39 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/settings/option/SettingsOptionViewHolder.kt
> +                setTextSize(TypedValue.COMPLEX_UNIT_SP, 10.toFloat())
We do need it, but we're already doing it above in line 24 `setTextSize(TypedValue.COMPLEX_UNIT_SP, model.titleTextSize.toFloat())`, unless I'm missing something

2021-05-20 00:42 UTC, VivekV95 requested changes
Conflicts and one last thing

2021-05-20 01:00 UTC, onodude commented
lets resolve the conflicts and match the latests specs

2021-05-20 11:59 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/screens/settings/option/SettingsOptionViewHolder.kt
> +                setTextSize(TypedValue.COMPLEX_UNIT_SP, 10.toFloat())
Sorry @VivekV95  i guess you are right :)

2021-05-20 15:48 UTC, onodude approved these changes

2021-05-20 15:48 UTC, merged