TCM-289 | Connect `Update`
hyfn/trx-consumer-android pull request #33
Opened 2021-05-16 02:21 UTC by vespertineSiren

## Description

### Summary

- [x] Account Creation should lead to Update before going to Onboarding (not implemented) then Home. 
- [x] Created color value that handles `enabled` state
- [x] Use temporary [save function](https://github.com/hyfn/trx-consumer-android/commit/271bc4f9d0b414764db34af7907b36a1cffb1c3c)
- [x] Add some events and functions in Update already present on iOS   
- [ ] Needs tests

Notes:
 - Date picker is constantly firing events to the listener in the viewmodel when the date hasn't been confirmed yet. Is this intended?

### Issue

[TCM-289](https://hyfnla.atlassian.net/browse/TCM-289)

### Video/Screenshot

https://user-images.githubusercontent.com/27742105/118383456-a612fb00-b5b2-11eb-8be4-cec3bc811e90.mov

2021-05-16 03:51 UTC, onodude commented
looks great @vespertineSiren thank you for the demo!

2021-05-16 18:48 UTC, onodude commented on app/src/main/res/color/save_button_tint_color.xml
> +    <item android:color="@color/blackRussian" />
blackRussian ?

2021-05-16 18:49 UTC, onodude commented on app/src/main/java/com/trx/consumer/screens/update/UpdateViewModel.kt
> +    private val requestSave: HashMap<String, Any>
params

2021-05-16 18:49 UTC, onodude commented on app/src/main/java/com/trx/consumer/screens/update/UpdateViewModel.kt
> +    private fun doCallSave() {
doCallUpdate

2021-05-16 18:49 UTC, onodude commented on app/src/main/java/com/trx/consumer/screens/update/UpdateViewModel.kt
> +            val response = backendManager.save(requestSave)
backendManager.update

2021-05-16 18:50 UTC, onodude commented on app/src/main/java/com/trx/consumer/screens/update/UpdateFragment.kt
> +            eventShowVerification.observe(viewLifecycleOwner, handleShowVerification)
please organize these

2021-05-16 18:51 UTC, onodude commented on app/src/main/java/com/trx/consumer/managers/BackendManager.kt
> +        }
why is this necessary?

2021-05-16 19:29 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/managers/BackendManager.kt
> +        }
I thought we had to cache all that data from Update

2021-05-16 19:30 UTC, vespertineSiren commented on app/src/main/res/color/save_button_tint_color.xml
> +    <item android:color="@color/blackRussian" />
Color was on there previously. Will use other black

2021-05-16 19:31 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/update/UpdateViewModel.kt
> +    private fun doCallSave() {
Function name based on button.. should I change the button name as well to make it more in line with iOS?

2021-05-16 19:31 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/update/UpdateViewModel.kt
> +            val response = backendManager.save(requestSave)
Will change function ma.e

2021-05-16 21:28 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/update/UpdateFragment.kt
> +            eventShowVerification.observe(viewLifecycleOwner, handleShowVerification)
Here you are https://github.com/hyfn/trx-consumer-android/pull/33/commits/802936af00cc6643c3462a373f4325cd3a1f61ba

2021-05-16 21:28 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/update/UpdateViewModel.kt
> +            val response = backendManager.save(requestSave)
Here you are https://github.com/hyfn/trx-consumer-android/pull/33/commits/802936af00cc6643c3462a373f4325cd3a1f61ba

2021-05-16 21:28 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/update/UpdateViewModel.kt
> +    private fun doCallSave() {
Here you are https://github.com/hyfn/trx-consumer-android/pull/33/commits/802936af00cc6643c3462a373f4325cd3a1f61ba

2021-05-16 21:28 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/update/UpdateViewModel.kt
> +    private val requestSave: HashMap<String, Any>
Here you are https://github.com/hyfn/trx-consumer-android/pull/33/commits/802936af00cc6643c3462a373f4325cd3a1f61ba

2021-05-16 21:28 UTC, vespertineSiren commented on app/src/main/res/color/save_button_tint_color.xml
> +    <item android:color="@color/blackRussian" />
Here you are https://github.com/hyfn/trx-consumer-android/pull/33/commits/802936af00cc6643c3462a373f4325cd3a1f61ba

Need to taskify since used in 17 other instances
<img width="436" alt="Screen Shot 2021-05-16 at 1 38 14 PM" src="https://user-images.githubusercontent.com/27742105/118413222-035e8900-b653-11eb-91d2-ab5c4c857201.png">

2021-05-16 23:27 UTC, onodude commented on app/src/main/java/com/trx/consumer/managers/BackendManager.kt
> +        }
hmm not sure about these additions

2021-05-16 23:28 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/managers/BackendManager.kt
> +        }
Sure. Can remove.

2021-05-16 23:30 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/managers/BackendManager.kt
> +        }
Here we are: https://github.com/hyfn/trx-consumer-android/pull/33/commits/6585d1f5929e5562119b70a57d5dcd0fb8f17e15

2021-05-16 23:36 UTC, onodude commented on app/src/main/java/com/trx/consumer/screens/update/UpdateViewModel.kt
> +        viewModelScope.launch {
needs state check, user can only be there on edit

2021-05-16 23:37 UTC, onodude commented on app/src/main/java/com/trx/consumer/screens/update/UpdateViewModel.kt
> +        doCallContinue()
this should be doCallUpdate based on state

2021-05-16 23:50 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/update/UpdateViewModel.kt
> +        viewModelScope.launch {
Here we are are: 
https://github.com/hyfn/trx-consumer-android/pull/33/commits/566ba50ff026751e2724590d6b12288abe2aa437

2021-05-16 23:50 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/update/UpdateViewModel.kt
> +        doCallContinue()
Here we are are: 
https://github.com/hyfn/trx-consumer-android/pull/33/commits/566ba50ff026751e2724590d6b12288abe2aa437

2021-05-17 00:18 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/update/UpdateFragment.kt
> +        // TODO: ErrorAlertModel modal presentation
`ErrorAlert` is in so I think we can just knock this out

2021-05-17 00:23 UTC, VivekV95 commented on app/src/main/res/color/save_button_tint_color.xml
> +    <item android:color="@color/blackRussian" />
That was me, Google told me that's the official name 😂

2021-05-17 00:27 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/update/UpdateViewModel.kt
> +                    UpdateViewState.CREATE -> {
Looks like iOS has a constant `kIsVerificationEnabled` that it checks here to decide which screen to show

2021-05-17 00:35 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/update/UpdateViewModel.kt
> +                    UpdateViewState.EDIT -> eventLoadSuccess.postValue("Success: TEMP")
I think we can show the actual success and error messages here even though `Alert` isn't implemented, less likely to miss cases like this later that way. Or we can add a `Todo`, I'm fine with either.

2021-05-17 00:40 UTC, VivekV95 commented on app/src/main/res/color/continue_button_state_color.xml
> +<?xml version="1.0" encoding="utf-8"?>
I think we generally handle this programatically instead of using a selector for parity with iOS

2021-05-17 00:54 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/update/UpdateViewModel.kt
> +        val enabled = firstName.isNotEmpty() &&
I'm honestly not confident enough that whatever comes through `doUpdateText` is properly validated to just do an empty check here, think it's safer to just use the `InputViewState` to do the checks (even though it seems redundant), already seeing a problem with zipcode

https://user-images.githubusercontent.com/39810816/118418926-0ae85700-b680-11eb-8ab8-1e1b8d52ba1c.mov

2021-05-17 01:57 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/update/UpdateViewModel.kt
> +        val enabled = firstName.isNotEmpty() &&
Heres a possible solution: https://github.com/hyfn/trx-consumer-android/pull/33/commits/029d2df9cef6709c58f60ae22450930e499bf7c9

2021-05-17 01:57 UTC, vespertineSiren commented on app/src/main/res/color/continue_button_state_color.xml
> +<?xml version="1.0" encoding="utf-8"?>
Removed here: https://github.com/hyfn/trx-consumer-android/pull/33/commits/029d2df9cef6709c58f60ae22450930e499bf7c9

2021-05-17 01:57 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/update/UpdateViewModel.kt
> +                    UpdateViewState.EDIT -> eventLoadSuccess.postValue("Success: TEMP")
Changed here: https://github.com/hyfn/trx-consumer-android/pull/33/commits/029d2df9cef6709c58f60ae22450930e499bf7c9

2021-05-17 01:57 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/update/UpdateViewModel.kt
> +                    UpdateViewState.CREATE -> {
Added here: https://github.com/hyfn/trx-consumer-android/pull/33/commits/029d2df9cef6709c58f60ae22450930e499bf7c9

2021-05-17 01:58 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/update/UpdateFragment.kt
> +        // TODO: ErrorAlertModel modal presentation
Here we go: https://github.com/hyfn/trx-consumer-android/pull/33/commits/029d2df9cef6709c58f60ae22450930e499bf7c9

2021-05-17 03:58 UTC, onodude submitted a review, later dismissed

2021-05-17 04:01 UTC, onodude commented on app/src/main/java/com/trx/consumer/screens/update/UpdateViewModel.kt
> +        val enabled = firstName.isNotEmpty() &&
please check out `Xpass.EditProfileViewModel.validate`
try to make use of the `validate` methods of the states

2021-05-17 04:01 UTC, onodude requested changes
@vespertineSiren please check out `Xpass.EditProfileViewModel.validate`
try to make use of the `validate` methods of the states

2021-05-17 17:14 UTC, onodude approved these changes
thank you!

2021-05-17 17:47 UTC, VivekV95 commented on app/src/main/res/layout/fragment_update.xml
> +        android:backgroundTint="@color/greyDark"
We'll want to use `app:backgroundColor="@color/greyDark"` here as the tint is always applied over the drawable that's set programatically

https://user-images.githubusercontent.com/39810816/118533742-0a969d00-b70e-11eb-9557-070d60515dc1.mov

2021-05-17 17:52 UTC, VivekV95 requested changes
One last thing

2021-05-17 20:17 UTC, VivekV95 approved these changes

2021-05-17 22:28 UTC, onodude approved these changes

2021-05-17 22:28 UTC, onodude commented
thank you @vespertineSiren @VivekV95 🚀

2021-05-17 22:28 UTC, merged