TCM-272 | Build dummy videos screen
hyfn/trx-consumer-android pull request #35
Opened 2021-05-16 16:56 UTC by halilyesilyurt

## Description

I could only add dummy screenshots.

### Summary

- [x] Completed dummy videos screen.
- [x] Added videos screen navigation to test utility.

### Issue

[TCM-272](https://hyfnla.atlassian.net/browse/TCM-272)

### Video/Screenshot

| BEFORE_SCROLL| AFTER_SCROLL|
|--------|--------|
|![videos_1](https://user-images.githubusercontent.com/30659854/118405457-b2658980-b680-11eb-9a1e-4e250625be49.PNG)|![videos_2](https://user-images.githubusercontent.com/30659854/118405458-b2fe2000-b680-11eb-9fb7-fa2c4cf6aca8.PNG)|

2021-05-17 10:31 UTC, halilyesilyurt commented
updated pr images and added demo.

2021-05-17 21:01 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/params/VideoParamsModel.kt
> +data class VideoParamsModel(
Don't think `VideosFragment` will be receiving a `WorkoutModel`, let's create a `VideosModel` that will have the following properties:
```
@Parcelize
class VideosModel(
    val title: String = "",
    val poster: String = "",
    val trainer: TrainerModel = TrainerModel(),
    val videos: List<VideoModel> = emptyList()
): Parcelable
```
that will be sent to `VideosFragment`

2021-05-17 21:01 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/params/VideoParamsModel.kt
> +data class VideoParamsModel(
@onodude Confirming if this is correct

2021-05-17 21:17 UTC, VivekV95 commented on app/src/main/res/layout/fragment_videos.xml
> +                    android:backgroundTint="@color/white"
Not needed as background it already white

2021-05-17 21:18 UTC, VivekV95 commented on app/src/main/res/layout/fragment_videos.xml
> +                    android:id="@+id/btnTrainerProfile"
Looks like this needs a border according to the [design](https://www.figma.com/file/wMfhxL9w3KOw6okQJtt1OD/All-Screens-(v1.0.0)?node-id=2630%3A2), can use `app:outline="@color/black"`

2021-05-17 21:38 UTC, VivekV95 commented on app/src/main/res/layout/fragment_videos.xml
> +                    android:layout_width="match_parent"
Would be good to give this a slight alpha to make sure the title is visible (as the title color is white and a lot of the videos/workouts seem to have white backgrounds in their poster). We can do the same thing we're doing in the row view: `android:tint="@color/blackAlpha20"`

2021-05-17 21:45 UTC, VivekV95 commented on app/src/main/res/layout/fragment_videos.xml
> +    <com.trx.consumer.common.CommonHudView
Can remove this, don't think this screen will need a hud

2021-05-17 22:00 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/params/VideoParamsModel.kt
> +data class VideoParamsModel(
The first video in the list can be used for the main section, and the other videos can be used for the adapter

2021-05-17 22:04 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/videos/VideosFragment.kt
> +            lblSummary.text = it.trainer.bio
`VideoModel` should have a property `description` that we can add to it and use here

2021-05-17 22:06 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/videos/VideosFragment.kt
> +            lblSummary.text = it.trainer.bio
Nevermind on the above, we can handle this in a consolidation task

2021-05-17 22:09 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/params/VideoParamsModel.kt
> +data class VideoParamsModel(
Don't need the extra params model, can just send `WorkoutModel` directly

2021-05-17 22:10 UTC, VivekV95 requested changes
Left a few comments

2021-05-18 17:33 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_videos.xml
> +                    android:backgroundTint="@color/white"
Completed.

2021-05-18 17:33 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_videos.xml
> +                    android:layout_width="match_parent"
Completed.

2021-05-18 17:33 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_videos.xml
> +                    android:id="@+id/btnTrainerProfile"
Completed.

2021-05-18 17:33 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_videos.xml
> +    <com.trx.consumer.common.CommonHudView
Completed.

2021-05-18 17:34 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/models/params/VideoParamsModel.kt
> +data class VideoParamsModel(
i removed VideoParamsModel and use WorkoutModel directly as you said.

2021-05-18 17:35 UTC, halilyesilyurt commented
changed pr images and demo.

2021-05-18 17:35 UTC, halilyesilyurt commented
changed base branch to develop.

2021-05-18 22:53 UTC, VivekV95 submitted a review, later dismissed

2021-05-19 00:22 UTC, onodude approved these changes

2021-05-19 00:22 UTC, merged