TCM-276 | Build dummy Filter screen
hyfn/trx-consumer-android pull request #37
Opened 2021-05-17 18:48 UTC by devender197

## Description

### Summary

- [ ] Dummy videos filter screen and view model is created
- [ ] All related models and classes are created.

### Issue

[TCM-276](https://hyfnla.atlassian.net/browse/TCM-276)

### Video/Screenshot

https://user-images.githubusercontent.com/24737954/118540693-acfe5280-b705-11eb-8222-c85647114efd.mov

#ScreenShot

![Screenshot_1621277278](https://user-images.githubusercontent.com/24737954/118540764-bedff580-b705-11eb-9b08-aa5698752249.png)

2021-05-17 23:00 UTC, VivekV95 commented on app/src/main/res/layout/fragment_filters.xml
> +<com.trx.consumer.common.CommonView xmlns:android="http://schemas.android.com/apk/res/android"
This file should be `fragment_filter` right? `fragment_filters` would be for `FiltersFragment`

2021-05-17 23:07 UTC, VivekV95 commented on app/src/main/res/layout/fragment_filters.xml
> +<com.trx.consumer.common.CommonView xmlns:android="http://schemas.android.com/apk/res/android"
Unless we're re-using it

2021-05-17 23:09 UTC, devender197 commented on app/src/main/res/layout/fragment_filters.xml
> +<com.trx.consumer.common.CommonView xmlns:android="http://schemas.android.com/apk/res/android"
[Done](https://github.com/hyfn/trx-consumer-android/pull/37/commits/a48e0566ed7f6f57e5a4d6d59e9e7403b1529dfd)

2021-05-17 23:34 UTC, VivekV95 commented on app/src/main/res/layout/row_video_filter.xml
> +    <com.trx.consumer.common.CommonImageButton
According to [design](https://www.figma.com/file/wMfhxL9w3KOw6okQJtt1OD/All-Screens-(v1.0.0)?node-id=2636%3A2), looks like we need an additional label to display the selected filter

2021-05-17 23:34 UTC, VivekV95 commented on app/src/main/res/values/strings.xml
> +    <string name="filter_empty_list_label">There are no filter</string>
"filter" -> "filters"

2021-05-17 23:36 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/filter/VideoFilterAdapter.kt
> +       //TO-DO
Let's mark as `//TODO:` so that it's detected by AS

2021-05-17 23:37 UTC, VivekV95 requested changes
Couple comments, looking good otherwise

2021-05-18 01:35 UTC, devender197 commented on app/src/main/res/values/strings.xml
> +    <string name="filter_empty_list_label">There are no filter</string>
[Done](https://github.com/hyfn/trx-consumer-android/pull/37/files#diff-5e01f7d37a66e4ca03deefc205d8e7008661cdd0284a05aaba1858e6b7bf9103R165)

2021-05-18 01:37 UTC, devender197 commented on app/src/main/res/layout/row_video_filter.xml
> +    <com.trx.consumer.common.CommonImageButton
Actually, we have multiple options for filter and user can select all options. So once we will start working on option screen. We can discuss, what to show selected filter label

2021-05-18 01:41 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/filter/VideoFilterAdapter.kt
> +       //TO-DO
[Done](https://github.com/hyfn/trx-consumer-android/pull/37/commits/5cd234ecd2fe8a67f104c9c01592cf1e5028bb92)

2021-05-18 02:16 UTC, VivekV95 commented on app/src/main/res/values/strings.xml
> +    <string name="filter_empty_list_label">There are no filter</string>
I meant the string for `filter_empty_list_label` should be "There are no filters", sorry should've been more specific

2021-05-18 02:17 UTC, VivekV95 commented on app/src/main/res/values/strings.xml
> +    <string name="filter_empty_list_label">There are no filter</string>
`filter` for the string names makes sense

2021-05-18 17:18 UTC, VivekV95 requested changes
Just the "filters" comment above + conflicts and should be good to go

2021-05-18 19:14 UTC, devender197 commented on app/src/main/res/values/strings.xml
> +    <string name="filter_empty_list_label">There are no filter</string>
[Done](https://github.com/hyfn/trx-consumer-android/pull/37/files#diff-5e01f7d37a66e4ca03deefc205d8e7008661cdd0284a05aaba1858e6b7bf9103R171)

2021-05-18 19:19 UTC, devender197 commented
@onodude @VivekV95 for the review. Please let me know any further changes required. @onodude I have inserted the label for selected filter and will handle this on filter options screen. Thank you.

2021-05-18 23:11 UTC, VivekV95 approved these changes

2021-05-19 00:07 UTC, onodude approved these changes

2021-05-19 00:07 UTC, merged