TCM-278  | Build dummy filters screen
hyfn/trx-consumer-android pull request #40
Opened 2021-05-18 01:27 UTC by devender197

## Description

### Summary

- [ ] Filter options layout, view model and all required classes added

### Issue

[TCM-278](https://hyfnla.atlassian.net/browse/TCM-278)

### Video/Screenshot

| Selected | UnSelected |
|---|---|
|![Screenshot_1621301237](https://user-images.githubusercontent.com/24737954/118576519-8825d180-b73d-11eb-8f2b-5997c6ed79ce.png)|![Screenshot_1621301231](https://user-images.githubusercontent.com/24737954/118576533-8f4cdf80-b73d-11eb-8fb9-ad3ffe844c1e.png)|

2021-05-19 01:51 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/update/UpdateFragment.kt
> +            //ivPassword.setInputViewListener(viewModel)
I don't how but after certain merge these commented block is giving error

2021-05-19 20:50 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/filter/FiltersFragment.kt
> +    override fun onSaveInstanceState(outState: Bundle) {
Is this needed?

2021-05-19 20:54 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/FilterModel.kt
>      val id: Int = 0,
If we're using the title as the identifier for `equals` and `hashCode`, do we still need `id`?

2021-05-19 21:48 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/filter/FiltersViewModel.kt
> +        params?.list?.forEach { filter -> filter.values.forEach { option -> option.isSelected = true } }
We can just initialize `params` as a `FilterParamsModel` so that we don't have to deal with the nullable. It initializes with an empty list anyways so should be safe.

2021-05-19 21:48 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/filter/FiltersViewModel.kt
> +        params?.list?.forEach { filter -> filter.values.forEach { option -> option.isSelected = true } }
Exceeds character limit

2021-05-19 21:51 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/filter/FiltersViewModel.kt
> +        eventTapFilter.postValue(params?.apply { selectedModel = model })
Let's do 
```
   params.selectedModel = model
   eventTapFilter.postValue(params)
```
to match patterns we use elsewhere

2021-05-19 21:56 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/filteroptions/FilterOptionViewModel.kt
> +        this.model?.values?.find { model == it }?.isSelected = model.isSelected
Nice `find` (pun inteded), didn't know about this

2021-05-19 21:59 UTC, VivekV95 commented on app/src/main/res/layout/fragment_options.xml
> +    <com.trx.consumer.common.CommonLabel
Would we even be able to view this Fragment if there are no filter options for a filter?

2021-05-19 22:02 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/filter/FiltersViewHolder.kt
> +            } else if (count > 1 && count < model.values.size) {
Feel like just `count > 1` is sufficient, not sure why we need the upper limit

2021-05-19 22:03 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/filter/FiltersViewHolder.kt
> +                model.values.firstOrNull { it.isSelected }?.let { it -> it.name }
`model.values.find { it.isSelected }?.name`

2021-05-19 22:04 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/filteroptions/FilterOptionsAdapter.kt
> +class FilterOptionsAdapter(private val listener: FilterOptionsListener, scopeProvider: () -> CoroutineScope) :
Exceeds character limit

2021-05-19 22:07 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/filteroptions/FilterOptionsFragment.kt
> +        if (model.values.isNotEmpty()) adapter?.update(model.values)
Related to [this](https://github.com/hyfn/trx-consumer-android/pull/40/files#r635612682), should we even show the user a filter that has no filter options for it?

2021-05-19 22:13 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/filteroptions/FilterOptionsViewHolder.kt
> +    private fun setBackgroundColor(isSelected: Boolean) {
Can cut down on most of this:
```
  lblTitle.textColor(if (isSelected) R.color.white else R.color.black)
  viewFilter.bgColor(if (isSelected) R.color.black else R.color.greyLightExtra)
````
Also don't really need the extra function as it's just a couple lines of code

2021-05-19 22:17 UTC, VivekV95 commented on app/src/main/res/layout/fragment_options.xml
> +<com.trx.consumer.common.CommonView xmlns:android="http://schemas.android.com/apk/res/android"
Let's call this file `fragment_filter_options` to match `FilterOptionsFragment`

2021-05-19 22:22 UTC, VivekV95 requested changes
Looking really good, left a few comments. Also, couple things:
1. We initially planned on calling these `FilterFragment` and `FiltersFragment` instead of `FiltersFragment` and `FilterOptionsFragment`. I'm fine with either, @onodude just conforming what we want to go with.
2. Coming into `FiltersFragment`, all options are selected by default so we'll want to show the selected labels on first entry 

https://user-images.githubusercontent.com/39810816/118892602-c6023180-b8c6-11eb-998e-70f7c06127ff.mov

2021-05-19 22:39 UTC, VivekV95 commented
Confirmed with @onodude
1. Let's keep `FilterOptionsFragment` but rename `FiltersFragment` to `FilterFragment` along with corresponding view model and layout file
2. If a filter has no filter options available, it shouldn't appear in the list of filters in `FilterFragment`

2021-05-19 23:06 UTC, devender197 commented on app/src/main/java/com/trx/consumer/models/common/FilterModel.kt
>      val id: Int = 0,
We are still waiting for the endpoint. Once we will get it, we will made the necessary changes.

2021-05-19 23:17 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/filter/FiltersViewHolder.kt
> +            } else if (count > 1 && count < model.values.size) {
initially, all the filter options will be selected. So in that case, we don't need to show selected filter on the Filters row. Hence, count>1 and less than size of the values list is appropriate.

2021-05-19 23:20 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/filter/FiltersViewHolder.kt
> +                model.values.firstOrNull { it.isSelected }?.let { it -> it.name }
Yes, you are right. we are already checking the count before hand. So this check is not required. But It would be better to play safe with `firstOrNull` than the exception with `first`.

2021-05-19 23:22 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/filteroptions/FilterOptionsFragment.kt
> +        if (model.values.isNotEmpty()) adapter?.update(model.values)
I don't trust dynamic api endpoints. It should be better to have checks at our end.

2021-05-20 00:42 UTC, devender197 commented on app/src/main/res/layout/fragment_options.xml
> +<com.trx.consumer.common.CommonView xmlns:android="http://schemas.android.com/apk/res/android"
[Done](https://github.com/hyfn/trx-consumer-android/pull/40/commits/8259317b1d1cec665c41e153fca0df081fd7c0f5)

2021-05-20 00:50 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/filteroptions/FilterOptionsViewHolder.kt
> +    private fun setBackgroundColor(isSelected: Boolean) {
[Done](https://github.com/hyfn/trx-consumer-android/pull/40/commits/c97d50334b7957e9685b5b40c1ce31a95c508b58)

2021-05-20 01:01 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/filteroptions/FilterOptionViewModel.kt
> +        this.model?.values?.find { model == it }?.isSelected = model.isSelected
Can I have more light on it? is there anything wrong ?

2021-05-20 01:14 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/filteroptions/FilterOptionsAdapter.kt
> +class FilterOptionsAdapter(private val listener: FilterOptionsListener, scopeProvider: () -> CoroutineScope) :
[Done](https://github.com/hyfn/trx-consumer-android/pull/40/commits/578312901fe3436a2eb5664ab9c29920148112c3#diff-21e3e81c919b9ad961585a6dcd6f51c1428825e43260f95ca492171cacdfc070R13)

2021-05-20 01:15 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/filter/FiltersViewHolder.kt
> +                model.values.firstOrNull { it.isSelected }?.let { it -> it.name }
[Done](https://github.com/hyfn/trx-consumer-android/pull/40/commits/578312901fe3436a2eb5664ab9c29920148112c3#diff-89c81cb6b22806ab1d229b302a4922b0bd282b863ccd04d9634906eb4f1b0cb0R21)

2021-05-20 01:15 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/filter/FiltersViewModel.kt
> +        eventTapFilter.postValue(params?.apply { selectedModel = model })
[Done](https://github.com/hyfn/trx-consumer-android/pull/40/commits/578312901fe3436a2eb5664ab9c29920148112c3#diff-0e2050d257b016a972897985384f756f69829fd4e08b851e23b12269d82017faR49)

2021-05-20 01:16 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/filter/FiltersViewModel.kt
> +        params?.list?.forEach { filter -> filter.values.forEach { option -> option.isSelected = true } }
[Done](https://github.com/hyfn/trx-consumer-android/pull/40/commits/578312901fe3436a2eb5664ab9c29920148112c3#diff-0e2050d257b016a972897985384f756f69829fd4e08b851e23b12269d82017faR34)

2021-05-20 01:17 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/filter/FiltersFragment.kt
> +    override fun onSaveInstanceState(outState: Bundle) {
Thank you forgot to remove it. [Removed](https://github.com/hyfn/trx-consumer-android/pull/40/commits/578312901fe3436a2eb5664ab9c29920148112c3#diff-27f9809ac68f7b5a39af86e1245b6ef88f0ecaf62b3752cdb0d475dd01178b2eL54)

2021-05-20 16:45 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/filteroptions/FilterOptionViewModel.kt
> +        this.model?.values?.find { model == it }?.isSelected = model.isSelected
No issues, didn't know `find` was a thing, really convenient

2021-05-20 16:59 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/filteroptions/FilterOptionsFragment.kt
> +        if (model.values.isNotEmpty()) adapter?.update(model.values)
For followup/connect task: We're not making the api call in `FilterOptions`, so in `Filters` we would already know if a filter has options or not, so the question was do we want that filter to even appear in the list if it has no options?

2021-05-20 18:18 UTC, VivekV95 approved these changes

2021-05-20 19:48 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/filter/FiltersViewHolder.kt
> +            } else if (count > 1 && count < model.values.size) {
@VivekV95 I confirmed with @onodude about this functionality. So I think it is good for now and we can discuss this later.

2021-05-20 21:31 UTC, VivekV95 submitted a review, later dismissed

2021-05-20 22:10 UTC, onodude commented on app/src/main/java/com/trx/consumer/models/common/FilterOptionModel.kt
> +class FilterOptionModel(val name: String, var isSelected: Boolean = true) : Parcelable {
please use `value` instead of `name`

2021-05-20 22:10 UTC, onodude commented on app/src/main/java/com/trx/consumer/models/common/FilterModel.kt
>      val id: Int = 0,
please use `identifier: String` instead of `id: Int`

2021-05-20 22:11 UTC, onodude commented on app/src/main/java/com/trx/consumer/models/common/FilterOptionModel.kt
> +class FilterOptionModel(val name: String, var isSelected: Boolean = true) : Parcelable {
should be called `FilterOptionsModel`

2021-05-21 02:23 UTC, devender197 commented on app/src/main/java/com/trx/consumer/models/common/FilterOptionModel.kt
> +class FilterOptionModel(val name: String, var isSelected: Boolean = true) : Parcelable {
[Done](https://github.com/hyfn/trx-consumer-android/pull/40/commits/3fea88cdafc6433841d73cf635ddac9eec341d27#diff-6f09250e1c1e10c81067402fd21a2b923b39a69e3588f8dafceb245bdd9659a9R7)

2021-05-21 02:24 UTC, devender197 commented on app/src/main/java/com/trx/consumer/models/common/FilterModel.kt
>      val id: Int = 0,
[Done](https://github.com/hyfn/trx-consumer-android/pull/40/commits/3fea88cdafc6433841d73cf635ddac9eec341d27#diff-9439500f10707d685b15b6947fc3beaab350a6096120af69001e08bcf455f876R8)

2021-05-21 02:24 UTC, devender197 commented on app/src/main/java/com/trx/consumer/models/common/FilterOptionModel.kt
> +class FilterOptionModel(val name: String, var isSelected: Boolean = true) : Parcelable {
[Done](https://github.com/hyfn/trx-consumer-android/pull/40/commits/3fea88cdafc6433841d73cf635ddac9eec341d27#diff-6f09250e1c1e10c81067402fd21a2b923b39a69e3588f8dafceb245bdd9659a9R7)

2021-05-21 05:03 UTC, onodude approved these changes

2021-05-21 05:03 UTC, merged