TCM-297 | Connect `AddCard` and Stripe backend
hyfn/trx-consumer-android pull request #44
Opened 2021-05-18 23:10 UTC by vespertineSiren

## Description

### Summary

In Progress

### Issue

In Progress

### Video/Screenshot

In Progress

2021-05-19 21:28 UTC, devender197 commented on app/src/main/java/com/trx/consumer/managers/BackendManager.kt
> +        return call(RequestModel(endpoint = EndpointModel.PAYMENT_ADD, path, params = null))
is endpoint on line 77 correct? shouldn't be PAYMENT_DELETE ?

2021-05-19 21:30 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/managers/BackendManager.kt
> +        return call(RequestModel(endpoint = EndpointModel.PAYMENT_ADD, path, params = null))
Good catch. Will change.

2021-05-19 22:44 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/CardModel.kt
> +            HashMap<String, Any>().apply {
Can clean this up a bit
```
hashMapOf(
                "type" to "card",
                "card" to hashMapOf(
                    "number" to number,
                    "exp_month" to expMonth,
                    "exp_year" to expYear,
                    "cvc" to securityCode
                )
            )

2021-05-19 22:50 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/addcard/AddCardFragment.kt
> +        viewBinding.apply {
Can just do 
```
 viewBinding.btnSave.apply {
            isEnabled = enabled
            bgColor(if (enabled) R.color.black else R.color.greyDark)
        }

2021-05-19 22:52 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/addcard/AddCardFragment.kt
> +    private val handleSaveSuccess = Observer<Void> {
Let's use string resources for what's passed into `create` here and in `handleSaveError`

2021-05-19 23:05 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/addcard/AddCardViewModel.kt
> +                card?.let {
We can just show a hud before this line and hide it in line `140` so we don't have to show and hide in multiple places within the same flow

2021-05-19 23:14 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/addcard/AddCardViewModel.kt
> +                            eventSaveError.postValue("There is an error with the expiration")
Not sure this error message is appropriate here

2021-05-19 23:15 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/addcard/AddCardViewModel.kt
> +                    eventSaveError.postValue("There is an error with the expiration")
Same here

2021-05-19 23:17 UTC, VivekV95 commented on app/src/main/res/drawable/ic_btn_close_black.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
We don't need a separate drawable for this, can just use the white icon and set a `tint` in the image view

2021-05-19 23:21 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/addcard/AddCardViewModel.kt
> +                                if (deleteResponse.isSuccess) {
Will the `deleteResponse` be successful if there's no current card?

2021-05-19 23:21 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/stripe/StripeBackendManager.kt
> +class StripeBackendManager(
Can fit on one line

2021-05-19 23:26 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/views/input/InputViewState.kt
> +            val inputMonth = inputDate.get(Calendar.MONTH) + 1
Not sure about the `+1` addition, if both the current month and exp month are January for ex, `inputMonth` would be `1` because of the `+1`, but `currentMonth` would be `0`. Am I missing something?

2021-05-19 23:29 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/addcard/AddCardViewModel.kt
> +            backendManager.user().let {
Should we show an error if the `user` call fails?

2021-05-19 23:30 UTC, VivekV95 requested changes
Left some thoughts

2021-05-19 23:33 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/CardModel.kt
> +            HashMap<String, Any>().apply {
I did it that way in an early commit and it still wouldnt send .This can probably removed all together.

2021-05-19 23:34 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/addcard/AddCardFragment.kt
> +    private val handleSaveSuccess = Observer<Void> {
This is what iOS used so and I'm following parity with the push to match them.

2021-05-19 23:36 UTC, vespertineSiren commented on app/src/main/res/drawable/ic_btn_close_black.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
I'm aware of the tint but following iOS parity here

2021-05-19 23:37 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/addcard/AddCardFragment.kt
> +        viewBinding.apply {
Noted. Probably back when I was handling another view here. Request makes sense.

2021-05-20 00:03 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/addcard/AddCardFragment.kt
> +    private val handleSaveSuccess = Observer<Void> {
We've already decided to break parity with this in other places, from what I can tell we only hardcode strings in places where we don't have access to `context`

2021-05-20 00:05 UTC, VivekV95 commented on app/src/main/res/drawable/ic_btn_close_black.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
It's fine to break parity here IMO as by extension, if we needed 20 colors we'd end up making 20 files

2021-05-20 19:52 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/addcard/AddCardFragment.kt
> +    private val handleSaveSuccess = Observer<Void> {
This isn't possible. The error on line 135 is catching the reason for the exception from the failed Stripe backend call.

2021-05-20 19:55 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/addcard/AddCardViewModel.kt
> +                card?.let {
Makes sense. WIll make change.

2021-05-20 20:06 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/addcard/AddCardViewModel.kt
> +            backendManager.user().let {
I don't believe so. There is no guest mode for this app I believe.

2021-05-20 20:07 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/CardModel.kt
> +            HashMap<String, Any>().apply {
Here we are https://github.com/hyfn/trx-consumer-android/pull/44/commits/a3dbbbe1d0d50f68022432f4d2cb2dc82ced73f4

2021-05-20 20:09 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/addcard/AddCardFragment.kt
> +        viewBinding.apply {
Here you are https://github.com/hyfn/trx-consumer-android/pull/44/commits/c1852776396b74fc95d756f834cf48a4e44e5fef

2021-05-20 20:10 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/stripe/StripeBackendManager.kt
> +class StripeBackendManager(
Here we are: https://github.com/hyfn/trx-consumer-android/pull/44/commits/d368edbaaf958cc85c4e6f3ed9000f5728c5acea

2021-05-20 20:10 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/views/input/InputViewState.kt
> +            val inputMonth = inputDate.get(Calendar.MONTH) + 1
Here we are: https://github.com/hyfn/trx-consumer-android/pull/44/commits/d234e5d137ff1f60fe79f2b8b2fdd20f5cce4b10

2021-05-20 20:13 UTC, vespertineSiren commented on app/src/main/res/drawable/ic_btn_close_black.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Here we are: https://github.com/hyfn/trx-consumer-android/pull/44/commits/43ceac30cb0e4f1335a1c9dbe622b03f9d58556e

2021-05-20 21:37 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/addcard/AddCardViewModel.kt
> +                            eventSaveError.postValue("There is an error with the expiration")
Should be handled in recent commits.

2021-05-20 21:37 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/addcard/AddCardViewModel.kt
> +                    eventSaveError.postValue("There is an error with the expiration")
Should be handled in recent commmits.

2021-05-21 05:07 UTC, onodude commented on app/src/main/java/com/trx/consumer/stripe/StripeBackendManager.kt
> +    suspend fun createStripePaymentMethod(card: CardModel): String? {
`createPaymentMethod` 😬

2021-05-21 05:08 UTC, onodude submitted a review, later dismissed
thanks @vespertineSiren

2021-05-21 07:32 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/stripe/StripeBackendManager.kt
> +    suspend fun createStripePaymentMethod(card: CardModel): String? {
Here ya go: https://github.com/hyfn/trx-consumer-android/pull/44/commits/97de3010f8687dd389505d4e5e06b7207592661b

2021-05-21 16:04 UTC, onodude commented on app/src/main/java/com/trx/consumer/screens/addcard/AddCardFragment.kt
> +            //  TODO: Add when showSupportEmail() is imported.
we can start supporting: `digital@trxtraining.com`

2021-05-21 17:02 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/addcard/AddCardFragment.kt
> +            //  TODO: Add when showSupportEmail() is imported.
Sure I can add it into this PR.

2021-05-21 23:25 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/addcard/AddCardFragment.kt
> +            //  TODO: Add when showSupportEmail() is imported.
Demo available in description: https://github.com/hyfn/trx-consumer-android/pull/44/commits/df03556894b019fc021a4b4a8047975892a0eb21

2021-05-22 03:06 UTC, onodude approved these changes

2021-05-22 03:06 UTC, merged