TCM-295 | Connect `Plans`
hyfn/trx-consumer-android pull request #52
Opened 2021-05-21 16:29 UTC by vespertineSiren

## Description

### Summary

WIP

### Issue

(TCM-295)[https://hyfnla.atlassian.net/browse/TCM-295]

### Video/Screenshot

WIP

2021-05-22 00:51 UTC, devender197 commented on app/src/main/res/layout/fragment_plans.xml
> +                    android:fontFamily="@font/atcarquette_regular"
This text is bold in iOS, can please compare it [here](https://github.com/hyfn/trx-consumer-ios/blob/develop/TRX-Consumer/Screens/Plans/PlansView.swift)

2021-05-22 00:56 UTC, devender197 commented on app/src/main/res/layout/fragment_plans.xml
> +                    android:fontFamily="@font/atcarquette_regular"
textSize and textStyle are different than iOS. Please check [here](https://github.com/hyfn/trx-consumer-ios/blob/develop/TRX-Consumer/Screens/Plans/PlansView.swift)

2021-05-22 02:52 UTC, vespertineSiren commented on app/src/main/res/layout/fragment_plans.xml
> +                    android:fontFamily="@font/atcarquette_regular"
I looked at this and fixed a few things. Did not change the size from `11sp` to `12sp` because of the small size warning: https://github.com/hyfn/trx-consumer-android/pull/52/commits/7e6ddf160601b9e9447768a111c2e5da0b1ad6cd

2021-05-22 02:52 UTC, vespertineSiren commented on app/src/main/res/layout/fragment_plans.xml
> +                    android:fontFamily="@font/atcarquette_regular"
I looked at this and fixed a few things. Did not change the size from `11sp` to `12sp` because of the small size warning: https://github.com/hyfn/trx-consumer-android/pull/52/commits/7e6ddf160601b9e9447768a111c2e5da0b1ad6cd

2021-05-22 03:07 UTC, onodude commented
@vespertineSiren would you be able to pull the latest changes and resolve the conflicts

2021-05-22 05:26 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/extensions/DoubleExtensions.kt
> +    return "$" + decimalFormat.format(this)
Can use interpolation here

2021-05-22 05:27 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/managers/BackendManager.kt
> +        return call(RequestModel(endpoint = EndpointModel.SUBSCRIPTION_ADD, path = path, params = params))
Couple lines exceeding character limit

2021-05-22 05:36 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/SubscriptionsModel.kt
> +                free = try {
Can save a few lines of code by using `opt` for `free` and `plans`, which we do in other places anyways:
```
 free =  jsonObject.optJSONObject("free")?.let {
                    SubscriptionModel.parse(it)
                } ?: SubscriptionModel(),

2021-05-22 05:37 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/SubscriptionsModel.kt
> +                free = try {
If we want to keep the try-catch, logging the exception would be beneficial

2021-05-22 05:47 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/SubscriptionModel.kt
> +                valueProps = jsonObject.optJSONArray("valueProps")?.let { jsonArray ->
Can just do `  valueProps = jsonObject.optJSONArray("valueProps").map()`

2021-05-22 05:57 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/UserModel.kt
> +                        //  TODO: Remove after testing.
Looks like we can remove this now

2021-05-22 05:58 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/UserSubscriptionModel.kt
> +                cancelAtPeriodEnd = jsonObject.optBoolean("subscription.cancel_at_period_end", false),
Neither need the default values passed as those are already the default values used by `optBoolean` and `optDouble`

2021-05-22 06:11 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/responses/PlansResponseModel.kt
> +            val list = subscription.plans.map { it.plan }.toMutableList()
Can pull this out before the `return` statement so that we can just do `} ?: list` in line 22

2021-05-22 06:15 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/plans/PlansViewModel.kt
> +            backendManager.user().let {
Don't think we need this extra scope, can just do 
```
 backendManager.user()
 cacheManager.user()?.let { user ->

2021-05-22 06:18 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/plans/PlansViewModel.kt
> +                    (user.subscription != null).let { value ->
Let's pull this out into a `val` for readability (I think we generally limit `let` to null check usages), something like
```
         val hasSubscription = user.subscription != null
         eventLoadCanCancel.postValue(hasSubscription)

2021-05-22 06:19 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/plans/PlansViewModel.kt
> +                if (response.isSuccess) {
Guessing we'll want to show an error if this isn't successful

2021-05-22 06:22 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/plans/PlansViewModel.kt
> +                        eventLoadError.postValue("There was no error")
"no error" -> "an error"

2021-05-22 06:23 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/plans/PlansViewModel.kt
> +                        eventLoadError.postValue("There was no error")
Maybe we can use and/or modify our `genericErrorMessage` in `ResponseModel`

2021-05-22 06:26 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/plans/PlansViewModel.kt
> +                if (user.subscriptionText != "Pay As You Go") {
Would be much safer to compare it to`kSubscriptionNamePay`

2021-05-22 06:29 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/plans/list/PlansViewHolder.kt
> +        item.title?.let { lblTitle.text = it }
Let's initialize `PlanModel`'s string properties as non-null empty strings so we don't have to deal with all the nullables here

2021-05-22 06:30 UTC, VivekV95 requested changes
Left some initial thoughts

2021-05-22 22:39 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/extensions/DoubleExtensions.kt
> +    return "$" + decimalFormat.format(this)
Here we go: https://github.com/hyfn/trx-consumer-android/pull/52/commits/634f65d988476891827f27cad96686466bebaf6b

2021-05-22 22:43 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/managers/BackendManager.kt
> +        return call(RequestModel(endpoint = EndpointModel.SUBSCRIPTION_ADD, path = path, params = params))
Here we go: https://github.com/hyfn/trx-consumer-android/pull/52/commits/1c201259e9c9343902c8ccb49f93c851617b96d4

2021-05-22 22:52 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/SubscriptionsModel.kt
> +                free = try {
Im not sure why I kept this in. I probably didnt want it to fail parsing during `map`.

2021-05-22 22:54 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/SubscriptionsModel.kt
> +                free = try {
I'll keep the first suggestion and add a LogManager call for plans. https://github.com/hyfn/trx-consumer-android/pull/52/commits/1c6075b3572713ecab65a0388e0499fc077731c1

2021-05-22 23:01 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/SubscriptionModel.kt
> +                valueProps = jsonObject.optJSONArray("valueProps")?.let { jsonArray ->
Didn't realized we had this extension. Ended up using it: https://github.com/hyfn/trx-consumer-android/pull/52/commits/f51bec807879ec8057b2032477d3bc7a89cdf00e

2021-05-22 23:05 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/UserModel.kt
> +                        //  TODO: Remove after testing.
Here we are. https://github.com/hyfn/trx-consumer-android/pull/52/commits/c0cf65d37628e2c473176bbf1a26f5138418ce2b

2021-05-22 23:07 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/responses/PlansResponseModel.kt
> +            val list = subscription.plans.map { it.plan }.toMutableList()
I think this is what you meant 
```
    fun plans(subscriptionText: String?): List<PlanModel> =
        subscriptionText?.let { text ->
            val list = subscription.plans.map { it.plan }.toMutableList()
            list.indexOfFirst { it.title == text }.let { index ->
                if (index != -1) {
                    list.removeAt(index).let { planModel ->
                        planModel.primaryState = PlansViewState.CURRENT
                        list.add(0, planModel)
                    }
                }
            }
            list
        } ?: subscription.plans.map { it.plan }
```

2021-05-22 23:10 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/plans/PlansViewModel.kt
> +            backendManager.user().let {
I think I tried to emulate what they did on iOS so I structured it this way. Will change it either way.

2021-05-22 23:16 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/plans/PlansViewModel.kt
> +                    (user.subscription != null).let { value ->
I ended up going with this below for brevity. 
`      eventLoadCanCancel.postValue(user.subscription != null)`

2021-05-22 23:22 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/plans/PlansViewModel.kt
> +                if (response.isSuccess) {
Doesn't seem to be the case on iOS

2021-05-22 23:24 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/plans/PlansViewModel.kt
> +                        eventLoadError.postValue("There was no error")
Ill just use the genericErrorMessage.

2021-05-22 23:25 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/plans/PlansViewModel.kt
> +                if (user.subscriptionText != "Pay As You Go") {
Changed it to that.

2021-05-22 23:40 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/responses/PlansResponseModel.kt
> +            val list = subscription.plans.map { it.plan }.toMutableList()
Requested Change: Refactor plans function PlansResponseModel https://github.com/hyfn/trx-consumer-android/pull/52/commits/01f724a60ce805d1399a85f9d9c6dc228a0812e0

2021-05-22 23:42 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/UserSubscriptionModel.kt
> +                cancelAtPeriodEnd = jsonObject.optBoolean("subscription.cancel_at_period_end", false),
Here we go: https://github.com/hyfn/trx-consumer-android/pull/52/commits/6bf8ecd851fd88a02303cd90ef5db9511e2f1400

2021-05-22 23:42 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/plans/PlansViewModel.kt
> +            backendManager.user().let {
Here we go: https://github.com/hyfn/trx-consumer-android/pull/52/commits/c52bc0999a854ac085a8bc363d6e6e51d92c5552

2021-05-22 23:42 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/plans/PlansViewModel.kt
> +                    (user.subscription != null).let { value ->
Here we go: https://github.com/hyfn/trx-consumer-android/pull/52/commits/c52bc0999a854ac085a8bc363d6e6e51d92c5552

2021-05-22 23:42 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/plans/PlansViewModel.kt
> +                        eventLoadError.postValue("There was no error")
Here we go: https://github.com/hyfn/trx-consumer-android/pull/52/commits/c52bc0999a854ac085a8bc363d6e6e51d92c5552

2021-05-22 23:43 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/plans/PlansViewModel.kt
> +                if (user.subscriptionText != "Pay As You Go") {
Here we go: https://github.com/hyfn/trx-consumer-android/pull/52/commits/c52bc0999a854ac085a8bc363d6e6e51d92c5552

2021-05-22 23:43 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/plans/list/PlansViewHolder.kt
> +        item.title?.let { lblTitle.text = it }
Here we go: https://github.com/hyfn/trx-consumer-android/pull/52/commits/c52bc0999a854ac085a8bc363d6e6e51d92c5552

2021-05-23 00:40 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/plans/PlansViewModel.kt
> +                eventLoadConfirmSubscription.postValue(model)
Not sure about the logic here, based on what iOS is doing, looks like `eventLoadConfirmationSubscription` should always be called _unless_ `eventLoadCancelSubscription` is called. This would be the most direct translation of what iOS is doing:
```
  cacheManager.user()?.let { user ->
                if (user.subscriptionText != UserModel.kSubscriptionNamePay) {
                    eventLoadCancelSubscription.postValue(user.subscription)
                    return@launch
                }
            }
            eventLoadConfirmSubscription.postValue(model)

2021-05-23 00:47 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/plans/PlansViewModel.kt
> +    private var userModel: UserModel? = null
Not sure we need this, looks like the only place we need the user is in `doLoadPlans`

2021-05-23 00:49 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/plans/PlansFragment.kt
> +        val message = value?.let {
I think we briefly discussed this, what's stopping us from using string resources here and in `handleLoadConfirmSubscription`?

2021-05-23 00:50 UTC, VivekV95 commented on app/src/main/res/layout/fragment_plans.xml
> +        <com.trx.consumer.common.CommonHudView
Hud's being displayed at the top of the screen instead of center

2021-05-23 00:52 UTC, VivekV95 commented on app/src/main/res/layout/fragment_plans.xml
> +            android:id="@+id/lblTitle"
Isn't aligned with the text in the cells, don't think it needs the `padding`

2021-05-23 00:52 UTC, VivekV95 requested changes
Few things I missed during the first run through

2021-05-23 01:14 UTC, vespertineSiren commented on app/src/main/res/layout/fragment_plans.xml
> +            android:id="@+id/lblTitle"
Thats the changes that @onodude requested last night. I think its fine but he can chime in on this.

2021-05-23 01:16 UTC, vespertineSiren commented on app/src/main/res/layout/fragment_plans.xml
> +        <com.trx.consumer.common.CommonHudView
I think because of the root view. If the root were a contraintlayout with the children being a commonview and that scroller, that should fix the issue.

2021-05-23 01:18 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/plans/PlansFragment.kt
> +        val message = value?.let {
iOS presents you with a `Cancel` string and a numerical cost to it. I assume that we have to follow parity with them until we change how the AlertFragment/Model presents data.

2021-05-23 01:19 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/plans/PlansViewModel.kt
> +    private var userModel: UserModel? = null
I did it for line 63. I guess I can make userModel local just to that function, I suppose.

2021-05-23 01:57 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/plans/PlansFragment.kt
> +        val message = value?.let {
I meant something like this:
```
<string name="plans_cancel_subscription_message"> Are you sure you want to cancel your %1$s subscription?</string>`
     val message = getString(R.string.plans_cancel_subscription_message, value)
        val model = AlertModel.create(title = "", message = message)

2021-05-23 18:58 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/plans/PlansViewModel.kt
> +                eventLoadConfirmSubscription.postValue(model)
Maybe I should just use the UserModel that I saved in the viewmodel. Lemme rework this.

2021-05-23 19:20 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/plans/PlansViewModel.kt
> +                eventLoadConfirmSubscription.postValue(model)
Wouldnt this make more sense?

```
    override fun doTapChoosePlan(model: PlanModel) {
        viewModelScope.launch {
            cacheManager.user()?.let { user ->
                if (userModel?.subscriptionText != UserModel.kSubscriptionNamePay) {
                    eventLoadCancelSubscription.postValue(user.subscription)
                }
            }
            eventLoadConfirmSubscription.postValue(model)
        }
    }
```

2021-05-23 19:21 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/plans/PlansViewModel.kt
> +                eventLoadConfirmSubscription.postValue(model)
Also going back to this, can't we just use the userModel here https://github.com/hyfn/trx-consumer-android/pull/52#discussion_r637468327 to do that subscriptionText check?

2021-05-23 20:44 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/plans/PlansViewModel.kt
> +                eventLoadConfirmSubscription.postValue(model)
Here we are: https://github.com/hyfn/trx-consumer-android/pull/52/commits/65eae9b5b6e22339e30a07e3a36b1720886ce800

2021-05-23 20:44 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/plans/PlansViewModel.kt
> +    private var userModel: UserModel? = null
Here we are: https://github.com/hyfn/trx-consumer-android/pull/52/commits/65eae9b5b6e22339e30a07e3a36b1720886ce800

2021-05-23 20:44 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/plans/PlansFragment.kt
> +        val message = value?.let {
Here we are: https://github.com/hyfn/trx-consumer-android/pull/52/commits/65eae9b5b6e22339e30a07e3a36b1720886ce800

2021-05-23 20:44 UTC, vespertineSiren commented on app/src/main/res/layout/fragment_plans.xml
> +        <com.trx.consumer.common.CommonHudView
Here we are: https://github.com/hyfn/trx-consumer-android/pull/52/commits/65eae9b5b6e22339e30a07e3a36b1720886ce800

2021-05-23 21:04 UTC, VivekV95 approved these changes

2021-05-23 22:09 UTC, onodude approved these changes
thanks!

2021-05-23 22:09 UTC, merged