TCM-290 | Connect `Email`
hyfn/trx-consumer-android pull request #59
Opened 2021-05-23 23:33 UTC by vespertineSiren

## Description

### Summary

Slight deviation from iOS since this isn't completed on their end. 
- Created backend calls for `Forgot` and `CODE` along with updating the `EmailViewState` and strings to reflect that. 
- Add helper function in InputView for specific styling in EmailFragment

### Issue

[TCM-290](https://hyfnla.atlassian.net/browse/TCM-290)

### Video/Screenshot

In Progress

2021-05-24 00:14 UTC, onodude commented on app/src/main/java/com/trx/consumer/managers/BackendManager.kt
> +        val path = EndpointModel.LOGIN.path
should probably be:
`val path = EndpointModel.FORGOT.path`

2021-05-24 00:15 UTC, onodude commented on app/src/main/java/com/trx/consumer/managers/BackendManager.kt
> +        )
this could be removed

2021-05-24 00:17 UTC, onodude commented on app/src/main/java/com/trx/consumer/screens/email/EmailViewModel.kt
> +        doCallSendEmail()
lets put the state check here and add `doCallForgot` for forgot and todo for the code case

2021-05-24 00:17 UTC, onodude requested changes
looks good @vespertineSiren couple of changes needed

2021-05-24 00:31 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/managers/BackendManager.kt
> +        val path = EndpointModel.LOGIN.path
ah. totally missed this. Probably leading to the handing.

2021-05-24 00:50 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/managers/BackendManager.kt
> +        val path = EndpointModel.LOGIN.path
Here you go: https://github.com/hyfn/trx-consumer-android/pull/59/commits/9e4f6364305810dae4e5b4eff91f21ddd221dff1

2021-05-24 00:50 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/managers/BackendManager.kt
> +        )
Done here: https://github.com/hyfn/trx-consumer-android/pull/59/commits/520c9e672d061f10ee78aa7c063f67ad5e453075

2021-05-24 00:50 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/email/EmailViewModel.kt
> +        doCallSendEmail()
Done here: https://github.com/hyfn/trx-consumer-android/pull/59/commits/520c9e672d061f10ee78aa7c063f67ad5e453075

2021-05-24 15:43 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/email/EmailFragment.kt
> +            NavigationManager.shared.dismiss(this, null)
Do we want to kick user out of this screen on an error? For ex. if they entered their email wrong and they need to enter it again, they'll need to re-enter the screen. Feel like it'd be better to do nothing here and just let the modal get dismissed.

2021-05-24 15:58 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/views/input/InputView.kt
> +    fun setEmailInputViewState(state: EmailViewState) {
Is this needed? Couldn't we just call the existing `setInputViewState`?

2021-05-24 15:59 UTC, VivekV95 commented on app/src/main/res/layout/fragment_email.xml
> +            android:id="@+id/viewHeader"
Let's auto-format this file

2021-05-24 16:06 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/email/EmailFragment.kt
> +            UtilityManager.shared.showSupportEmail(this)
Doesn't seem we're directing the user to the email app with enough info for it to be useful, should we just send them to the support url instead?

https://user-images.githubusercontent.com/39810816/119375092-00c9e800-bc80-11eb-8e9d-478e674210b6.mov

2021-05-24 16:06 UTC, VivekV95 requested changes
Left a few thoughts

2021-05-24 16:07 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/views/input/InputView.kt
> +    fun setEmailInputViewState(state: EmailViewState) {
This does email fragment specific styling

2021-05-24 16:08 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/email/EmailFragment.kt
> +            NavigationManager.shared.dismiss(this, null)
Nvm completely missed the fact that we have a close button

2021-05-24 16:09 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/email/EmailFragment.kt
> +            NavigationManager.shared.dismiss(this, null)
I kinda guessed on which model to use since this screen wasn't implemented on iOS. ErrorAlert makes sense as a good viable option since Login does that.

2021-05-24 16:10 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/email/EmailFragment.kt
> +            UtilityManager.shared.showSupportEmail(this)
Weird. It's supposed to place the email in the To box.

2021-05-24 16:15 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/views/input/InputView.kt
> +    fun setEmailInputViewState(state: EmailViewState) {
Looks like we'll need the same behavior for all our screens with input views, will look into taskifying

2021-05-24 16:24 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/views/input/InputView.kt
> +    fun setEmailInputViewState(state: EmailViewState) {
Discussed with @onodude and we'll just keep existing behavior we have in Login and Register of letting the placeholder become the hint when clicked on instead of having both of them. Can just use `setInputViewState`

2021-05-24 16:28 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/email/EmailFragment.kt
> +            NavigationManager.shared.dismiss(this, null)
I think it's fine as it is now, we can modify later if needed

2021-05-24 16:28 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/views/input/InputView.kt
> +    fun setEmailInputViewState(state: EmailViewState) {
Tell me how that would look with what you're suggesting. The label and placeholder are two different things and the label is always present instead of minimized in the edit text on the figma.... unless I'm misunderstanding what you're saying, I don't believe this needs a change

2021-05-24 16:45 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/views/input/InputView.kt
> +    fun setEmailInputViewState(state: EmailViewState) {
@onodude Will be changing the figma designs to reflect what our current default behavior is

2021-05-24 16:48 UTC, onodude commented
yeah we can revert the different placeholder thing as it is not implemented on other screens

2021-05-24 20:58 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/email/EmailFragment.kt
> +            UtilityManager.shared.showSupportEmail(this)
Here we go: https://github.com/hyfn/trx-consumer-android/pull/59/commits/312e97bc099a6999668ee81044f1a4d4cd01668f
Now shows this:
![image](https://user-images.githubusercontent.com/27742105/119406731-0af7e080-bc98-11eb-8cf2-45ad300a40aa.png)

2021-05-24 20:58 UTC, vespertineSiren commented on app/src/main/res/layout/fragment_email.xml
> +            android:id="@+id/viewHeader"
Completed.

2021-05-24 20:58 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/views/input/InputView.kt
> +    fun setEmailInputViewState(state: EmailViewState) {
Reverted to match previous design.

2021-05-24 22:33 UTC, VivekV95 approved these changes

2021-05-25 00:02 UTC, onodude approved these changes

2021-05-25 00:02 UTC, merged