TCM-99 | Build dummy login screen
hyfn/trx-consumer-android pull request #6
Opened 2021-03-28 18:45 UTC by halilyesilyurt

## Description

### Summary

- [x] Completed dummy login screen.

### Issue

[TCM-99](https://hyfnla.atlassian.net/browse/TCM-99)

### Video/Screenshot

![login](https://user-images.githubusercontent.com/30659854/112763833-cb51a700-900e-11eb-9b3f-15c32a09e5e0.png)

2021-04-01 17:31 UTC, VivekV95 commented on app/src/main/res/layout/fragment_login.xml
> +            android:layout_marginEnd="10dp"
Don't think we need the `marginEnd` and `marginBottom` here

2021-04-01 17:35 UTC, VivekV95 commented on app/src/main/res/layout/fragment_login.xml
> +        android:textSize="24sp"
Looks like this should be `32sp` according to design specs

2021-04-01 17:48 UTC, VivekV95 commented on app/src/main/res/layout/fragment_login.xml
> +        android:textSize="14sp"
Should be `11sp` according to specs, but I think we can make it 12 as 11 would give us the small font size warning

2021-04-01 17:48 UTC, VivekV95 commented on app/src/main/res/layout/fragment_login.xml
> +        android:textStyle="bold"
Let's use `android:fontFamily="@font/atcarquette_bold"` instead to closer match the specs

2021-04-01 17:50 UTC, VivekV95 commented on app/src/main/res/layout/fragment_login.xml
> +        android:background="@color/transparent"
This can be removed, `CommonButton` has a transparent background by defauly

2021-04-01 17:51 UTC, VivekV95 commented on app/src/main/res/layout/fragment_login.xml
> +    <com.trx.consumer.common.CommonLabel
Let's use a `CommonButton` here as well for consistency, I missed this when I was making `Splash`

2021-04-01 17:55 UTC, VivekV95 requested changes
Left a few minor design related comments, when resolving `strings` conflict please keep it alphabetical so things will be easier to find

2021-04-01 20:14 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/login/LoginFragment.kt
>      private val handleTapBack = Observer<Void> {
Let's implement `onBackPressed`

2021-04-01 20:15 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_login.xml
> +            android:layout_marginEnd="10dp"
Completed.

2021-04-01 20:15 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_login.xml
> +        android:textSize="24sp"
Completed.

2021-04-01 20:16 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_login.xml
> +        android:layout_marginTop="16dp"
i guess you are right  i removed it. Also i removed from second seperator.

2021-04-01 20:17 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_login.xml
> +        android:textSize="14sp"
Completed.

2021-04-01 20:17 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_login.xml
> +        android:textStyle="bold"
Completed.

2021-04-01 20:17 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_login.xml
> +        android:background="@color/transparent"
Completed.

2021-04-01 20:17 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_login.xml
> +    <com.trx.consumer.common.CommonLabel
Completed.

2021-04-01 20:21 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/screens/login/LoginFragment.kt
>      private val handleTapBack = Observer<Void> {
Completed.

2021-04-02 20:44 UTC, VivekV95 approved these changes

2021-04-02 21:28 UTC, onodude approved these changes
thanks!

2021-04-02 21:29 UTC, onodude approved these changes
resolved conflicts

2021-04-02 21:38 UTC, merged