TCM-373 | Connect workout screen
hyfn/trx-consumer-android pull request #61
Opened 2021-05-24 19:12 UTC by devender197

## Description

### Summary

- [ ] Layout and view name updated to match parity with iOS and different state created
- [ ] Booking response model created
- [ ] WorkoutViewModel updated 

### Issue

[TCM-373](https://hyfnla.atlassian.net/browse/TCM-373)

### Video/Screenshot

2021-05-24 20:31 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/WorkoutModel.kt
> +    val bookViewStatus: BookingState
Let's rename `BookingState` to `BookingViewState` to match iOS

2021-05-24 20:31 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/responses/BookingResponseModel.kt
> +class BookingResponseModel(val workouts: MutableList<WorkoutModel> = mutableListOf()) {
`workouts` don't need to be mutable

2021-05-24 20:33 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/responses/BookingResponseModel.kt
> +class BookingResponseModel(val workouts: MutableList<WorkoutModel> = mutableListOf()) {
Let's rename to `BookingsResponseModel` to match iOS

2021-05-24 20:40 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
> +            // NavigationManager.shared.present(this, R.id.player_view) TODO: needs to play video
`Player` is implemented, can check out how to launch it in `TestUtlility`

2021-05-24 20:41 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/WorkoutModel.kt
> +                if (date.elapsedMin() < kMinutesBeforeCanJoin) BookingState.JOIN else BookingState.CANCEL
Exceeds character limit

2021-05-24 20:43 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/responses/BookingResponseModel.kt
> +        get() = workouts.filter { it.isCanceled }.sortedBy { it.startsAt }.map { it.booking }
Should be filtering for `!it.isCanceled`

2021-05-24 20:46 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
> +            NavigationManager.shared.present(this, R.id.live_fragment)
This should be going to `LivePlayer` which hasn't been implemented yet, can add a todo

2021-05-24 20:51 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutViewModel.kt
> +                        model.state = BookingState.BOOKED
Guessing we'd like to modify our `ViewModel`'s `model` property which it isn't currently doing, maybe we can rename the lambda param to `booking` or something

2021-05-24 20:55 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutViewModel.kt
> +                    eventTapStartWorkout.postValue(model)
We'll want to `return` after this line based on iOS

2021-05-24 20:56 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutViewModel.kt
> +                    cacheManager.user()?.card?.let {
Looks like the logic here is reversed compared to iOS, iOS calls the user endpoint if the card is null

2021-05-24 20:59 UTC, VivekV95 requested changes
Left some initial thoughts

2021-05-24 21:41 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/responses/BookingResponseModel.kt
> +        get() = workouts.filter { it.isCanceled }.sortedBy { it.startsAt }.map { it.booking }
There's a typo there. `it.isCanceled` -> it.isCancelled

2021-05-24 22:29 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/responses/BookingResponseModel.kt
> +                }
You can probably get the jsonArray and use the `map` extension in file  get this value. This would also remove the need to have a mutableList.

2021-05-24 22:31 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
>      }
This view initalization stuff is supposed to be before observing the viewmodel events.

2021-05-24 22:36 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
> +        }
Consider creating a function for this because of how verbose it is. `textColor` and `bgColor` should be useable in an `apply` block. Refer to `PlansViewHolder`

2021-05-24 22:39 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
>          } else model as WorkoutModel
Something about this seems really off to me. Would using `as?` or something cut back on this code?

2021-05-24 22:47 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutViewState.kt
> +        const val video = "video"
`const val` should be all caps with underscores as spaces. So this should be something like:

```
const val LARGE_GROUP = "large-group"
const val ONE_ON_ONE = "1-on-1"
const val SMALL_GROUP = "small-group-training"
const val VIDEO = "video"
```

2021-05-24 22:49 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
>          }
Should there be some sort of HUD event here since we are making backend calls?

2021-05-24 22:52 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutViewModel.kt
> +                    eventLoadWorkoutView.postValue(model)
This isn't being handled in the fragment. Remove event entirely or implement in fragment as well.

2021-05-24 22:59 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
>      private val handleLoadView = Observer<WorkoutModel> { model ->
Consider removing the function body and just adding a log. This is not being called in the viewmodel and is the same contents as `handleLoadVideoView`

2021-05-24 23:44 UTC, onodude commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
> +        }
lets just change the apply to a normal setting that way this whole block will be consistent

2021-05-25 01:02 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
>          } else model as WorkoutModel
Sorry can you please elaborate this. As far as I understand, nothing seems off about this.

2021-05-25 01:33 UTC, devender197 commented on app/src/main/java/com/trx/consumer/models/responses/BookingResponseModel.kt
> +class BookingResponseModel(val workouts: MutableList<WorkoutModel> = mutableListOf()) {
I have used the `foreach` function instead of `map`. Hence I need a mutable list.

2021-05-25 01:57 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/WorkoutModel.kt
> +                if (date.elapsedMin() < kMinutesBeforeCanJoin) BookingState.JOIN else BookingState.CANCEL
I'm working with `elapsedMin` and noticed it returns negative values when current time is before the start time. So this condition will equate to true for any time before the start time, which I presume is not what we want. Maybe we should use the absolute value?

2021-05-25 02:02 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/responses/BookingResponseModel.kt
> +class BookingResponseModel(val workouts: MutableList<WorkoutModel> = mutableListOf()) {
Using `forEach` is fine, but the implementation shouldn't dictate necessity. If I see an exposed mutable property I'm going to most likely think it's being modified outside of just its creation. Can create the mutable list outside the constructor and expose it as a `List`

2021-05-25 02:03 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/responses/BookingResponseModel.kt
> +class BookingResponseModel(val workouts: MutableList<WorkoutModel> = mutableListOf()) {
Or we can use the `map` extension, I'm fine with either. They both pretty much do the same thing.

2021-05-25 06:42 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
>      private val handleLoadView = Observer<WorkoutModel> { model ->
Please look at line number 70 and 71 in `handleLoadVideoView`. it is different in `handleLoadView`

2021-05-25 06:43 UTC, devender197 commented on app/src/main/java/com/trx/consumer/models/common/WorkoutModel.kt
> +    val bookViewStatus: BookingState
`BookingState` is different than `BookingViewState`.

2021-05-25 06:45 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutViewModel.kt
> +                        model.state = BookingState.BOOKED
[Done](https://github.com/hyfn/trx-consumer-android/pull/61/files#diff-ad1c3474489651ab78612134122709e83cc1481a863c936469b91759832da917R53)

2021-05-25 06:46 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutViewModel.kt
> +                    eventLoadWorkoutView.postValue(model)
[Done](https://github.com/hyfn/trx-consumer-android/pull/61/files#diff-63443031905bf86b4e8fe7d72b97a863621e84b1bdfd870289f177726110fac8R47)

2021-05-25 06:46 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutViewModel.kt
> +                    eventTapStartWorkout.postValue(model)
[Done](https://github.com/hyfn/trx-consumer-android/pull/61/files#diff-ad1c3474489651ab78612134122709e83cc1481a863c936469b91759832da917R78)

2021-05-25 06:46 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutViewState.kt
> +        const val video = "video"
[Done](https://github.com/hyfn/trx-consumer-android/pull/61/files#diff-280c9037675cb6eded2f59a3843331989bb472ad78fdaf6d8e4801311ff2fbafR9)

2021-05-25 06:48 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
> +        }
[Done](https://github.com/hyfn/trx-consumer-android/pull/61/files#diff-63443031905bf86b4e8fe7d72b97a863621e84b1bdfd870289f177726110fac8R73)

2021-05-25 06:48 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
>      }
[Done](https://github.com/hyfn/trx-consumer-android/pull/61/files#diff-63443031905bf86b4e8fe7d72b97a863621e84b1bdfd870289f177726110fac8R35)

2021-05-25 06:51 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutViewModel.kt
> +                    cacheManager.user()?.card?.let {
[Done](https://github.com/hyfn/trx-consumer-android/pull/61/files#diff-ad1c3474489651ab78612134122709e83cc1481a863c936469b91759832da917R80)

2021-05-25 06:51 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
> +            NavigationManager.shared.present(this, R.id.live_fragment)
[Done](https://github.com/hyfn/trx-consumer-android/pull/61/files#diff-63443031905bf86b4e8fe7d72b97a863621e84b1bdfd870289f177726110fac8R105)

2021-05-25 06:53 UTC, devender197 commented on app/src/main/java/com/trx/consumer/models/common/WorkoutModel.kt
> +                if (date.elapsedMin() < kMinutesBeforeCanJoin) BookingState.JOIN else BookingState.CANCEL
[Done](https://github.com/hyfn/trx-consumer-android/pull/61/files#diff-403fadc4d5dc5fea2797de8d8c7e2a6453d5c16a30061a8861aadb271af62f75R91)

2021-05-25 06:54 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
> +            // NavigationManager.shared.present(this, R.id.player_view) TODO: needs to play video
[Done](https://github.com/hyfn/trx-consumer-android/pull/61/files#diff-63443031905bf86b4e8fe7d72b97a863621e84b1bdfd870289f177726110fac8R97)

2021-05-25 07:02 UTC, devender197 commented on app/src/main/java/com/trx/consumer/models/responses/BookingResponseModel.kt
> +        get() = workouts.filter { it.isCanceled }.sortedBy { it.startsAt }.map { it.booking }
[Done](https://github.com/hyfn/trx-consumer-android/pull/61/files#diff-6134bb6bf5479305875e66945fabdc012aac0ac198051ea7369c33c5c4e83e2dR24)

2021-05-25 15:42 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/WorkoutModel.kt
> +    val bookViewStatus: BookingState
Looks like iOS still has a separate `BookingViewState` it's returning here, let's bring that over

![Screen Shot 2021-05-25 at 10 41 50 AM](https://user-images.githubusercontent.com/39810816/119527320-d4789f00-bd45-11eb-9848-cf4f860f1a20.png)

2021-05-25 15:56 UTC, VivekV95 requested changes
Few unaddressed comments and one add-on

2021-05-25 17:05 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
>      }
THanks

2021-05-25 17:06 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
> +        }
thanks

2021-05-25 17:08 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutViewModel.kt
> +                    eventLoadWorkoutView.postValue(model)
Thanks

2021-05-25 18:11 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
>          }
Was this missed in your commits? I was unable to find.

2021-05-25 18:14 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
>          } else model as WorkoutModel
It can be reduced to one line. Some pseudocode
```if  (model is VideoModel) model.toWorkoutModelExtensionFunction else model as WorkoutModel```

2021-05-25 19:31 UTC, devender197 commented on app/src/main/java/com/trx/consumer/models/common/WorkoutModel.kt
> +                if (date.elapsedMin() < kMinutesBeforeCanJoin) BookingState.JOIN else BookingState.CANCEL
Good catch. But using absolute value will not give us any benefit because after using abs the logic will be true for a given range(eg:  -10 to +10 ) So I modified logic [here](https://github.com/hyfn/trx-consumer-android/pull/61/files#diff-403fadc4d5dc5fea2797de8d8c7e2a6453d5c16a30061a8861aadb271af62f75R94) which will do its task.

2021-05-25 19:32 UTC, devender197 commented on app/src/main/java/com/trx/consumer/models/common/WorkoutModel.kt
> +    val bookViewStatus: BookingState
If you look at `BookingState` and `BookingViewState`, it is kind of similar. Hence I used BookingState. I don't have an issue changes [done](https://github.com/hyfn/trx-consumer-android/pull/61/files#diff-403fadc4d5dc5fea2797de8d8c7e2a6453d5c16a30061a8861aadb271af62f75R90)

2021-05-25 19:36 UTC, devender197 commented
@VivekV95 @vespertineSirenThank you for review.  I have done all the suggestion. Please let me further changes requried

2021-05-25 21:57 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
>          } else model as WorkoutModel
Agreed, I'm not sure we're doing anything like this elsewhere, seems too much like business logic to be done here. A convert function in `VideoModel` would make sense, or we can create a `Params` model for this screen. We can handle it in a followup task.

2021-05-25 21:57 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
>          }
Agreed, seems like we'll need a hud here. Can handle it in a followup task

2021-05-25 21:58 UTC, VivekV95 submitted a review, later dismissed
Approving, a couple things we can handle in a followup along with any additional improvements

Created https://hyfnla.atlassian.net/browse/TCM-395, feel free to add anything that comes to mind

2021-05-26 00:02 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutViewState.kt
> +        const val video = "video"
[Done](https://github.com/hyfn/trx-consumer-android/pull/61/commits/350a346f94c03f4658c880eb7ad73bfd032d22d5)

2021-05-26 00:04 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
>          }
[Done](https://github.com/hyfn/trx-consumer-android/pull/61/commits/1961a86689a6dcb38bfeba5db790ce71235b2187)

2021-05-26 00:06 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
>          } else model as WorkoutModel
I am not agreed. I did this to make parity with iOS. There are many way to concise code. Please check iOS code [here](https://github.com/hyfn/trx-consumer-ios/blob/develop/TRX-Consumer/Screens/Workout/WorkoutViewController.swift#L17)

2021-05-26 00:08 UTC, devender197 commented
> Approving, a couple things we can handle in a followup along with any additional improvements
> 
> Created https://hyfnla.atlassian.net/browse/TCM-395, feel free to add anything that comes to mind

Handle all the suggestion here. As per my recommendation, no need to create extract task. Thank you

2021-05-26 00:12 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
>          } else model as WorkoutModel
It just doesn't seem like you're really leveraging kotlin by leaving it this way.

2021-05-26 00:17 UTC, onodude approved these changes
thank you!

2021-05-26 00:17 UTC, merged