TCM-116 | Build dummy profile screen
hyfn/trx-consumer-android pull request #62
Opened 2021-05-24 21:12 UTC by halilyesilyurt

## Description

### Summary

- [x] Completed dummy profile screen.
- [x] Added profile navigation to home.
- [x] Added settings navigation to profile.

### Issue

[TCM-116](https://hyfnla.atlassian.net/browse/TCM-116)

### Video/Screenshot

| Live Section | Virtual Section|
|--------|------|
|![profile_live](https://user-images.githubusercontent.com/30659854/119407893-92237380-bced-11eb-8211-4bf73219388e.png)|![profile_virtual](https://user-images.githubusercontent.com/30659854/119407898-9354a080-bced-11eb-9668-5f2337780a69.png)|

DEMO

https://user-images.githubusercontent.com/30659854/119407967-a8313400-bced-11eb-8b5d-07b84d6bc965.mp4

2021-05-25 00:05 UTC, onodude commented on app/src/main/res/layout/fragment_profile.xml
> +    <com.trx.consumer.common.CommonView
please use the `viewNavBar` and `btnBack` specs from `Subscriptions` screen, please mimic the `btnBack` specs for `btnSettings` in terms of layout

2021-05-25 00:05 UTC, onodude requested changes
looking good overall @halilyesilyurt left a minor comment about the top layout, also could you please revert irrelevant changes (some icon files got mixed up)

2021-05-25 16:45 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/liveworkouttable/LiveWorkoutTableAdapter.kt
> +class LiveWorkoutTableAdapter(
Let's create a proprietary adapter for the `Profile` screen called `ProfileAdapter` that will handle displaying both `Live` and `Virtual` cells. Can check out [SearchResultAdapter](https://github.com/hyfn/xpass-android/blob/develop/app/src/main/java/com/xponential/xpass/screens/search/SearchResultAdapter.kt) from Xpass for reference

2021-05-25 16:46 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/liveworkouttable/LiveWorkoutTableListener.kt
> +interface LiveWorkoutTableListener {
We can use the existing `LiveWorkoutListener` and `VirtualWorkoutListener`

2021-05-25 16:47 UTC, onodude requested changes
looks like some listeners and adapters are duplicate of existing ones. we do not need new listeners and adapters for table ones

2021-05-25 16:52 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/virtualworkouttable/VirtualWorkoutTableViewHolder.kt
> +class VirtualWorkoutTableViewHolder(view: View) : CommonViewHolder(view) {
Don't think we need the extra `ViewHolders` either, can use the existing `LiveWorkoutViewHolder` and `VirtualWorkoutViewHolder`

2021-05-25 16:52 UTC, VivekV95 requested changes
Some changes in approach

2021-05-25 19:27 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_profile.xml
> +    <com.trx.consumer.common.CommonView
Completed.

2021-05-25 19:28 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/screens/liveworkouttable/LiveWorkoutTableAdapter.kt
> +class LiveWorkoutTableAdapter(
Completed. Thanks for your advise :)

2021-05-25 19:28 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/screens/liveworkouttable/LiveWorkoutTableListener.kt
> +interface LiveWorkoutTableListener {
Completed.

2021-05-25 19:28 UTC, halilyesilyurt commented
updated pr images and demo.

2021-05-25 21:50 UTC, VivekV95 commented on app/src/main/res/layout/fragment_profile.xml
> +        android:layout_width="wrap_content"
hud should match parent for both width and height

2021-05-25 21:52 UTC, VivekV95 requested changes
Looking great, one more change from me, and these icons still need to be removed:
![Screen Shot 2021-05-25 at 4 51 42 PM](https://user-images.githubusercontent.com/39810816/119573210-909f8d00-bd79-11eb-95d7-596fa6765e7d.png)

2021-05-26 20:17 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_profile.xml
> +        android:layout_width="wrap_content"
Completed.

2021-05-26 20:17 UTC, halilyesilyurt commented
> Looking great, one more change from me, and these icons still need to be removed:
> ![Screen Shot 2021-05-25 at 4 51 42 PM](https://user-images.githubusercontent.com/39810816/119573210-909f8d00-bd79-11eb-95d7-596fa6765e7d.png)

Completed.

2021-05-26 22:41 UTC, VivekV95 approved these changes

2021-05-26 23:45 UTC, onodude approved these changes
thank you!

2021-05-26 23:45 UTC, merged