TCM-388 | Build BookingAlert Screen
hyfn/trx-consumer-android pull request #66
Opened 2021-05-26 05:29 UTC by vespertineSiren

## Description

### Summary

WIP

### Issue

[TCM-388](https://hyfnla.atlassian.net/browse/TCM-388)

### Video/Screenshot

| Some State | Some State |
|----|----|
|![both_cancels](https://user-images.githubusercontent.com/27742105/119606999-6dd89d00-bda8-11eb-91d6-9669aee9ecca.png)| Another thing |

2021-05-26 21:35 UTC, onodude approved these changes
thank you!

2021-05-26 21:42 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/WorkoutModel.kt
> +    private var currency: String = "usd"
Let's move this to constructor to lose the parcelize warning. Also looks like this can just be a `val`

2021-05-26 21:48 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/responses/BookIntentResponseModel.kt
> +            }.let { BookIntentResponseModel(listOf()) }
Think we'll want to do `?: BookIntentResponseModel(listOf())` here to handle the null

2021-05-26 21:51 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/bookingalert/BookingAlertFragment.kt
> +            viewContent.isInvisible = true
We can still interact with invisible views, using `isHidden` would be safer

2021-05-26 21:57 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/bookingalert/BookingAlertFragment.kt
> +                btnPrimary.isHidden = false
Can use `apply`, `with`, etc for the repeated view calls

2021-05-26 22:00 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/bookingalert/BookingAlertViewModel.kt
> +                    eventShowHud.postValue(false)
Looks like there are additional backend calls happening after hiding the hud, should we just show and hide it at the beginning and end of the scope launch respectively?

2021-05-26 22:05 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/bookingalert/BookingAlertViewModel.kt
> +                                // cacheManager.asyncHomeRefresh()
We won't need this, we'll just be `dismiss`ing to home which will automatically refresh it

2021-05-26 22:17 UTC, VivekV95 commented on app/src/main/res/navigation/nav_main.xml
> +        android:label="AlertFragment"
Should be "BookingAlertFragment"

2021-05-26 22:20 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/testutility/TestUtilityFragment.kt
> +        // val model = BookingAlertModel.testCardLiveBook()
The options are super helpful, thanks!

2021-05-26 22:24 UTC, VivekV95 commented
Buttons need spacing in card state for both live and virtual: 
![Screen Shot 2021-05-26 at 5 21 43 PM](https://user-images.githubusercontent.com/39810816/119738954-2523f100-be47-11eb-9437-9131ab297cf6.png)

2021-05-26 22:31 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/bookingalert/BookingAlertViewModel.kt
> +                                // cacheManager.asyncHomeRefresh()
On second thought nvm, not sure what our finalized flow will be

2021-05-26 22:32 UTC, VivekV95 requested changes
Looking great, left a few thoughts

2021-05-26 22:57 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/WorkoutModel.kt
> +    private var currency: String = "usd"
There should be logic in the future that should allow us to take payments from the UK so I set it as a `var` for now.

2021-05-26 22:57 UTC, vespertineSiren commented on app/src/main/res/navigation/nav_main.xml
> +        android:label="AlertFragment"
Good catch. Will change.

2021-05-26 23:03 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/bookingalert/BookingAlertFragment.kt
> +            viewContent.isInvisible = true
Moved setting all the clicklisteners outside out of the bind function. https://github.com/hyfn/trx-consumer-android/pull/66/commits/7fd64e6e1be8c388805bf817721c617020f5782e

2021-05-27 00:44 UTC, onodude commented on app/src/main/java/com/trx/consumer/models/common/WorkoutModel.kt
> +    private var currency: String = "usd"
@vespertineSiren has some trx insight haha i am sure that won't happen soon but a trivial change regardless

2021-05-27 00:47 UTC, onodude commented
@vespertineSiren would you be able to use the ui component names from the iOS side: [link](https://github.com/hyfn/trx-consumer-ios/blob/develop/TRX-Consumer/Screens/BookingAlert/BookingAlertView.swift)

2021-05-27 01:07 UTC, vespertineSiren commented on app/src/main/res/navigation/nav_main.xml
> +        android:label="AlertFragment"
Handled in another commit.

2021-05-27 01:08 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/bookingalert/BookingAlertViewModel.kt
> +                                // cacheManager.asyncHomeRefresh()
Errr.. okay well. Im going to dismiss this for now.

2021-05-27 01:16 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/bookingalert/BookingAlertViewModel.kt
> +                    eventShowHud.postValue(false)
Sure.  Ill rework this.

2021-05-27 01:23 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/responses/BookIntentResponseModel.kt
> +            }.let { BookIntentResponseModel(listOf()) }
Will this work? https://github.com/hyfn/trx-consumer-android/pull/66/commits/89174500ba345b7b0cd70daab06cfd50cdcd7311
Please resolve if answer if commit is sufficient.

2021-05-27 01:23 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/bookingalert/BookingAlertViewModel.kt
> +                    eventShowHud.postValue(false)
Will this work? 
https://github.com/hyfn/trx-consumer-android/pull/66/commits/e578f71b2efafa8a638aabe2cb5b17e48a59ac27
Please resolve if answer if commit is sufficient.

2021-05-27 03:08 UTC, vespertineSiren commented
Images updated. 

@onodude: Reworked image logic [here](https://github.com/hyfn/trx-consumer-android/pull/66/commits/59f1632b958524573495c52f4fd43f53635e2f4e)

2021-05-27 03:09 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/bookingalert/BookingAlertFragment.kt
> +                btnPrimary.isHidden = false
Reworked here
https://github.com/hyfn/trx-consumer-android/pull/66/commits/59f1632b958524573495c52f4fd43f53635e2f4e
Please resolve if answer in commit is sufficient.

2021-05-27 20:12 UTC, VivekV95 approved these changes
Looks like the close button got pushed out a bit, but approving as we'll be revisiting this screen anyways 
![Screen Shot 2021-05-27 at 3 06 35 PM](https://user-images.githubusercontent.com/39810816/119890855-f026a580-befd-11eb-90c6-ceb4a5b7ce5c.png)

2021-05-27 20:15 UTC, onodude approved these changes

2021-05-27 20:15 UTC, merged