TCM-381 | Button State Login
hyfn/trx-consumer-android pull request #69
Opened 2021-05-26 22:05 UTC by vespertineSiren

## Description

### Summary

- Enable/disable button based on contents in InputView
- Create function that enables button state and switches color based on two static values. 

### Issue

[TCM-381](https://hyfnla.atlassian.net/browse/TCM-381)

### Video/Screenshot

| Initial | Filled |
|----|----|
|![initial](https://user-images.githubusercontent.com/27742105/119737212-c6a14780-be33-11eb-9b58-58635c43df4f.png)|![filled](https://user-images.githubusercontent.com/27742105/119737217-c86b0b00-be33-11eb-8b97-07a45d5cec20.png)|

https://user-images.githubusercontent.com/27742105/119737184-b7ba9500-be33-11eb-9dac-f5a2c0b5b590.mov

2021-05-26 22:43 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/common/CommonButton.kt
> +            bgColor(if (isEnabled) R.color.black else R.color.greyDark)
Not sure we want specific colors built into a reusable view, would be better as an extension function

2021-05-26 22:51 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/common/CommonButton.kt
> +            bgColor(if (isEnabled) R.color.black else R.color.greyDark)
I thought it through that way but I was recommended to code it this way initially. Though that is a good suggestion for a refactor if given the greenlight in the future.

2021-05-26 22:53 UTC, VivekV95 requested changes
Just one thought

2021-05-26 22:55 UTC, VivekV95 approved these changes

2021-05-26 23:15 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/common/CommonButton.kt
> +            bgColor(if (isEnabled) R.color.black else R.color.greyDark)
Confirmed with @onodude, let's make this an extension

2021-05-26 23:16 UTC, VivekV95 requested changes
Just the extension

2021-05-26 23:19 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/common/CommonButton.kt
> +            bgColor(if (isEnabled) R.color.black else R.color.greyDark)
Cool will inline.

2021-05-27 17:43 UTC, onodude approved these changes
thank you!

2021-05-27 17:45 UTC, merged