TCM-102 | Build dummy register screen
hyfn/trx-consumer-android pull request #7
Opened 2021-03-28 18:55 UTC by halilyesilyurt

## Description

### Summary

- [x] Completed dummy register screen.

### Issue

[TCM-102](https://hyfnla.atlassian.net/browse/TCM-102)

### Video/Screenshot

![register](https://user-images.githubusercontent.com/30659854/112764190-1b7d3900-9010-11eb-9512-df1ee1adea52.png)

2021-04-01 20:17 UTC, VivekV95 commented on app/src/main/res/layout/fragment_register.xml
> +            android:layout_marginTop="16dp"
Same as the other places, let's remove `marginTop` to better match specs and iOS appearance.

2021-04-01 20:20 UTC, VivekV95 commented on app/src/main/res/layout/fragment_register.xml
> +        <com.trx.consumer.common.CommonLabel
Design specs are wrong here, label should say "Already have an account? Log in": 
[Register](https://user-images.githubusercontent.com/39810816/113349424-a3f42600-92fd-11eb-8604-0c3c5b8c9617.png)

2021-04-01 20:25 UTC, VivekV95 commented on app/src/main/res/layout/fragment_register.xml
> +            android:textStyle="bold"
Let's use ` android:fontFamily="@font/atcarquette_bold"`

2021-04-01 20:25 UTC, VivekV95 commented on app/src/main/res/layout/fragment_register.xml
> +        <com.trx.consumer.common.CommonLabel
Missing `android:fontFamily="@font/atcarquette_regular"`

2021-04-01 20:26 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/register/RegisterFragment.kt
>  class RegisterFragment : BaseFragment(R.layout.fragment_register) {
Let's implement `onBackPressed`

2021-04-01 20:37 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_register.xml
> +            android:layout_marginTop="16dp"
Completed.

2021-04-01 20:38 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_register.xml
> +        <com.trx.consumer.common.CommonLabel
Completed.

2021-04-01 20:38 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_register.xml
> +            android:textStyle="bold"
Completed.

2021-04-01 20:38 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_register.xml
> +        <com.trx.consumer.common.CommonLabel
Completed.

2021-04-01 20:39 UTC, halilyesilyurt commented on app/src/main/java/com/trx/consumer/screens/register/RegisterFragment.kt
>  class RegisterFragment : BaseFragment(R.layout.fragment_register) {
there is already onBackPressed implementation.

2021-04-02 00:04 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/register/RegisterFragment.kt
>  class RegisterFragment : BaseFragment(R.layout.fragment_register) {
Missed it, my fault!

2021-04-02 20:48 UTC, VivekV95 commented on app/src/main/res/layout/fragment_register.xml
> +            android:textSize="24sp"
Should be 32sp like `Login`, missed this the first time

2021-04-02 20:53 UTC, VivekV95 commented on app/src/main/res/layout/fragment_register.xml
> +        <com.trx.consumer.common.CommonLabel
Let's align this vertically with the `cbTerm` (I'm thinking constrain top and bottom to it), and give this a `margin_start` of 16dp so that it matches the "Register" title. We have another ticket to fix the margin of the InputViews.

2021-04-02 20:53 UTC, VivekV95 requested changes
Just a couple more small things

2021-04-03 20:38 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_register.xml
> +            android:textSize="24sp"
Completed.

2021-04-03 20:38 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_register.xml
> +        <com.trx.consumer.common.CommonLabel
Completed.

2021-04-06 00:06 UTC, onodude approved these changes
thank you!

2021-04-06 00:06 UTC, merged

2021-04-06 00:07 UTC, onodude commented
merged to the wrong branch could you please reopen this @halilyesilyurt