TCM-118 | Build dummy welcome screen
hyfn/trx-consumer-android pull request #9
Opened 2021-03-28 20:10 UTC by halilyesilyurt

## Description

### Summary

- [x] Completed dummy welcome screen.

### Issue

[TCM-118](https://hyfnla.atlassian.net/browse/TCM-118)

### Video/Screenshot

![welcome](https://user-images.githubusercontent.com/30659854/112766495-bf6be200-901a-11eb-84db-bc954fcc9af4.png)

2021-04-01 19:29 UTC, VivekV95 commented on app/src/main/res/layout/fragment_welcome.xml
> +    <com.trx.consumer.common.CommonLabel
Needs `android:fontFamily="@font/atcarquette_regular"` and `android:textSize="15sp"`

2021-04-01 19:31 UTC, VivekV95 commented on app/src/main/res/layout/fragment_welcome.xml
> +        android:textStyle="bold"
Let's use `android:fontFamily="@font/atcarquette_bold"`

2021-04-01 19:31 UTC, VivekV95 requested changes
Couple of small design changes

2021-04-03 20:44 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_welcome.xml
> +        android:textStyle="bold"
Completed.

2021-04-03 20:44 UTC, halilyesilyurt commented on app/src/main/res/layout/fragment_welcome.xml
> +    <com.trx.consumer.common.CommonLabel
Completed.

2021-04-06 00:08 UTC, VivekV95 approved these changes

2021-04-06 00:08 UTC, onodude submitted a review, later dismissed
thanks!

2021-04-07 00:31 UTC, onodude approved these changes
thanks!

2021-04-07 00:31 UTC, merged