TCM-263 | Implement prelim Analytics events
hyfn/trx-consumer-android pull request #93
Opened 2021-05-30 22:29 UTC by vespertineSiren

## Description

### Summary

- Implement model structure mentioned in ticket. 

### Issue

[TCM-263](https://hyfnla.atlassian.net/browse/TCM-263)

### Video/Screenshot

<img width="800" alt="Screen Shot 2021-05-30 at 3 28 11 PM" src="https://user-images.githubusercontent.com/27742105/120122093-ab984580-c15b-11eb-82df-cafad7d90830.png">

2021-05-30 23:55 UTC, onodude reviewed
thank you! would you be able to call these event where appropriate too

2021-05-31 16:00 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/AnalyticsEventModel.kt
> +        return JSONObject(properties.toMap())
JSONObject accepts a `Map` so we can just instantiate the maps above as immutable maps using `mapOf`

2021-05-31 16:01 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/managers/AnalyticsManager.kt
> +    fun trackAmplitude(
Can fit on one line

2021-05-31 16:02 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/AnalyticsEventModel.kt
> +    val amplitudeProperties: List<AnalyticsPropertyModel>
Not currently being used, will we be using it later?

2021-05-31 16:08 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/AnalyticsEventModel.kt
> +    CANCEL_SUBSCRIPTION,
This seems like the perfect use-case to use a `sealed class` instead of an `enum`: Each sub-class would contain whatever model it needs as a property and by checking the sealed class type, the model is is already available as its appropriate type and we don't need to cast anything

2021-05-31 16:12 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/AnalyticsEventModel.kt
> +        return JSONObject(properties.toMap())
Looking again, I'm not sure if the pairs are actually getting inserted

2021-05-31 16:18 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/addcard/AddCardViewModel.kt
> +            analyticsManager.trackAmplitude(
We could just do this in `BaseViewModel` I think

2021-05-31 16:24 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/home/HomeViewModel.kt
> +        analyticsManager.trackAmplitude(
Can fit in one line

2021-05-31 16:25 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/login/LoginViewModel.kt
> +                analyticsManager.trackAmplitude(
Can fit in one line

2021-05-31 16:33 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/player/PlayerActivity.kt
> +    private val analyticsManager: AnalyticsManager by lazy { AnalyticsManager(ConfigManager()) }
Don't really want to use a separate instances outside of our singleton instances, I'm guessing `@AndroidEntryPoint` doesn't work because of the ancient `Activity`? We can create `PlayerParams` or something and send the manager in it along with the video as an extra

2021-05-31 16:43 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/player/PlayerActivity.kt
> +            analyticsManager.trackAmplitude(
Can fit in one line

2021-05-31 16:44 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/player/PlayerActivity.kt
> +                hasCompleted25 = false
Should be setting to `true` here I think

2021-05-31 16:45 UTC, VivekV95 requested changes
Left a few initial thoughts

2021-05-31 16:50 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/addcard/AddCardViewModel.kt
> +                this.javaClass.simpleName.replace("ViewModel", "")
Can maybe create a `BaseViewModel` extension or function to get the screen name instead of having to do it in every ViewModel

2021-05-31 16:53 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/welcome/WelcomeFragment.kt
> +            btnBack.setOnClickListener { viewModel.doTapBack() }
Can have these call `action` while we're here

2021-05-31 17:12 UTC, onodude commented on app/src/main/java/com/trx/consumer/models/common/AnalyticsEventModel.kt
> +    fun getAmplitudePropertiesJSON(value: Any?): JSONObject {
this is not very safe... lets try to implement methods like these ones in the manager
```
fun trackCancelSubscription(model: UserModel) {…}
fun trackFilterOnDemand(model: FilterOptionsModel) {…}
```

2021-05-31 17:13 UTC, onodude commented on app/src/main/java/com/trx/consumer/models/common/AnalyticsEventModel.kt
> +    val amplitudeProperties: List<AnalyticsPropertyModel>
this should not be necessary in the desired approach. the json should be built in each manager tracker method

2021-06-02 04:06 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/AnalyticsEventModel.kt
> +    fun getAmplitudePropertiesJSON(value: Any?): JSONObject {
Something like this? https://github.com/hyfn/trx-consumer-android/pull/93/commits/dded474dd0a5ce462c73a5ba6cb44775079c80d1

2021-06-02 04:23 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/AnalyticsEventModel.kt
> +    CANCEL_SUBSCRIPTION,
Just followed ticket suggestion.

2021-06-02 05:11 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/AnalyticsEventModel.kt
> +        return JSONObject(properties.toMap())
This fixes it.

2021-06-02 05:12 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/managers/AnalyticsManager.kt
> +    fun trackAmplitude(
I prefer the look of it.

2021-06-02 05:12 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/AnalyticsEventModel.kt
> +    val amplitudeProperties: List<AnalyticsPropertyModel>
Removed here https://github.com/hyfn/trx-consumer-android/pull/93/commits/dded474dd0a5ce462c73a5ba6cb44775079c80d1

2021-06-02 05:13 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/home/HomeViewModel.kt
> +        analyticsManager.trackAmplitude(
Handled somewhere.

2021-06-02 05:13 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/login/LoginViewModel.kt
> +                analyticsManager.trackAmplitude(
Handled somewhere.

2021-06-02 05:13 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/player/PlayerActivity.kt
> +    private val analyticsManager: AnalyticsManager by lazy { AnalyticsManager(ConfigManager()) }
I think this looks kinda nutty but check it out. https://github.com/hyfn/trx-consumer-android/pull/93/commits/56bae557d8e35fb71044302f5ace31593c30fea0

2021-06-02 05:14 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/player/PlayerActivity.kt
> +            analyticsManager.trackAmplitude(
Handled in some commit

2021-06-02 05:14 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/player/PlayerActivity.kt
> +                hasCompleted25 = false
Handled somehwere

2021-06-02 05:14 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/addcard/AddCardViewModel.kt
> +                this.javaClass.simpleName.replace("ViewModel", "")
Here we are: https://github.com/hyfn/trx-consumer-android/pull/93/commits/737eb6f32b3146d71928b3c6d8137dbcdb3741c1

2021-06-02 05:15 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/welcome/WelcomeFragment.kt
> +            btnBack.setOnClickListener { viewModel.doTapBack() }
https://github.com/hyfn/trx-consumer-android/pull/93/commits/1b846ebab03192a608c586a302ddacc9510ebee7

2021-06-02 16:39 UTC, onodude commented on app/src/main/java/com/trx/consumer/models/common/AnalyticsEventModel.kt
> +    val amplitudeEventCategory: String
not used please remove

2021-06-02 16:40 UTC, onodude commented on app/src/main/java/com/trx/consumer/models/common/AnalyticsEventModel.kt
> +    private fun trackCancelSubscription(user: UserModel): Map<String, Any> =
these should not return a map and these functions should be in the manager

2021-06-02 16:40 UTC, onodude requested changes
thank you would you be able to organize the structure like we discussed

2021-06-02 17:45 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/AnalyticsEventModel.kt
> +    private fun trackCancelSubscription(user: UserModel): Map<String, Any> =
So to clarify, you want me to move `fun trackAnalyticEvent` and all the functions in trackAnalyticEvent over to the `AnalyticsManager`? Ill do that.

2021-06-02 17:46 UTC, onodude commented on app/src/main/java/com/trx/consumer/models/common/AnalyticsEventModel.kt
> +    private fun trackCancelSubscription(user: UserModel): Map<String, Any> =
https://github.com/hyfn/trx-consumer-android/pull/93#discussion_r642607061

2021-06-02 18:21 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/AnalyticsEventModel.kt
> +    private fun trackCancelSubscription(user: UserModel): Map<String, Any> =
Here you go: https://github.com/hyfn/trx-consumer-android/pull/93/commits/bee594af535c5b117f7a96ffe2d8439bd1a42733

2021-06-02 18:22 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/AnalyticsEventModel.kt
> +    val amplitudeEventCategory: String
Here you are https://github.com/hyfn/trx-consumer-android/pull/93/commits/d9143eb3c28f71f2f2a0d3d37c85863801d9d849

2021-06-02 23:23 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/managers/AnalyticsManager.kt
> +            JSONObject((value))
Extra pair of parens here in all the logs

2021-06-02 23:29 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/player/PlayerActivity.kt
> +    private val analyticsManager: AnalyticsManager by lazy { AnalyticsManager(ConfigManager()) }
Yeah it's... unfortunate. Would be open to other ideas if you can think of any.

2021-06-02 23:33 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/params/PlayerParamsModel.kt
> +    var video: VideoModel = VideoModel.test().apply { id = "6232799349001" },
Don't think we want a default value here, should always be expecting a video passed here to avoid any confusion. Can just revert just the video was being sent in `TestUtility`

2021-06-02 23:36 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/player/PlayerActivity.kt
> +                event.getIntegerProperty(Event.PLAYHEAD_POSITION) /
Let's move to the line above, doesn't exceed character limit

2021-06-02 23:39 UTC, VivekV95 requested changes
Looking good, just a couple things

2021-06-03 00:59 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/AnalyticsPropertyModel.kt
> +    val propertyType: String
Not being used, not sure if needed or not

2021-06-03 02:19 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/AnalyticsPropertyModel.kt
> +    val propertyType: String
Mentioned to add it in the ticket https://hyfnla.atlassian.net/browse/TCM-263

2021-06-03 02:25 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/managers/AnalyticsManager.kt
> +            JSONObject((value))
My script command+R got the best of me. Will Remove.

2021-06-03 02:26 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/managers/AnalyticsManager.kt
> +            JSONObject((value))
Here we go https://github.com/hyfn/trx-consumer-android/pull/93/commits/e53b9866e3014f9445d2f840103d8db2757a6a08

2021-06-03 02:26 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/params/PlayerParamsModel.kt
> +    var video: VideoModel = VideoModel.test().apply { id = "6232799349001" },
Here we go: https://github.com/hyfn/trx-consumer-android/pull/93/commits/e53b9866e3014f9445d2f840103d8db2757a6a08

2021-06-03 02:26 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/player/PlayerActivity.kt
> +                event.getIntegerProperty(Event.PLAYHEAD_POSITION) /
Ta da https://github.com/hyfn/trx-consumer-android/pull/93/commits/e53b9866e3014f9445d2f840103d8db2757a6a08

2021-06-03 18:04 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/player/PlayerActivity.kt
> +        val playerParams = NavigationManager.shared.params(intent) as PlayerParamsModel
Have to modify what's being send in `WorkoutFragment` as well

2021-06-03 18:11 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/player/PlayerActivity.kt
> +        analyticsManager.trackPageView(
Can fit in one line

2021-06-03 18:12 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/player/PlayerActivity.kt
> +        analyticsManager.trackPageView(
Also `this` call not needed

2021-06-03 18:12 UTC, VivekV95 requested changes
Couple final things I missed

2021-06-04 17:13 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/player/PlayerActivity.kt
> +        val playerParams = NavigationManager.shared.params(intent) as PlayerParamsModel
This is going to be a bit more involved.

2021-06-04 17:46 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/params/PlayerParamsModel.kt
> +    var workout: WorkoutModel = WorkoutModel.testLive()
This isn't necessary, `Player` only expects a video and never a workout.

2021-06-04 17:49 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/params/PlayerParamsModel.kt
> +    var workout: WorkoutModel = WorkoutModel.testLive()
Look at what is being sent in WorkoutFragment.

2021-06-04 18:06 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
> +        if (model.workout.workoutState == WorkoutViewState.VIDEO) {
Doesn't solve the issue, `PlayerActivity` is expecting a `PlayerParamsModel` and not just a `VideoModel`, which is the modification I was talking about. The only change we needed to make here was to send the `AnalyticsManager` along with the video in the params. Currently `Player` is crashing from here.

2021-06-04 18:07 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
> +        if (model.workout.workoutState == WorkoutViewState.VIDEO) {
Sorry if I was confusing, should've been more clear

2021-06-04 18:14 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
> +        if (model.workout.workoutState == WorkoutViewState.VIDEO) {
Squashed those two commits: https://github.com/hyfn/trx-consumer-android/pull/93/commits/960d1615feabd8932f85135de9c804ebf79a505c

2021-06-04 18:23 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/workout/WorkoutFragment.kt
> +        if (model.workout.workoutState == WorkoutViewState.VIDEO) {
Still not a huge fan of sending a workout model to `Player` that's not being used, I think down the line we could maybe split up the handlers into `handleTapStartVideoWorkout` and one for the others, but yeah out of scope and all.

2021-06-04 19:40 UTC, VivekV95 approved these changes

2021-06-04 19:42 UTC, VivekV95 submitted a review, later dismissed

2021-06-04 19:43 UTC, onodude commented on app/src/main/java/com/trx/consumer/extensions/BaseViewModelExtension.kt
> +    get() = this.javaClass.simpleName.replace("ViewModel", "")
not sure this is correct each page has a fixed name please remove the page view events and lets address in another task

2021-06-04 19:43 UTC, onodude requested changes
@vespertineSiren @VivekV95 would you be able to remove the page view events and lets address in another task

2021-06-04 19:49 UTC, onodude requested changes
@vespertineSiren separated the page view and player events into different tasks as they will need more work. could you please finalize the preliminary events with respect to this?

2021-06-21 18:24 UTC, onodude commented
hey @devender197 could you please take over this PR and implement pairty with: https://github.com/hyfn/trx-consumer-ios/pull/175 thank you! cc @vespertineSiren

2021-06-21 20:52 UTC, devender197 commented on app/src/main/java/com/trx/consumer/extensions/BaseViewModelExtension.kt
> +    get() = this.javaClass.simpleName.replace("ViewModel", "")
[Removed](https://github.com/hyfn/trx-consumer-android/pull/93/commits/30a6b28dc2cd5f9049292619a2ec3579661bec34)

2021-06-22 18:18 UTC, onodude commented on app/src/main/java/com/trx/consumer/screens/register/RegisterViewModel.kt
>                  eventShowOnboarding.call()
should be in the else to match iOS

2021-06-22 21:46 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/register/RegisterViewModel.kt
>                  eventShowOnboarding.call()
Moved the `eventShowOnBoarding.call()` inside the else [here]()

2021-06-22 23:02 UTC, VivekV95 approved these changes

2021-06-22 23:06 UTC, onodude approved these changes
thank you!

2021-06-22 23:06 UTC, merged

2021-06-22 23:07 UTC, onodude commented on app/src/main/java/com/trx/consumer/screens/player/PlayerActivity.kt
> +    private val analyticsManager: AnalyticsManager by lazy { AnalyticsManager(ConfigManager()) }
@VivekV95 @devender197 should we create a followup task for this?