TCM-463 |  Improve discover filters flow
hyfn/trx-consumer-android pull request #96
Opened 2021-06-01 06:49 UTC by devender197

## Description

### Summary

- [ ] Navigate to workouts tab if filters are selected.
- [ ] Clear the filters and decrease the opacity of the filters component to 0.3 when collections and programs tabs are selected

### Issue

[TCM-463](https://hyfnla.atlassian.net/browse/TCM-463)

### Video/Screenshot

https://user-images.githubusercontent.com/24737954/120278996-ca393200-c26a-11eb-89c7-a3c991e6f23a.mov

2021-06-01 23:09 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverFragment.kt
> +        viewModel.doLoadVideos()
`doLoadView` is our common pattern, can call `doLoadVideos` within `doLoadView`

2021-06-01 23:27 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverViewModel.kt
> +    fun setFilterClick(isClickable: Boolean) {
Let's used either `enabled` or `clickable` across for naming instead of both, bit confusing to follow otherwise

2021-06-01 23:27 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverViewModel.kt
> +    var isFilterEnable: Boolean = true
`isFilterEnabled`

2021-06-01 23:27 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverViewModel.kt
> +    private suspend fun doLoadFilteredWorkout(paramsToSend: HashMap<String, Any>): List<VideoModel> {
`doLoadFilteredWorkouts`

2021-06-01 23:36 UTC, VivekV95 requested changes
Logic looks good, just some naming stuff

2021-06-01 23:40 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverViewModel.kt
> +    var isFilterEnable: Boolean = true
Can also make this `private set` otherwise the setter becomes redundant

2021-06-02 08:14 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverViewModel.kt
> +    fun setFilterClick(isClickable: Boolean) {
[Done](https://github.com/hyfn/trx-consumer-android/pull/96/files#diff-7d6537adf3387efed84a304a14a1f45a83ad7b40211b6512c3ed144eccee7e55R114)

2021-06-02 08:14 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverViewModel.kt
> +    var isFilterEnable: Boolean = true
[Done](https://github.com/hyfn/trx-consumer-android/pull/96/files#diff-7d6537adf3387efed84a304a14a1f45a83ad7b40211b6512c3ed144eccee7e55R26)

2021-06-02 08:15 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverViewModel.kt
> +    private suspend fun doLoadFilteredWorkout(paramsToSend: HashMap<String, Any>): List<VideoModel> {
[Done](https://github.com/hyfn/trx-consumer-android/pull/96/files#diff-7d6537adf3387efed84a304a14a1f45a83ad7b40211b6512c3ed144eccee7e55R65)

2021-06-02 08:15 UTC, devender197 commented
@VivekV95 Thank you for review. I have implemented the requested change. Please let me know for further enhancements. Thank you.

2021-06-02 21:42 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverFragment.kt
> +        viewModel.doLoadVideos()
I second this. Should be included all the same for pattern consistency.

2021-06-02 21:45 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverFragment.kt
> +    private fun handleFilterClick(isClickable: Boolean) {
I'm not sure I agree with the naming of this function. The `handle` prefix is usually reserved for `Observer<T>`. Maybe do something like `loadFilterClick` or something along those lines.

2021-06-02 21:48 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverFragment.kt
> +    private fun handleFilterClick(isClickable: Boolean) {
Going down to line 55, we're also calling a function in the viewmodel.... wouldn't an `event` for this make more sense? I dont see many handlers in the app call a viewmodel function directly.

2021-06-02 21:54 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverViewModel.kt
> +    private var isFilterEnabled: Boolean = true
I'm not a big fan of how this variable is being used. Can't you enable/disable the views that are associated with calling `doTapFilter` and `doTapDiscoverFilter` instead of using that variable for checks?

2021-06-02 22:00 UTC, vespertineSiren commented on app/src/main/res/layout/fragment_discover.xml
> -
Why was this removed?

2021-06-02 22:00 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverViewModel.kt
> +    private fun resetFilters() {
`doResetFilters()`?

2021-06-02 22:02 UTC, vespertineSiren requested changes
Few thoughts. 

Please add `//regions [Region Name]` and `//endregion` for easier organization.

2021-06-02 23:55 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverViewModel.kt
> +    var filteredWorkouts: List<VideoModel> = listOf()
We're not storing these based on our discussion, just sending them

2021-06-03 00:18 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverViewModel.kt
> +    private var isFilterEnabled: Boolean = true
To add on, do we want filters to be scrollable but not clickable, or disable all interaction?

2021-06-03 00:55 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverViewModel.kt
> +    private var isFilterEnabled: Boolean = true
Confirmed with @onodude, we'll want to just disable all interaction with filters, so shouldn't be able to click or scroll when on collections or programs

2021-06-03 01:21 UTC, onodude commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverViewModel.kt
> +    private var isFilterEnabled: Boolean = true
yup all the above are correct. we can remove the variable, lets have a method called `setFiltersEnabled` in the fragment which we can just call in the load workouts collections and programs handlers

2021-06-03 02:24 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverViewModel.kt
> +    private fun resetFilters() {
We have reset functionin FilterOptionsViewModel. So I think name is fine. @onodude please let me know if it is required

2021-06-03 02:34 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverViewModel.kt
> +    var filteredWorkouts: List<VideoModel> = listOf()
This variable is not created to store the list. It is part of logic. Just consider situation, user want to selected few filter and now we need to get a filtered list from server by calling video(params) and wants to get workout, collection and program by calling videos() which is required. After getting this I want to call the doWorkout only once. If I separate both the call individually user can see a flick first workout list from video and then filtered workout. For any further discussion we can talk on call or group channel.

2021-06-03 02:41 UTC, devender197 commented on app/src/main/res/layout/fragment_discover.xml
> -
[Changes reverted](https://github.com/hyfn/trx-consumer-android/pull/96/commits/8b23f6d62a3052f6d9c51f155322c74f1f136e48#diff-34fc9a1ee677f41779300226835d10828342101e207577c98de99567a74a3fb8R129)

2021-06-03 02:42 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverFragment.kt
> +    private fun handleFilterClick(isClickable: Boolean) {
[Done](https://github.com/hyfn/trx-consumer-android/pull/96/commits/8b23f6d62a3052f6d9c51f155322c74f1f136e48#diff-b8b5acbef5ed93a44a1868dafc1fb0a8030303ec8efaac50ea795075a767ed99R154)

2021-06-03 02:43 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverViewModel.kt
> +    private var isFilterEnabled: Boolean = true
RecyclerView scroll is disabled [here](https://github.com/hyfn/trx-consumer-android/pull/96/commits/8b23f6d62a3052f6d9c51f155322c74f1f136e48#diff-b8b5acbef5ed93a44a1868dafc1fb0a8030303ec8efaac50ea795075a767ed99R157)

2021-06-03 05:55 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverViewModel.kt
> +    var filteredWorkouts: List<VideoModel> = listOf()
Makes sense, but if we have the ability to preserve the filtered workouts, not sure why resetting the filters when another tab is tapped is a requirement, will discuss tomorrow

2021-06-03 19:16 UTC, devender197 commented
@onodude @VivekV95 @vespertineSiren. Thank you for review. I have done the requested change in team meeting. Please review it and let me if any enhancement is required.

1. Removed isFilteredEnabled and FilteredWorkouts from viewmodel [here](https://github.com/hyfn/trx-consumer-android/pull/96/commits/60162cbc1a8ad0eb2161607b58c74e51426213ee#diff-7d6537adf3387efed84a304a14a1f45a83ad7b40211b6512c3ed144eccee7e55L27) and [here](https://github.com/hyfn/trx-consumer-android/pull/96/commits/5b8d394ed209942ad00562970093ca4031b8998f#diff-7d6537adf3387efed84a304a14a1f45a83ad7b40211b6512c3ed144eccee7e55L22)
2. Disable the scroll and child click listeners for recyclerview [here](https://github.com/hyfn/trx-consumer-android/pull/96/commits/60162cbc1a8ad0eb2161607b58c74e51426213ee#diff-fab3d51859943ce286edb4d9ad505f98945651bf69c0dcbfc34820adc14a5383R24) and [here](https://github.com/hyfn/trx-consumer-android/pull/96/commits/60162cbc1a8ad0eb2161607b58c74e51426213ee#diff-b8b5acbef5ed93a44a1868dafc1fb0a8030303ec8efaac50ea795075a767ed99R156)

2021-06-03 19:26 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverFragment.kt
> +        viewModel.doLoadVideos()
[Done](https://github.com/hyfn/trx-consumer-android/pull/96/commits/38f58431a7b17b8fe4178b0059e0102d556e9341)

2021-06-03 19:27 UTC, devender197 commented
> Few thoughts.
> 
> Please add `//regions [Region Name]` and `//endregion` for easier organization.

@vespertineSiren Thank you . Region added [here](https://github.com/hyfn/trx-consumer-android/pull/96/commits/0a1545a7028b9e3a4e84bbbc6ee1a903e2d77e26)

2021-06-03 19:28 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverViewModel.kt
> +    var filteredWorkouts: List<VideoModel> = listOf()
[Removed](https://github.com/hyfn/trx-consumer-android/pull/96/commits/5b8d394ed209942ad00562970093ca4031b8998f)

2021-06-03 20:19 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/common/CommonRecyclerView.kt
> +                return !isUserInteractionEnabled
We'll be bringing over these changes to Xpass and other projects so we'll still want to account for the old disabling scrolling behavior, with this change disabling scrolling will have no effect. Flow should go like this:
- if `isUserInteractionEnabled` is false, then just return false
- otherwise, return whatever the value of `isScrollable` is

2021-06-03 20:20 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/extensions/ViewExtensions.kt
> +fun View.isEnabled(enabled: Boolean) {
This seems way out of scope, we just wanted to disable `CommonRecyclerView` interaction, there's no guarantee this is the behavior we'll want outside of the `Discover` screen and it likely won't be

2021-06-03 20:21 UTC, devender197 commented on app/src/main/java/com/trx/consumer/extensions/ViewExtensions.kt
> +fun View.isEnabled(enabled: Boolean) {
It will useful in future if we want disable any view and all the childview.

2021-06-03 20:37 UTC, devender197 commented on app/src/main/java/com/trx/consumer/common/CommonRecyclerView.kt
> +                return !isUserInteractionEnabled
[Done](https://github.com/hyfn/trx-consumer-android/pull/96/commits/715719a9780797214db90dda3a8e165710d9236c)

2021-06-03 21:14 UTC, onodude commented on app/src/main/java/com/trx/consumer/common/CommonRecyclerView.kt
> +                return if (!isUserInteractionEnabled) true
`return if (!isUserInteractionEnabled) true`
instead
`return if (isUserInteractionEnabled) false`

2021-06-03 21:16 UTC, onodude commented on app/src/main/java/com/trx/consumer/extensions/ViewExtensions.kt
> +fun View.isEnabled(enabled: Boolean) {
could you please remove the extension please is just used in one place and implement the method we discussed

2021-06-03 21:16 UTC, onodude requested changes
thanks, left a couple of notes

2021-06-03 21:38 UTC, onodude commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverFragment.kt
> +        setFilterEnabled(false)
i guess not needed since its also called in `loadTabs`

2021-06-03 21:38 UTC, onodude commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverViewModel.kt
> +    //endregion
thank you for the regions

2021-06-03 21:40 UTC, onodude commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverViewModel.kt
> +    private fun resetFilters() {
does not have a event flow attached so can be resetFilters imo

2021-06-03 21:44 UTC, onodude commented on app/src/main/java/com/trx/consumer/common/CommonRecyclerView.kt
> +                return if (!isUserInteractionEnabled) true
sorry this breaks the logic, nvm

2021-06-03 21:44 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverViewModel.kt
> +        eventLoadFilters.postValue(filters)
I _think_ this can be removed as filters are posted in the `doLoadVideos` flow and we don't need to do it again, please correct me if I'm wrong though

2021-06-03 21:45 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverViewModel.kt
> +        eventLoadFilters.postValue(filters)
Nvm I think we do need it as selected filters gets reset

2021-06-03 21:50 UTC, devender197 commented on app/src/main/java/com/trx/consumer/extensions/ViewExtensions.kt
> +fun View.isEnabled(enabled: Boolean) {
[Reomved](https://github.com/hyfn/trx-consumer-android/pull/96/commits/39ddaa9e622703d41cb9f99458b797e678f398cc#diff-1486743caa850524ef37fe308ca92963c99f21d27c84527c5b4bc7175e72e969L48)

2021-06-03 21:50 UTC, devender197 commented on app/src/main/java/com/trx/consumer/common/CommonRecyclerView.kt
> +                return if (!isUserInteractionEnabled) true
Done

2021-06-03 21:52 UTC, devender197 commented on app/src/main/java/com/trx/consumer/screens/discover/DiscoverFragment.kt
> +        setFilterEnabled(false)
[Removed](https://github.com/hyfn/trx-consumer-android/pull/96/commits/8658b806b7d1fd8c9d35ab0fbd840a33815f9738#diff-b8b5acbef5ed93a44a1868dafc1fb0a8030303ec8efaac50ea795075a767ed99L131)

2021-06-03 22:12 UTC, onodude approved these changes
thank you!

2021-06-03 22:12 UTC, merged