TCM-485 | Refactor Plans response.
hyfn/trx-consumer-android pull request #97
Opened 2021-06-01 22:39 UTC by vespertineSiren

## Description

### Summary

Parsing of JSON based on this new [structure](https://trx-dashboard-dev.vercel.app/api/subscriptions)

### Issue

[TCM-485](https://hyfnla.atlassian.net/browse/TCM-485)

### Video/Screenshot

| | | |
|----|----|----|
|![Screenshot_1622586939](https://user-images.githubusercontent.com/27742105/120398597-6442be00-c2ef-11eb-937a-f77b6e3f290b.png)|![Screenshot_1622586944](https://user-images.githubusercontent.com/27742105/120398593-63aa2780-c2ef-11eb-98a4-5bc1f5c2f9d0.png)|![Screenshot_1622586947](https://user-images.githubusercontent.com/27742105/120398590-6278fa80-c2ef-11eb-9a5f-0246f0491d5f.png)|

2021-06-01 23:58 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/PlanModel.kt
> +                conflicts = jsonObject.optJSONArray("subsThisOneConflictsWith")?.let {
I think it'd be good to extract this (mapping json array into `PlanType`) into a function as it's happening in a few places

2021-06-02 00:01 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/PlanModel.kt
> +                price = jsonObject.optInt("priceInCents").toDouble(),
Would price in cents need to be a double?

2021-06-02 00:08 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/PlansModel.kt
> +inline fun <T> MutableList<T>.mapInPlace(mutator: (T) -> T) {
Doesn't look like this is being used

2021-06-02 00:10 UTC, VivekV95 requested changes
Had a few thoughts

2021-06-02 01:12 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/PlansModel.kt
> +inline fun <T> MutableList<T>.mapInPlace(mutator: (T) -> T) {
Good catch. It was an experiment I forgot to remove.

2021-06-02 05:18 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/PlanModel.kt
> +    var trialDays: Int = 0,
A lot of them were `var` initially so I stuck with this. Seems to be inconsistencies in all the models that exceeds the scope of this ticket.

2021-06-02 05:30 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/PlanModel.kt
> +                price = jsonObject.optInt("priceInCents").toDouble(),
Its a `Double` on iOS so they would have to change it too. I think we're following their lead.

2021-06-02 05:37 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/PlanModel.kt
> +                conflicts = jsonObject.optJSONArray("subsThisOneConflictsWith")?.let {
Here we are: https://github.com/hyfn/trx-consumer-android/pull/97/commits/05569e4f13ccf586770f43fcfffade416440dec9

2021-06-02 05:42 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/PlanModel.kt
> +                    .let { PlanPermissionModel.parse(it) },
Here we go https://github.com/hyfn/trx-consumer-android/pull/97/commits/1280dd8a105c1951e75cbd5c825a4ce3dca2d787

2021-06-02 16:46 UTC, VivekV95 approved these changes

2021-06-02 16:47 UTC, onodude commented on app/src/main/java/com/trx/consumer/models/responses/PlansResponseModel.kt
> +            } else PlansResponseModel(
discard...

2021-06-02 16:47 UTC, onodude commented on app/src/main/java/com/trx/consumer/models/common/PlansModel.kt
> +        fun parseDev(jsonObject: JSONObject): PlansModel {
have one method...

2021-06-02 16:48 UTC, onodude requested changes
very nice changes! lets remove the dev stuff tho

2021-06-02 18:34 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/PlansModel.kt
> +        fun parseDev(jsonObject: JSONObject): PlansModel {
Here you go https://github.com/hyfn/trx-consumer-android/pull/97/commits/aadb8a0a0ad2e4df06902bb6f403e2f205bc4c1c

2021-06-02 18:34 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/responses/PlansResponseModel.kt
> +            } else PlansResponseModel(
Here you go https://github.com/hyfn/trx-consumer-android/pull/97/commits/aadb8a0a0ad2e4df06902bb6f403e2f205bc4c1c

2021-06-02 23:07 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/PlansModel.kt
> +            val free = jsonObject.getJSONArray("baseValues").map { base ->
Failing on prod, not sure if that's expected or not: 

![Screen Shot 2021-06-02 at 6 06 27 PM](https://user-images.githubusercontent.com/39810816/120563086-624f2c80-c3cd-11eb-91ad-551724fa4108.png)

2021-06-02 23:08 UTC, VivekV95 requested changes
Doesn't seem to be working on prod

2021-06-02 23:09 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/PlansModel.kt
> +            val free = jsonObject.getJSONArray("baseValues").map { base ->
I was told to take that out the enviroment check with associated parsing since we're testing on dev with this

2021-06-02 23:11 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/PlansModel.kt
> +            val free = jsonObject.getJSONArray("baseValues").map { base ->
Pinged @onodude, don't know enough about the requirements to determine whether this is fine or not

2021-06-02 23:13 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/PlansModel.kt
> +            val free = jsonObject.getJSONArray("baseValues").map { base ->
Ah okay I misinterpreted the ticket notes, so the prod structure will take on the current dev structure?

2021-06-03 00:56 UTC, VivekV95 approved these changes

2021-06-03 21:20 UTC, onodude commented on app/src/main/java/com/trx/consumer/models/common/PlanModel.kt
> +                conflicts = PlanType.typeListFromJSONArray(
conflicts not needed to be parsed

2021-06-03 21:53 UTC, devender197 submitted a review, later dismissed
Looking good to me. Thank you

2021-06-04 06:48 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/PlanModel.kt
> +                conflicts = PlanType.typeListFromJSONArray(
https://github.com/hyfn/trx-consumer-android/pull/97/commits/2a892f28f37ece16874f9c1bab61ec8ac79a9b5f

2021-06-04 21:16 UTC, VivekV95 submitted a review, later dismissed

2021-06-07 16:59 UTC, onodude commented on app/src/main/java/com/trx/consumer/models/common/PlanModel.kt
> +    enum class PlanType {
these should not be hardcoded lets figure out a way to be dynamic

2021-06-07 23:41 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/PlanModel.kt
> +    enum class PlanType {
```
     customValues.keys().asSequence().toList().map {
                    PlanModel.parse(
                        customValues.getJSONObject(it)
                    )
                }
```

This is already in there and handling keys accordingly.

2021-06-07 23:42 UTC, vespertineSiren commented on app/src/main/java/com/trx/consumer/models/common/PlanModel.kt
> +    enum class PlanType {
Enums removed here: https://github.com/hyfn/trx-consumer-android/pull/97/commits/bfb3f1e0ffc0ebf83f22d310117bc12b602361ea

2021-06-08 18:14 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/PlanModel.kt
> +                key = jsonObject.optString("key", jsonObject.optString("name")),
Are we expecting a plan to ever come back without a key? If so, would the name be an appropriate substitute? Feels like they're different things

2021-06-08 18:21 UTC, VivekV95 commented on app/src/main/java/com/trx/consumer/models/common/PlanModel.kt
> +                key = jsonObject.optString("key", jsonObject.optString("name")),
Also, based on [this](https://github.com/hyfn/trx-consumer-android/pull/97#discussion_r646781208) discussion, this isn't currently being handled like we handle our filters. Filters assign the identifier (would be `key` in this case) using the key of the json object itself.

2021-06-08 18:29 UTC, VivekV95 requested changes
Marking as needs changes just because I had a couple questions

2021-06-22 00:15 UTC, onodude commented
thank you!

2021-06-22 00:15 UTC, closed without merging