TCM-467 | Replace LoadingHUD's JSON
hyfn/trx-consumer-android pull request #99
Opened 2021-06-02 19:21 UTC by vespertineSiren

## Description

### Summary

- Change to JSON, Small change to XML. 

### Issue

[TCM-467](https://hyfnla.atlassian.net/browse/TCM-467)

### Video/Screenshot

https://user-images.githubusercontent.com/27742105/120539901-f05eef00-c39c-11eb-9b20-612e79e429f9.mov

2021-06-02 22:39 UTC, VivekV95 commented on app/src/main/res/layout/layout_hud.xml
> +            android:id="@+id/imgSquare"
Are we still keeping the white container with the new animation? Looks a bit odd

2021-06-02 22:39 UTC, vespertineSiren commented on app/src/main/res/layout/layout_hud.xml
> +            android:id="@+id/imgSquare"
Yeah it was on the iOS PR.

2021-06-02 22:40 UTC, VivekV95 commented on app/src/main/res/layout/layout_hud.xml
> +            android:layout_width="match_parent"
can just have `style="@style/MatchParentDimensionsViewStyle"` instead of the current style + width + height

2021-06-02 22:41 UTC, VivekV95 requested changes
Couple thoughts

2021-06-03 00:39 UTC, onodude commented
@vespertineSiren @VivekV95 new request came in to remove the box. so we should just have the full bg with a dim and then the animation

2021-06-03 18:52 UTC, VivekV95 requested changes
There are a couple lines within `CommonHudView` that we can un-comment that I think would be within scope, looking good otherwise

2021-06-04 16:21 UTC, VivekV95 approved these changes

2021-06-04 16:46 UTC, onodude approved these changes
looks great @vespertineSiren

2021-06-04 16:46 UTC, merged